### ISSUE TITLE
Dorgesh-Kaan Lamps to be highlighted to ease a Sherlock Challenge

### ISSUE THREAD

**Issue by simeonlg** [runelite/runelite#10069]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I am doing a sherlock challenge of Fixing a magical lamp in Dorgesh-Kaan. They are really hard to spot and are rarely broken.

**Describe the solution you'd like**
Have light orbs be highlighted, specifically the ones which needs fixing

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you've
considered.

**Comment by kblicharski** [comment]
Would also like to see this added.

**Comment by Alexgopen** [comment]
Could we have an option to enable this when not on a clue?  It would be very useful for the unconventional firemaking training method of fixing lamps.  Maybe allow object highlighting as specified by a regex, like we can for NPC highlighting.
From the wiki:
"Despite the large amount of Firemaking experience given, finding the broken lamps can be frustrating. It may be useful to make fires in the city and take quick glances at nearby lamps in hope of a broken lamp being found, though don't go asking people if they have seen any because they are different for each person."

**Comment by Nightfirecat** [comment]
Object regex highlighting should be opened as a separate request
