### ISSUE TITLE
Mine Ore Vein Motherlode Mine Ladder

### ISSUE THREAD

**Issue by BuzzfeedBlue** [runelite/runelite#10105]
Shows to mine ore vein when hovering over the top part of the ladder of mlm while on the bottom floor

**To Reproduce**
1. Go to mlm
2. be on the bottom floor (i was at the deposit box)
3. hover on the top portion of the ladder

**Expected behavior**
no hovered text

![image](https://user-images.githubusercontent.com/24302678/67150492-15652380-f286-11e9-86bd-e216ca4804bd.png)
(user in screenshot is not me, it doesnt seem to pop up while near the ladder)

**Environment:**
 - OS: Windows 10
 - RuneLite version: 1.5.37

**Comment by dekvall** [comment]
This is expected behavior.
The click box of the ore vein extends down into the floor and if you hover the top part of the ladder (which has no click box from the lower floor) from certain angles, you will actually be hovering the click box of the vein instead. This is why you can't replicate it when you are standing near to the ladder. 

![mlm_ladder](https://user-images.githubusercontent.com/25151927/67165843-2bf4a300-f38a-11e9-966f-e1b1f7642f78.png)
