### ISSUE TITLE
Improve Travis-CI execution time on non-master branches

### ISSUE THREAD

**Issue by notjuanortiz** [runelite/runelite#10128]
**Is your feature request related to a problem? Please describe.**
It's very time-consuming to fix pull requests due to the slow build times of Travis-CI. Any improvements to the feedback loop would be extremely appreciated.

**Describe the solution you'd like**
- [ ] Every module unnecessarily generates Java-docs. It should be limited to the master branch only.
- [ ] Every module also produce a jar file for each sub-project. Again, should be limited to master branch.
- [ ] Each module unnecessarily performs a clean before building each sub-project.

Ideally, non-master branches should only run the check-style, and test commands.

**Describe alternatives you've considered**
While Maven does not provide support for incremental builds, the Gradle Enterprise build cache allows us to reuse outputs of goal executions from any previous build. This helps a ton for local builds but I'm not sure any improvements can be made for production builds.

**Comment by notjuanortiz** [comment]
The concerns mentioned are closely related to those in #9078

**Comment by Adam-** [comment]
1) people PR invalid javadoc which fails at release time, which is why travis tests it. I do not like havinig suprise release-time failures since half the time it is when the client is down
2) I somewhat doubt this takes much time (packing jar files?)
3) travis checks out a clean repository each build, so it is already "clean" and doesn't need to be cleaned again, even though it does run `mvn clean install`. Removing the clean wouldn't affect anything.
4) Maven does support incremental builds - it is what happens when you run eg `mvn install` without first cleaning. If you try it you will notice it only builds changed files.

**Comment by LlemonDuck** [comment]
Travis CI is no longer used and has been replaced on PRs with GitHub Actions. Given Adam's comment above I don't believe there are other merits of this issue that need to be revisited.
