### ISSUE TITLE
Banned from the discord

### ISSUE THREAD

**Issue by chrisjohnson** [runelite/runelite#10179]
I'm not sure where else to put this. I was in the discord earlier asking for support on runelite (very politely) and then suddenly the runelite discord disappeared from my list. When I tried to re-open the invite, it said I was banned. I obviously haven't done anything wrong, can somebody investigate and fix this?

Thanks
Chris

**Comment by Adam-** [comment]
I have no interest in providing support to users who are using RL to bot or otherwise break the in-game rules, as you are obviously doing *both* from your github history. These users are a net negative to the project as it damages the projects reputation to both Jagex and the wider playerbase, which indirectly threatens the project due to the degradation of Jagex's third-party-client stance caused by it.

**Comment by chrisjohnson** [comment]
@Adam-  Oh, that's a shame. This kind of temper tantrum is the playground equivalent of "You can't be my friend if you're his friend" and it's extremely petty. I assume you are a grown adult, aren't you embarrassed by that kind of behavior yet? Doesn't this sort of "I don't like you and you can't be in my club" attitude strike you as being a "net negative to the project"?

Just so we're clear, it's trivial for me to just make another discord account and get support just as easily as ever. This kind of action does *nothing* more than to demonstrate that what is meant to be an "open source" project is actually just a way for somebody to feel self-important.

So, you haven't reached your stated goal of not giving me support. But there's one thing this does accomplish. It ensures that I will never submit an upstream improvement to this project again. And I will be sure to show off what kind of childish behavior the management of this project is capable of to anybody who will listen. I hope you will reconsider your stance but I don't expect you will.
