### ISSUE TITLE
Bank evaulator does not count untradeable items

### ISSUE THREAD

**Issue by Adam-** [runelite/runelite#1045]
Such as all barrows, most items with charges, etc.

**Comment by Adam-** [comment]
Also related #881

**Comment by Adam-** [comment]
Also related, the bank tag system and the shift click menu reordering should take this into account too.

**Comment by pnobbe** [comment]
Before looking at the source code it is already quite easy to deduce why this is happening. Untradable items obviously can't be traded on the GE and thus have no price attached. Looking at the source code of [ItemPriceLoader](runelite/runelite-client/src/main/java/net/runelite/client/game/ItemPriceLoader.java) I could think of a solution to work this out.

One way to do this is to change the ```fetch()``` function to check whether an item matches this edge case through comparing the itemId against a ```HashMap<int, Integer[]>>```, where the Key is the itemId of the untradable item, and the value is a collection of itemId's of related items. If the Map contains the key, the function in turn uses a collection of itemId's that are directly related to the item in question (think of a **Dharok's Platebody** in the case of a **Dharok's Platebody 50**, or think of **Amulet of fury + Fury ornament kit** in the case of an **Amulet of Fury (or)**. The ```fetch()``` method can then use those values in order to determine the value of the originally requested item and cache it afterwards.

The ```fetch()``` method would look something like this: 

```java
private ItemPrice fetch(Integer key) {
        try {
            ItemPrice itemPrice = null;
            // Check if the item is an untradable
            if (untradables.containsKey(key) {
                    // If it is, try to determine the actual value
                    ItemPrice[] collectiveValueItems = client.lookupItemPrice(untradables.get(key));
                    int price = 0;
                    for (ItemPrice item: collectiveValueItems) {
                        price += item.getPrice();
                    }
                    ItemPrice itemPrice = new ItemPrice();
                    itemPrice.setPrice(price);
                    itemPrice.setItem(itemService.getItem(key));
                    // Something with itemPrice.setTime(), not particularly sure how this one should work

                    // If not, look it up as normal
                } else {
                    ItemPrice itemPrice = client.lookupItemPrice(key);
                }
                if (itemPrice == null) {
                    return NONE;
                }
                return itemPrice;

            }
            catch (IOException ex) {
                log.warn("unable to look up item!", ex);
                return NONE;
            }
        }
```

Now this would require a comprehensive list of items that qualify for this edge case. If people are willing to help me create such a list I would definitely be up to try and resolve this issue. 

If people have any other suggestions on how to fix this or on how to iron out some of the kinks in the above proposition I would also welcome those.

**Comment by Stickaplex** [comment]
Something to add as well is (if possible) to account for things with charges aka bp, trident, wyvern shield so bp for example would be price of bp+equipped darts+scales. Dont kno how feasible that is but if not, its not like its a huge thing

**Comment by pnobbe** [comment]
@Stickaplex Unfortunately it's not possible to determine the contents of a trident/blowpipe, etc. What we can do however is take the contents of the rune pouch/herb sack (and other such items) into consideration.

**Comment by Adam-** [comment]
Added in #3420
