### ISSUE TITLE
Snap installed runelite client crashes on open after logging into runelite account

### ISSUE THREAD

**Issue by icorne** [runelite/runelite#10452]
On first launch, the login page loads, then I log into runelite via my google account.
Afterwards it crashes.
On a standalone way installed runelite version, it just works (via de appimage)

[client.log](https://github.com/runelite/runelite/files/3969849/client.log)
[launcher.log](https://github.com/runelite/runelite/files/3969850/launcher.log)

Is it safe for me to upload settings.properties? I've tried to anonymize it

**Comment by gregjohnson2017** [comment]
I'm having the same problem and I found that it happens when the GPU plugin is turned on. You are probably experiencing the crash when you log into your runelite account if you have the GPU plugin turned on in your saved settings. I've been trying to disable hardware acceleration in the launch parameters with `--mode=OFF`, which is how we fix it when running the AppImage, but it still crashes the snap-installed runelite for me.

**Comment by Adam-** [comment]
This is probably the same as https://github.com/runelite/launcher/pull/71 - which I don't really understand, but is something to do with ubuntu's java distribution and/or system being incompatible with the jogl libraries.

**Comment by Adam-** [comment]
I've updated the snap with the adoptopenjdk build

**Comment by icorne** [comment]
Excellent, it works now!
