### ISSUE TITLE
Discussion on balancing for option swapping

### ISSUE THREAD

**Issue by ShaunDreclin** [runelite/runelite#1050]
There's been some discussion on discord already, but good to have it in a more lasting form. Some points to cover:

- Should we allow users to fully customize left click ops?
- Should we allow users to fully customize shift click ops?
- Is swapping ops on inventory items okay?
- Is swapping ops on equipped items okay?
- We want to avoid changing XP rates, but how far do we go with that? Do we just not allow specific items to be op swapped, or do we extend that to teleportation and utility items too since they have an indirect effect on XP rates?
- What could be done to mitigate the effects of changing XP rates?
- What precedents have been set by other clients that we could follow?

**Comment by ShaunDreclin** [comment]
My personal opinion on the whole thing is we should just do whatever we want with it, barring obvious overpowered stuff.

If Jagex doesn't like any of the more questionable ones, they will have us change it or they will change things on their end to make it stop working.

**Comment by Kamielvf** [comment]
OSB already has had customizable shift click options, which I would very much like this in RuneLite as well. I've mentioned before that if there's nobody working on it by next week I'll probably pick it up myself.

As for equipment tab clicks, those items have different options from their inventory ones, e.g. ardy cloak has "teleport" in inv which opens an interface where you select your destination, and has the destinations in the equipment tab.

I'm not against making a plugin to swap the ops of equipment, as long as it does not give the user an unfair advantage exp/hr wise. Swapping ops for specific items which don't give an unfair advantage is fine tbh.

When the menu-entry plugin was added there was also a discussion on what options would be allowed since the same applies there. As long as we're not giving users an unfair advantage, it will be fine.

**Comment by Kamielvf** [comment]
Also commenting on "if jagex doesn't like it, they will have us change it" that would be correct but I'd rather avoid having jagex contact us at all, and us not pushing the boundaries of what they deem to be "OP"

**Comment by ShaunDreclin** [comment]
Yeah there's a balance we need to find between doing too much and having Jagex get upset with us, and crippling our features unnecessarily for fear of Jagex getting upset with us when they don't actually mind.

I'd say a happy medium in this case could be to allow fully user customizable shift-click ops in the inventory and equipment panel, and for the rest of the game change the left click ops only in places that aren't too OP. (Left click Trade on a shopkeeper npc is probably fine, left click Buy 50 is probably not. Left click Pickpocket on npcs with a Talk-to op is debatable, but other clients already offer that.)

**Comment by SoyChai** [comment]
I mentioned this on discord earlier, but I think a good starting point for the boundaries of "op" is to disallow 1-click ops for actions where rapid, repeated use gives an obvious advantage. Shop buying commands would fall under that category, and so would pickpocketing (whether we allow this because other clients do is the next question).

By contrast, a 1-click op on an item the player might use no more than once every ~20 seconds wouldn't really save them any gameticks.

**Comment by ShaunDreclin** [comment]
Yeah, that's a fair distinction to make. Going by how often you click the option is probably the best way to decide which ones we want to not allow or put restrictions on.

**Comment by Lalonde33** [comment]
Shift click config is a must have for high level players. It helps with click intensive skill methods.

As for how far Runelite should go. I would just mimic Osbuddy when it comes to questionable things like this. Since jagex has the hard on for osb.
