### ISSUE TITLE
Keep Bank Tags open after viewing "Worn Items"

### ISSUE THREAD

**Issue by OliverBroadbent** [runelite/runelite#10824]
**Is your feature request related to a problem? Please describe.**
I use bank tag tabs and the new "worn items" all the time, however the 2 don't work well together. Currently, when a bank tag tab is open and you open and close "worn items", the tag tab closes. 

**Describe the solution you'd like**
After closing your worn items the tag tab should stay open.

**Describe alternatives you've considered**
N/A

**Additional context**
https://i.imgur.com/VXGgS9k.gif

**Comment by dillydill123** [comment]
I had this issue when developing Inventory Setups. There were two solutions I considered:

1. Check for menu entry selected to be a specific value. This isn't very efficient in my opinion because lots of string comparisons

2. Use `onVarClientIntChanged` to detect when the button is clicked. Here is some example code:

```
@Subscribe
public void onVarClientIntChanged(VarClientIntChanged event)
{
	if (event.getIndex() != 386)
	{
		return;
	}

	// must be invoked later otherwise causes freezing.
	clientThread.invokeLater(() ->
	{
		// checks to see if the hide worn items button was clicked or bank was opened
		int value = client.getVarcIntValue(386);
		if (value == 0)
		{
			// do something
		}
	});

}
```

As you can see from the comment, this also occurs if the bank was opened. So I think there would need to be additional logic to avoid selecting the tab at the wrong times.
