### ISSUE TITLE
Marking for clue-related items

### ISSUE THREAD

**Issue by eprkr** [runelite/runelite#10855]
When toggled, any item that is required for a clue step/stash unit is marked with a small symbol or something so you know that it should go in the bank for later instead of alching/dropping. This would mostly only be useful for ironmen.

**Comment by Nightfirecat** [comment]
I've updated the title of #3105 to be more general, as this is another possible solution for bringing attention to items which are used for clue scrolls. As such, I am closing this issue in favor of that one, since there are a number of ways we could implement the feature, "I want to know which items are used in clues"; this is another possible solution.
