### ISSUE TITLE
Add Amount Healed with bank interface open

### ISSUE THREAD

**Issue by satyrsaw** [runelite/runelite#10853]
Basically, make the 'Item Stats' Plug in work with bank interface open. Maybe only when pressing shift?
This is more suitable for consumables.

**Comment by Nightfirecat** [comment]
I believe the tooltips were originally not shown in the bank interface since players could not eat/drink consumables there. Now that that's no longer the case, I don't see any reason not to add this behavior. (As a bonus, this could be hidden conditionally based on the bank settings for whether consumable menu options are enabled)

**Comment by satyrsaw** [comment]
sounds good to me!

**Comment by abextm** [comment]
Closed by #10258
