### ISSUE TITLE
Clarify Plugin Hub risk label

### ISSUE THREAD

**Issue by Matsyir** [runelite/runelite#10997]
**Is your feature request related to a problem? Please describe.**
No, simply a misleading label in my opinion, a sentiment I've seen shared by others. Many people's first reaction when they see the big bold "**Use at your own risk!**" label is something like, "oh, this a cheat client now? I won't use these because I don't want to get banned". Heard this first hand when my friend discovered the feature, and I had to explain to him that everything goes through the same checks to comply with Jagex's rules. I've seen the same thing asked about on reddit a few times. I know it may seem obvious from a developer's standpoint who knows RL's firm stance on this, but that bold label even caught me off guard and I had to check out the documentation to confirm these were still complying.

**Describe the solution you'd like**
I'm not sure what's ideal, but some ideas:
- Replace bold "Use at your own risk" label with "Stability not guaranteed", or something along those lines. The current label makes it sound more seriously risky than it is.
- Add a sentence to the initial label saying "These plugins are equally reviewed to comply with Jagex's rules."

**Describe alternatives you've considered**
Every runelite user going to the plugin hub github/runelite github wiki and getting to the part that explains these plugins are also reviewed to comply. We know that isn't going to happen, and I bet some people are still refraining from using these plugins out of fear that they don't comply with Jagex's rules. I've also noticed people have asked this a few times in discord, so it would help reduce that as well.

**Additional context**
Talking about this panel in the plugin hub:
![image](https://user-images.githubusercontent.com/28902643/76467868-fd22ac00-63c0-11ea-9581-a496700e4538.png)

**Comment by Nightfirecat** [comment]
We very much want to avoid giving any impression that these are maintained by the primary client developers, so this messaging is preferable to, say, removing the "Use at your own risk!" line. With that said, your point is valid and we would like to find better messaging which succinctly: (since space is at a premium here)

1. Explains that plugins are not supported by client devs, and that we make no promises to resolve any bugs in them basically regardless of the nature or severity of them
2. Encapsulates [our review policy](https://github.com/runelite/plugin-hub/blob/dfd2507aa569471a66282e83eec07dadeb9ba61e/README.md#reviewing) which states that plugins do not break Jagex's rules on third-party clients and are not malicious toward users

The first point is more important to us, which is why the message as-is has not been changed. We are open to updates to this so long as it maintains a clear emphasis on the first point so it cannot be confused.

**Comment by dekvall** [comment]
How about this, which should be just one more line.
```
External plugins are verified to not be
malicious or rule-breaking, but are not
maintained by the RuneLite developers.
They may cause bugs or instability.
         **Use at your own risk**
```

**Comment by Matsyir** [comment]
Yeah, I can understand your concerns Jordan. I don't have an ideal solution in mind, I'm fine with keeping the bold label as is if it's clarified otherwise. And indeed the space is definitely restricted here. I like dekvall's suggestion, pretty succinct, gets the message across without removing any of the  _"unsupported by RL devs"_ factor.

**Comment by Nightfirecat** [comment]
Shown with @dekvall's proposed text:

![RuneLite plugin hub warning label with proposed changed copy](https://cdn.discordapp.com/attachments/200118126438907906/687713814497591350/unknown.png)

Looks pretty good to me. Adds exactly one line, still maintains a good balance of the two concerns we want.
