### ISSUE TITLE
Would it be possible to keep the HTTP API responses cached for chat commands?

### ISSUE THREAD

**Issue by kylemiller3** [runelite/runelite#11000]
I would love the ability to track peoples' duel arena kills from the HTTP API but unfortunately it seems to cache the chat command for a couple minutes or so.

Can you make the last update permanently cached? I'm not sure if the other requests are but they seem to last longer at least.

Alternatively, maybe you could add webhooks to allow the client to post data to other websites kinda like the xp tracker already does but allow the user to customize the url address.

**Comment by Nightfirecat** [comment]
We could change it to cache responses, but most users like to have up-to-date stats shown when performing chat commands. What is the use case for cached responses?

**Comment by kylemiller3** [comment]
I would like to make a Discord bot to show duel arena stats and the chat API is the closest thing I've found so far that would allow me to do that. I understand it wouldn't be up-to-date until the user does "!duels" from looking at the source code and if there was a way to auto-update current duel stats after a duel that would be great.

On a semi-related note: how does the /xp/get API work? It shows responses for some of the accounts I've tried but not all of them. I'm using the latest RL for my account and am not seeing any stats for that API.

**Comment by Nightfirecat** [comment]
Chat commands which rely on stored config data&mdash;such as the `!duels` command you referenced&mdash;do not store persistent values on our servers. They are stored for a short duration (5 minutes iirc) and then purged, so you cannot rely on being able to query that data at any time. We're not interested in serving player data that way, so that's not likely to change.

The XP API is used to store player XP data to display on runelite.net using its xp tracker.

**Comment by kylemiller3** [comment]
But you do serve XP data like that? No interest in webhooks or custom HTTP POSTs plugin either so that the site doesn't have to serve these requests?

Also tell me if I should make another issue because I have all the XP trackers on but I am not seeing my stats in /xp/get and I am not seeing a section for xp tracking on the website. If you could quickly help me understand what to do to make it work and how to see it on runelite.net I'd appreciate it.

**Comment by Adam-** [comment]
Our xp tracker hasn't worked for awhile due to a combination of Jagex throttling the hiscore lookups heavily and Jagex's hiscores not being online.

**Comment by kylemiller3** [comment]
I have also run into that issue in my app. Could you not just upload hiscores directly from the client on logout in the same vein as the !duels command does (POSTs then GETs)? I understand you do not want to serve data this way but it seems like you are already doing it with these APIs so why not make a POST on logout of the users stats and fix the xp tracker?

**Comment by Adam-** [comment]
That is an option, but we have problems with users submitting fake data for themselves and other people, and it isn't clear how to resolve it.

**Comment by kylemiller3** [comment]
That makes sense. Is there an issue for this for potential resolutions?

**Comment by ypperlig** [comment]
The only 100% solution right now is to scrape hiscores. Jagex offers no other form for service except the hiscores to see xp gains.

Since Friday the hiscores have actually worked, so the xp tracker should be back up and running again now.

An alternative would be if Jagex gave 3rd parties the option to validate a RSN belongs to someone, but that's not currently possible. Even if so, the xp gains could still be fake, but it would not allow someone else to push fake xp gains for them, so the player would only be cheating their own stats,

The other alternatives would be downright horrible and a nightmare to maintain, for example manual verification of RSNs.

**Comment by Nightfirecat** [comment]
As has been mentioned, we're not interested in assuming the role of a hiscore provider or serving long lasting configuration-based values, so I am closing this issue.
