### ISSUE TITLE
Profiles

### ISSUE THREAD

**Issue by danjsmith4** [runelite/runelite#11072]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always
frustrated when [...]
I am frustrated that profiles on runelite only holds username/email, i would like it to hold passwords as well. 
**Describe the solution you'd like**
The profiles add-on to also expand to be similar to a different client that has a encrypted password and stores username and password. 
**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you've
considered.
an alternative is to use said other client when I would not want too. 
**Additional context**
I am not sure if it is possible to import the .jar file from the other client that has the plugin I really like, but if this is possible let me know.

**Comment by melkypie** [comment]
Profiles is an plugin on the plugin-hub where it is solely maintained by the plugin's creator. If you want  to make a suggestion towards a plugin-hub plugin I suggest you right click the plugin in the settings and hit the support option and put it on the plugin's repo. Here is the one for profiles: https://github.com/mlgudi/profiles

**Comment by Nightfirecat** [comment]
As mentioned, the profiles plugin is part of the plugin hub, and not maintained by us. We have avoided managing secrets of any kind in the client because of the security risk of doing so. (see #641,  #10145) I would first recommend using a password manager, possibly in conjunction with our Login Screen plugin which allows copy+pasting into the username and password fields there, or making a feature request of mlgudi for their plugin-hub plugin.
