### ISSUE TITLE
Jormungand's prison task location

### ISSUE THREAD

**Issue by Alexsuperfly** [runelite/runelite#11104]
user in discord claims that his `!task` command does not work on his basilisk task, I believe this is because the location is not whitelisted [here](https://github.com/runelite/runelite/blob/18a9a60b7d3b9bcfa55e89f364986628aefd020a/runelite-client/src/main/java/net/runelite/client/plugins/slayer/Task.java#L184).
I was also able to get a [client log](https://github.com/runelite/runelite/files/4390994/client.4.log) from them

![](https://cdn.discordapp.com/attachments/442492468307427330/692900000459522068/9bbefdcbf426fb2e95cf16c0c03ed697.png)

![](https://cdn.discordapp.com/attachments/442492468307427330/692906932381417532/0b62ff6859294114d935e6e8ad607bc5.png)

**Comment by thomaschow** [comment]
@Adam-  I'd like to take this task. I started looking at the cleint logs and I'm a bit skeptical the problem is in the whitelist as you mentioned: 

> I believe this is because the location is not whitelisted [here](https://github.com/runelite/runelite/blob/18a9a60b7d3b9bcfa55e89f364986628aefd020a/runelite-client/src/main/java/net/runelite/client/plugins/slayer/Task.java#L184).

The client logs point to a socket timeout, and a subsequent NPE [here](https://github.com/runelite/runelite/blob/18a9a60b7d3b9bcfa55e89f364986628aefd020a/runelite-client/src/main/java/net/runelite/client/plugins/slayer/SlayerPlugin.java#L784-L786). 

I wonder if [`task`](https://github.com/runelite/runelite/blob/18a9a60b7d3b9bcfa55e89f364986628aefd020a/runelite-client/src/main/java/net/runelite/client/plugins/slayer/SlayerPlugin.java#L776) is set to null here, as a result of a null return value of the underlying GSON parser. 

Is it possible to get more information from the user on what the [http params](https://github.com/runelite/runelite/blob/18a9a60b7d3b9bcfa55e89f364986628aefd020a/http-api/src/main/java/net/runelite/http/api/chat/ChatClient.java#L148) were submitted to get this Task? Alternatively, would you know how to reproduce this locally?

**Comment by Alexsuperfly** [comment]
im not too sure the log is actually related, i kinda just included it for completeness. 
Looking back it, the NPE is logged after the timestamp in the picture showing him attempting to `!task`, so its likely some other one off that did that.  

you can test the change by faking the various messages, for example change [this](https://github.com/runelite/runelite/blob/18a9a60b7d3b9bcfa55e89f364986628aefd020a/runelite-client/src/main/java/net/runelite/client/plugins/slayer/SlayerPlugin.java#L323) to just be some hard coded string and let it evaluate from there.

**Comment by Adam-** [comment]
I'm not sure why having a location as null would cause this error since most tasks have a null location (non-Konar assigned) and that doesn't usually error. May be worth looking into further.
