### ISSUE TITLE
In-Game typing 

### ISSUE THREAD

**Issue by Pingvinszar2** [runelite/runelite#11124]
I'd expect the following options to be added to the game-texting:

CTRL+A: Select all 
CTRL+D:Delete all
Modifier Key+Left/RightArrow (move left/right)
Modifier Key Up/Down Arrow: (scroll up/scroll down)

This feature would work for:
In-Game search fields.
In-Game chatting.

**Comment by Hydrox6** [comment]
Delete All is already in the client `Chat Commands`
Up/Down sounds like repeating historical messages, which is basically autotyping, and something we've rejected in the past
The other two are potentially possible but a giant pain

**Comment by Hydrox6** [comment]
Since you're making a lot of requests as if we're Jagex, I want to make this clear: We are not Jagex, we are a 3rd party client. We are bound by Jagex's banned features statement, and are limited as to exactly what to change.

Also, if you could tone down the issue spam that would be great. There are some very good ideas that you've posted, but just tone down the speed. You could also join the [Discord server](https://runelite.net/discord) if you want to chat about some of these requests before making them.

**Comment by Pingvinszar2** [comment]
> 
> 
> Since you're making a lot of requests as if we're Jagex, I want to make this clear: We are not Jagex, we are a 3rd party client. We are bound by Jagex's banned features statement, and are limited as to exactly what to change.
> 
> Also, if you could tone down the issue spam that would be great. There are some very good ideas that you've posted, but just tone down the speed. You could also join the [Discord server](https://runelite.net/discord) if you want to chat about some of these requests before making them.

Please forgive me, I didn't mean to spam.
Discord is, where I've been told to post it here, as the ideas would be lost over time.

**Comment by Pingvinszar2** [comment]
> 
> 
> Delete All is already in the client `Chat Commands`
> Up/Down sounds like repeating historical messages, which is basically autotyping, and something we've rejected in the past
> The other two are potentially possible but a giant pain

Oh great, I didn't even notice before, that it was already added, thanks.
Would it be also possible to add the "Quick-message" orbs for levels? ...or would they'd trigger bot-detection systems too..?
