### ISSUE TITLE
Add a general mob kill tracker

### ISSUE THREAD

**Issue by brainard52** [runelite/runelite#11200]
I like to have interesting stats on-hand from time to time. One of the things I'd like to know is how many of a specific mob I've killed. For example, I've killed a ton of Moss Giants in order to get Mossy Keys, but I don't actually know how many Moss Giants I've killed.

Loot tracker *almost* accomplishes this, but it almost seems as though things go missing. I think a simple kill tracker would be sufficient.

**Comment by xandyman999** [comment]
Loot tracker only tracks npcs that drop an item on death. That’s why nylocas in tob, xarpus, or sotesteg don’t get tracked but if sote drops a long bone, it will show up. Also why if a darts or arrows were to spawn the same tick they would show theyre from the npc that died on top of it and the tracker picks up that you killed a nylo that dropped a dart. Moss giants always drop bones. The chance a bone in ground despawns at exact tick another would appear, while also having no other loot is extremely fringe. The loot tracker is perfectly accurate for your use case. If you ever feel the need to test this, record your HP XP before and after to calculate the number of moss giants killed and compare it with loot tracker counter.

**Comment by Nightfirecat** [comment]
xandyman's comment is accurate. The client has no way to accurately know when a monster is killed. The best we can do is make an educated guess, like we do for the Loot Tracker plugin. We're not truly able to make a general kill tracker since nothing in the client tracks that and there's no way for us to reliably tell which player(s) killed which monster(s).
