### ISSUE TITLE
clue scroll drops in loot tracker

### ISSUE THREAD

**Issue by lv99Abra** [runelite/runelite#11416]
was doing clues while in f2p (beginner) and the loot tracker stacks the clue scrolls dropped by dark wizards (as i expect it would) when i went to p2p for medium clues, the mediums didn't stack in loot tracker and clogs up the loot (killing guards in fally) currently at ~15 clues, but when i am going for 100 it will definitely become more of an issue. dont know which one is meant to be implemented, but i would assume them stacking as if 1 drop (like every other drop that isn't stackable).

![begref](https://user-images.githubusercontent.com/22280215/80735764-cb7fb480-8ad6-11ea-8141-29686fe84d4a.png)

![medissue](https://user-images.githubusercontent.com/22280215/80735814-dcc8c100-8ad6-11ea-97c0-e190c65a8e6c.png)

**Comment by while-loop** [comment]
There seems to be only 1 beginner clue ID which is why the Dark Wizard clues are stacked.

LootTracker does not use ItemVariations for dropped loot, so each unique medium clue variation occupies a slot in the loot tab. 

I'm not sure which of the proposed fixes is better in this case.

1. Use ItemVariations in LootTracker
  - downfall is that all `CLUE_SCROLL_*` IDs maps to `CLUE_SCROLL`, so we'd have to create new variations for each tier
  - w/ the new variations I'm not too familiar with the possible regression bugs 
2. Treat clue scrolls as a separate case
  - check if the item is a clue scroll, and get the base clue ID for that tier.

**Comment by basicDamen** [comment]
Potentially utilize Immutable Sets and list each clue variant of the tier and link it to a base.
That way the builder tosses it all into a single item slot in the panel. You'd need to check if the item matches any of the set values on each drop.

Would probably link it in a separate file within the plugin for future proofing if we ever needed to add more. (Ref. RunEnergyPlugin)

Might be another way to do it, but this could be one option.
