### ISSUE TITLE
Discord plugin leaks ingame activity wile playing Deadman Mode

### ISSUE THREAD

**Issue by Nightfirecat** [runelite/runelite#11430]
Given the competitive PVP nature of DMM/SDMM/DMMT, we should not display the current activity of players on DMM. I think it would be safe to add a "Playing Deaman Mode" activity line rather than omitting it like we do for wilderness activities.

**Comment by ks0i** [comment]
Good idea but just because you have someone added on discord doesn't mean you know their username or know what account they're playing on. This would only affect streamers who are playing off stream.

**Comment by Atroxide** [comment]
> Good idea but just because you have someone added on discord doesn't mean you know their username or know what account they're playing on. This would only affect streamers who are playing off stream.

You don't have to know someone or know what account they are playing on to use this maliciously. For a comparison- people in the pvp clan scene always have their private chat off to keep from getting hunted. If you know someone plays a lot of DMM, being able to track their movement is not a good thing at all.

For me, the real question on if this should be implemented is the question- Should RuneLite remove a feature (Activity Tracker) in a gamemode simply because some players won't realize they are providing the information?

> omitting it like we do for wilderness activities.

If it is true that the Discord plugin omits wilderness activity from the tracker then it basically answers my question. We either should do both or neither.

**Comment by Atroxide** [comment]
I think this can be closed. Apparently it has already been implemented.
https://github.com/runelite/runelite/commit/d25546f5db7e13adfdda97a5020f2193329b7644

**Comment by Nightfirecat** [comment]
That commit has nothing to do with this issue.

**Comment by Nightfirecat** [comment]
I don't remember now what led me to file this issue originally--perhaps someone requesting it? I'm not sure--but it is in fact already implemented in https://github.com/runelite/runelite/blob/b35ab9aecddfc3efc6caf5014457de10cf517dea/runelite-client/src/main/java/net/runelite/client/plugins/discord/DiscordPlugin.java#L418-L422

**Comment by makingcomment** [comment]
> I don't remember now what led me to file this issue originally

Based on the OP, you wanted a "Playing Deadman Mode" activity line when playing DMM. That's different behavior than what's provided by the code you quoted.

**Comment by Nightfirecat** [comment]
I suppose that's true, but the concern was moreso that I thought that activity was leaked, not that it should have displayed some status that indicated playing DMM.
