### ISSUE TITLE
Add option to remove "Did you enjoy playing today" text/buttons

### ISSUE THREAD

**Issue by ShaunDreclin** [runelite/runelite#1167]
They're dumb and ugly. pls kill them

**Comment by SomeoneWithAnInternetConnection** [comment]
This feels like it should be closed WONTFIX. Jagex added those buttons because they're actually interested in user feedback and zapping them becasue "they're dumb and ugly" seems like a shitty thing to do. Especially since they're just on the logout panel, and not in a nag modal or some other place where you're always going to have them in view

**Comment by ShaunDreclin** [comment]
I've never once clicked them and don't intend to, so I don't see why an option for me to remove them would be a bad thing

**Comment by SoyChai** [comment]
What I see here is that we've got a case for not hiding these by default, and a case for allowing the user to hide them if they insist on it, neither of which necessarily overlap.

The only real downside of hiding these buttons is that it decreases the likelihood of a user 'reconsidering' their decision to ignore them, and Jagex may take issue with _that_.

**Comment by ShaunDreclin** [comment]
I dont think the people who go out of their way to find a config option to hide them have much overlap with people who might change their minds about ignoring them haha

**Comment by SoyChai** [comment]
Ehhh I'm not so sure, I could definitely see a user who looks at them every day becoming tempted to make the small effort of clicking NO after a particularly awful new quest. 😃

**Comment by ShaunDreclin** [comment]
(or for the meme karma)
