### ISSUE TITLE
Skill Calculator: Option to disable members-only items

### ISSUE THREAD

**Issue by Bahlokzind** [runelite/runelite#11946]
I think it would be good to add a toggle for members-only items within the skill calculator.
For a casual player like myself who is f2p (and doesn't have extensive knowledge of the game's items), it adds a fair bit of clutter to the skill calculator to have a lot of items that I'm unsure of whether they're actually skillable or not for me. I reckon it would be a nice qol change if there were a checkbox to enable/disable mem-only drops.
Thanks for your time.

**Comment by Nightfirecat** [comment]
I don't think this is worth adding since the skill calculator is not meant to explain what skilling methods are best, or how you should plan your skilling. It is only meant to calculate iterations of actions required to reach a certain goal. The wiki would be a better place to look at different skilling options.

**Comment by Bahlokzind** [comment]
Oh okay, thank you for the reply.
