### ISSUE TITLE
Add more chat colour options

### ISSUE THREAD

**Issue by Valdevon** [runelite/runelite#11959]
**Is your feature request related to a problem? Please describe.**

When using a custom chat background image (like many themes in the resource pack plugin use), some default text colours can be difficult to read. Most of them can be changed in the chat colours plugin, but not all of them

Some examples of colours that cannot be changed
- My own username in the bottom left, and the colour of unsent messages:
![image](https://user-images.githubusercontent.com/9509239/85320696-771f0280-b491-11ea-92b4-2a0f881578e9.png)

- The colour of popup messages that take up the entire chatbox, as well as the click to continue button: 
![image](https://user-images.githubusercontent.com/9509239/85320680-71c1b800-b491-11ea-8245-f1650369c365.png)

- The colour of text in crafting menus: 
![image](https://user-images.githubusercontent.com/9509239/85321046-0b896500-b492-11ea-8e05-391f6c617c8a.png)

- The colour of npc chat boxes
![image](https://user-images.githubusercontent.com/9509239/85321100-25c34300-b492-11ea-9ea8-cffad8ca7135.png)

**Describe the solution you'd like**
The addition of these options to the chat colors plugin, if possible

**Describe alternatives you've considered**
Using the default chatbox background image seems to be the only solution, unfortunately

**Additional context**
N/A

**Comment by Hydrox6** [comment]
Aside from your own Username (which would be a nice addition imo), the rest of these aren't "Chat Colours". Also, given that this is *only* an issue with an external plugin, this issue should be on the repo for that plugin.

**Comment by Valdevon** [comment]
> given that this is _only_ an issue with an external plugin, this issue should be on the repo for that plugin.

I wouldnt say its an issue with the external plugin. This would be an enhancement to the chat colours plugin which would work nicely with the external plugin, but also have some use on its own.

>  the rest of these aren't "Chat Colours"

okay, but its text that shows up in the chat box

**Comment by Hydrox6** [comment]
Only the first one is actually a part of chat. The rest are interfaces that reside in the area that the chatbox is also in; they're not part of chat. And during regular gameplay, there is no need to ever change any of those colours, since there is no way to change the backgrounds, and the contrast is good enough; nearly every colour you could change the text in those interfaces to would be terrible to look at, [as I found out before](https://user-images.githubusercontent.com/2979691/39757800-d7a570f6-52c5-11e8-8165-6f1a7caacb9d.png). There is only an issue when the backgrounds are changeable, which is what that external does, hence it's an issue with the external plugin.

**Comment by Marstead** [comment]
+1, I have decided to design a dark resource pack and it's a no go because some chat colors are not customizable. If this improvement is deemed inappropriate for the Chat Colours plugin, I'd request a new plugin be added for revamping other interface colors (Dialogue Box, text in the bank such as herb/potion overlay text and quantity #s, etc)

**Comment by raiyni** [comment]
This issue should be opened on the resource packs repo.

**Comment by Marstead** [comment]
https://github.com/melkypie/resource-packs/issues/43

I opened this request under the resource packs plugin in response to this being closed on Runelite's end.
