### ISSUE TITLE
Cannon plugin: Add "common cannon spots" for Wilderness slayer

### ISSUE THREAD

**Issue by jachymb** [runelite/runelite#12046]
I noticed the cannon plugin does not show common cannoning spots in the Wilderness (at least I noticed that for my last two tasks of Mammoths and Black demons), however for most of mobs for Wilderness slayer are cannonable. The list of relevant monsters and areas is: https://oldschool.runescape.wiki/w/Krystilia#Tasks

**Comment by Nightfirecat** [comment]
What tiles are commonly used?

**Comment by dumbitdownjr** [comment]
Hi, I'm a first timer, but I think I could tackle this since it's just adding new WorldPoints to the CannonSpots enum. There are a couple things I need to figure out first though.

First, how are optimal cannon spots for each monster determined? I was searching for a guide for all cannon spots or similar, but I haven't been able to find anything close to comprehensive, and I found nothing with the best tiles for wilderness slayer monsters. I guess I'm wondering how the current list of best tiles was created, so I can figure out which are the best tiles to add for wilderness slayer.

Second, I'm haivng a hard time figuring out which tiles each WorldPoint belongs to. I've been looking at the WorldPoint definition, but I'm still confused as to how the system works, so once I find the tiles to add I can create the corresponding WorldPoint coordinates for them.

**Comment by Nightfirecat** [comment]
1. We use the spots given to us by contributors. Generally speaking, they have a good sense for what tiles are optimal.
2. [Use the client's developer tools](https://github.com/runelite/runelite/wiki/Using-the-client-developer-tools)

I recommend [joining our Discord server](https://runelite.net/discord) and asking questions like these in our `#development` channel. (read the channel description for directions on how to chat there)

**Comment by jachymb** [comment]
Clarification: I noticed there ARE some cannon spots in the wildy, namely in rev caves. I missed cannon spots for 1) black demons in Edgeville dungeon 2) Mamooths 3) scorpions. There are probably much more mobs without recommended cannon spots.

**Comment by dumbitdownjr** [comment]
I just went through all the cannonable wilderness slayer monsters, and you're right there are some missing ones. So far, I've been been able to find optimal cannon spots for 4 monsters that have missing spots: black knights, fire giants, scorpions, and zombies. Most of the rest of them are cannonable, but are not commonly cannoned (lava dragons or bears for example). There are some that should be added that I haven't found optimal cannon spots yet such as greater demons and black demons. 

One small correction is that mammoths do have a cannon spot already right next to the wilderness obelisk.
![image](https://user-images.githubusercontent.com/28718724/87121867-5d2f3f00-c249-11ea-9f1d-9eac595d2596.png)
