### ISSUE TITLE
exp in Skill Calculator for Maple Longbow (U) is wrong

### ISSUE THREAD

**Issue by d4ddyc00l** [runelite/runelite#12056]
It says its 58.5 exp but it should be 58.3 exp

**Comment by Nightfirecat** [comment]
I've updated the original post because none of the information you provided was accurate.

* The skill calculator does not say that Willow longbow (u) gives 50 exp
* It should not say that it gives 58 exp [(58.3 is the actual amount)](https://oldschool.runescape.wiki/w/Maple_longbow_(u))

It is, however, incorrect as it stands, as it states it gives 58.5 exp instead of the correct 58.3.
