### ISSUE TITLE
Entity sound hider

### ISSUE THREAD

**Issue by fennecOS** [runelite/runelite#12360]
**Is your feature request related to a problem? Please describe.**
At the moment, I play with ingame sound and it's really annoying to skill and also hear other skillers' sounds layered on top of mine, but don't want to play with entity hider to get rid of them, I find myself always having to hop in order to find a place where I can skill in peace.

**Describe the solution you'd like**
Could either add an "Entity sound hider" or just add another bit of options to the entity hider itself. This could go hand-in-hand with annoyance mute which I also use, but doesnt have those kind of options

**Describe alternatives you've considered**
I've asked around and it seems the only way to do this is to just enable entity hider but I dont exactly want to hide everybody else, I just want to hide their sounds.

**Comment by Broooklyn** [comment]
I could look into adding something like this to Annoyance Mute, although it might not be entirely possible in the way you described since some sounds have the same source regardless of whether they originated from you or another player. 

Although now that I think about it, you should be able to enable `Mute other players' area sounds` in the `Music` plugin, that might work for what you're describing, although due to what I mentioned above, it won't catch every sound, but you can open an issue on my Repo if you find any outliers.

**Comment by fennecOS** [comment]
alright, thanks! I'll use that, I did not know that was an actual thing. Looking at the music plugin in general seems like these options should be somewhere else where they'd make more sense, but it's good to know that they are there!

I will take note of any outliers
