### ISSUE TITLE
Grand Exchange plugin log file.

### ISSUE THREAD

**Issue by GETrackerDan** [runelite/runelite#1250]
Would like to see the plugin have the option to log each buy/sell trades from Grand Exchange into a txt file with timestamps.

If it's possible to only log the items when the offer has fully completed in grand exchange so you don't have multiple lines of the item log due to buying multiple items.

Example:
**[03/04/2018] [04:45] 200 Bronze bars sold [Total 38200gp] [Each 191gp]**

This would be an ideal addition to those like that keep track of profits/losses on their trades.

**Comment by deathbeam** [comment]
I don't think we really want to use external resources like this, only "store" we should use is the config manager.

**Comment by SomeoneWithAnInternetConnection** [comment]
Support for a (*write only*) external resource makes sense, especially if we were to use CSV (or a similarly spreadsheet-able format), since I suspect many folks who are actively trading probably use spreadsheets.

On that note... @GETrackerDan Would having information about partial trades be useful? Or are you only interested in finished trades?

**Comment by GETrackerDan** [comment]
.CSV is ideal, and works for me as I use spreadsheets to track.

For me personally,  partial trades gives me the impression of multiple lines of the same data apart from the date/timestamp until my order is fully completed, so if you are selling 20k ores your going to have a large file in possibly a shirt period of time and I'd prefer if it was only logged once the offer/sell has been fulfilled.

Would be interested to see other people's opinions on that as if it is something others would prefer could it be some type of toggle option  to either log partially fulfilled or completed.

**Comment by psikoi** [comment]
Why not just log when trade is accepted or when it's cancelled? this would avoid all the triggers in between.

**Comment by SomeoneWithAnInternetConnection** [comment]
There's no technical reason for it to be one way or another, but my thinking was that having information about partial trades included in the log would allow for more accurate price (since price/item isn't always going to be the same for each partial fulfillment) and trade-rate data. That sort of thing probably only *really* matters if you're trading huge numbers of items, but I suspect you could make some pretty graphs out of it regardless :P.

Given the potential issue with filesize that @GETrackerDan mentioned, it seems like a toggle is probably worthwhile here.

**Comment by psikoi** [comment]
Then maybe the solution would be to track the start, end and all the small increments in between, and allow the user to choose if they want to see the small increments or not (to make the spreadsheet cleaner)

**Comment by deathbeam** [comment]
I think the decision was that if we implement this we store it on remote and display on website. Local log is useless because its just log not useable within runelite
