### ISSUE TITLE
WikiPlugin does not open quest guides

### ISSUE THREAD

**Issue by kmarius** [runelite/runelite#12570]
**Describe the bug**
Right clicking a quest in the quest guide gives the options to open a (quick-) quest guide from the wiki in the browser. Neither option works.

**To Reproduce (for me)**
1. Open quest list
2. Rightclick any quest
3. Choose Guide: .. or Quick-guide: ..
4. A chat message appears that a guide has been opened but nothing happens.

**Expected behavior**
The quest guide from the osrs wiki should open in the browser

**Environment (please complete the following information):**
 - OS: ArchLinux 5.8.10-arch1-1
 - RuneLite version: 1.6.27, 1.6.28-SNAPSHOT
 - Launcher version: 2.1.3
 - Java (native): openjdk version "14.0.2" 2020-07-14, and whatever is included in the AppImage

**Additional context**
The test at https://github.com/runelite/runelite/blob/273ebdeebf7f5c63a5fe43aef7f199926d3d4e79/runelite-client/src/main/java/net/runelite/client/plugins/wiki/WikiPlugin.java#L341 fails. I found that `ev.getMenuAction()` equals `MenuAction.CC_OP`. Changing this makes it work.

**Comment by Nightfirecat** [comment]
I can't reproduce this. Both the `Guide` and `Quick-guide` menu options work fine on release for me.

**Comment by MrCarroll** [comment]
It was mentioned in Discord that the default client asks to copy and paste the URL manually. This occurs because Java on Linux dynamically loads GTK to have it actually handle opening the link. RuneLite itself then falls back to xdg-open if this first GTK call fails (I think Adam implied that this specific button on the UI is a vanilla interface and thus might not be covered by the xdg-open fallback, but I don't play the game so correct me if I'm wrong.)

In Ubuntu, the relevant package for the library with the GTK function needed ends up being GVFS. I'm not sure what the Arch equivilent would be, but this is why the vanilla/upstream client fails. I get the impression that this is what's happening in this specific instance too.

**Comment by abextm** [comment]
This is a vanilla feature, not ours. The package is [gvfs](https://www.archlinux.org/packages/?q=gvfs) on arch too. Vanilla doesn't fallback to xdg-open, it only uses java.awt.Desktop
