### ISSUE TITLE
Changes in the Zuk/jad collection log shown in "look up"

### ISSUE THREAD

**Issue by cristherino** [runelite/runelite#12680]
it would be amazing to see the zuk/jad kcs of each person from kc 1 when u use Look up on them, they are not usual bosses that u can do 50kcs+ to show them in the look up section

![b4c6b88922f1891e444e40b5d7df8b71](https://user-images.githubusercontent.com/73307188/96909227-becb9000-146b-11eb-93f6-cc694f8a6931.png)

**Comment by Nightfirecat** [comment]
You must be ranked on the hiscores in order for these to appear. We cannot look them up otherwise, as we're not relying on collection log/boss log for the hiscore plugin. As-is, hovering those bosses (and any other unranked bosses) will mention that you are unranked in them.
See [this comment](https://github.com/runelite/runelite/issues/5146#issuecomment-457866269) and  #12393.
