### ISSUE TITLE
[Leagues] Teleporting through the Areas interface sets off the Home Teleport timer

### ISSUE THREAD

**Issue by ShaunDreclin** [runelite/runelite#12779]
**Environment:**
 - OS: Windows 10
 - RuneLite version: 1.6.32-SNAPSHOT

**Comment by Nightfirecat** [comment]
I see the issue here. Ordinarily, there's no other way to proc a teleport, so we never needed to null the `lastTeleportClicked` field. Now that there is, it will create a timer for whichever teleport you've clicked most recently prior to an area teleport--whether that be a minigame or home teleport.

https://github.com/runelite/runelite/blob/master/runelite-client/src/main/java/net/runelite/client/plugins/timers/TimersPlugin.java#L449-L454

I feel the easiest way around this would be to create another TeleportWidget entry for the area teleport so as not to follow the pre-existing home/minigame teleport code paths following the last animation.
