### ISSUE TITLE
Inconsistent XP drop recoloring when 1t flicking

### ISSUE THREAD

**Issue by SomeZer0** [runelite/runelite#1280]
When 1t flicking (without overheads), some XP that is gotten on the same tick is not recolored, while the other is.
https://vgy.me/23KqGN.png
https://vgy.me/Q5HTta.png
https://vgy.me/5yWldf.png
Note that this XP is gotten on the same tick, so.. Both, or neither, should be highlighted, not just 1.

However, when 1t flicking with overheads, the recoloring seems to be consistent.

**Comment by deathbeam** [comment]
Is this still issue?

**Comment by Nightfirecat** [comment]
I've noticed it on last week's build--any combination of the three highlight possibilities (first skill only, both skills, or second skill only) can be obtained by changing timing of clicking the prayers. Interestingly, I hadn't run into this when using the quick-prayer orb, only when using the prayer menu directly.

**Comment by SomeZer0** [comment]
This is still an issue.

**Comment by Nightfirecat** [comment]
The issue is that the XP drop is only recolored if the associated prayer icon--let's say Piety--is highlighted locally in the client. When flicking with the quick-prayer orb, it always matches the server ticks. When flicking manually in the prayer menu, it often flickers around tick boundaries. In addition, if you flick the prayer off before the HP exp drop appears, it is no longer highlighted. (and vice-versa, you can miss a flick, but enable Piety before the next tick to have the HP exp drop highlighted)
