### ISSUE TITLE
Hide Helmets?

### ISSUE THREAD

**Issue by SirZandro** [runelite/runelite#12856]
It would be cool to be able to see your head without having to leave the helmet space empty.
Perhaps one option to hide your own and other to hide everyone elses?
This could maybe be added to the entity hider?

**Comment by Hydrox6** [comment]
Players in the game are built out of "kits", with each kit being a part of the body. Each visible slot of armour has a slot, plus hair jaw and shoulders. Depending on what the player in question is wearing, certain slots will be hidden (eg. you don't have hair when wearing a full helmet, or shoulders when wearing a chestplate). Since they're hidden, the client doesn't actually know about them; it just gets told to display these armour pieces and it does.

Hiding your own helmet would be possible, though with a bit of setup. Hiding other people's helmets is basically impossible without some inter-client communication, and given how small and niche this is it's probably not worth the server time.

I agree though, a "plot armour" feature would be quite cool; the slayer helmet is really boring to look at, even with recolours.

**Comment by markthequark** [comment]
This feature can be found in the transmogrification plugin  
https://runelite.net/plugin-hub/show/transmog
