### ISSUE TITLE
More configurable text size.

### ISSUE THREAD

**Issue by SomeZer0** [runelite/runelite#1288]
Previously the text size was pretty perfect.

Currently (April 5th patch), if you don't have "Runelite -> Use smaller font for overlays" enabled, the ground item text and item tooltip boxes/text is extremely large. This can be fixed by enabling that option. However, this doesn't get things back to "normal."

Currently, if you have that option enabled, it shrinks the text of pretty much every other overlay.
(It seemingly does not change inventory overlays. **Please**, let those stay the same size!)

It would be nice to have an option with all the overlays how they were, (Smaller text on ground items/tooltips, larger text elsewhere) or an option to configure text size for specific overlays.

/end nitpick

**Comment by SoyChai** [comment]
Although full UI consistency was one of deathbeam's goals when he implemented this setting, I agree that more granular settings wouldn't hurt at all. Especially since the game itself uses such a diverse range of font sizes.

**Comment by SoyChai** [comment]
Letting it be customised per-overlay would be overkill, I agree. I think this request is for ground items and tooltips though?

I can see an argument for both, since they're both unique compared to any other Runelite overlays:

- Ground items because the lines of text indicating drop stacks can be an especially tall and messy overlay
- Tooltips because they follow the cursor around and become more obscuring at larger text sizes

**Comment by deathbeam** [comment]
Solution to this is obviously DPI scaling. And for differentiating between sizes of ground items, tooltips etc solution is add option for dynamic and non-dynamic overlays I guess. Or maybe just change the font size only for dynamic ones and leave our ones same as xp tracker.
