### ISSUE TITLE
[Shades of Mort'on] Trigger notification at 100% Sanctity

### ISSUE THREAD

**Issue by Marstead** [runelite/runelite#12906]
**Is your feature request related to a problem? Please describe.**
Repairing the temple at Shades of Mort'on is a primarily idle activity. When the player reaches 100% Sanctity, they are no longer able to accrue additional Sanctity until "dumping" it by converting olive oil to sacred oil (or upgrading Serum 207). However, the player is able to continue repairing the wall even at 100% Sanctity, wasting time and repair resources. 

**Describe the solution you'd like**
I would like to be able to set RuneLite to trigger a notification when the Temple Repair state reaches 100% Sanctity. This will help with idle play at this minigame.

**Describe alternatives you've considered**
It would be even better if we could specify the Sanctity % threshold at which to trigger the notification, if that's possible.

**Comment by KhaiQ** [comment]
Hey there! Seems like quite a while since you requested this, but I recently have been working on a plugin that revolves around creating Sacred Oil. This plugin can send you a notification once your sanctity passes a User designated threshold in addition to a few other features. I'm still waiting on it to get fully verified by the RuneLite team but if you want to get access to it now, you can find it in my repos or click this link: https://github.com/KhaiQ/sacredoil

Please feel free to message me any bugs you find or features you would like to see added!
