### ISSUE TITLE
Door marker on Hespori exit

### ISSUE THREAD

**Issue by REALmrhalk** [runelite/runelite#12900]
**Is your feature request related to a problem? Please describe.**
Not really, just a quality of life improvement. The Hespori exit is rather small and "hard" to find.

**Describe the solution you'd like**
Highlight the exit to the Hespori boss for small quality of life imrpovement.

**Describe alternatives you've considered**
My cc friend suggested going into object markers and marking it myself, so I am going to do that now.

**Additional context**
I thought of not suggesting this since my cc friend suggested the object marker idea, however I had already made the github account so I figured why not.

**Comment by Nightfirecat** [comment]
This seems like the ideal use for the object markers plugin like you've mentioned. I don't think highlighting it by default would fit in anywhere else.

**Comment by Hydrox6** [comment]
Yeah, this is definitely an Object Marker use case. There's a load of stuff people *want* highlighted in the game, so much so that if we did highlight them, the game would look like a wireframe and would be horrible to look at. Hence, there are multiple fully customisable plugins to mark Objects, NPCs, and Tiles.
