### ISSUE TITLE
Option to bound context menu within game frame in fixed mode

### ISSUE THREAD

**Issue by kentor** [runelite/runelite#12927]
**Is your feature request related to a problem? Please describe.**
I typically play in fixed mode, and it's annoying when I need to switch to resizable mode to use no-mouse-movement training methods for construction or blackjacking. 

**Describe the solution you'd like**
Make the right click menu bounded within the game frame in fixed mode, i.e. so that the menu doesn't go over the chat area. 

**Describe alternatives you've considered**
No alternative than to be annoyed to have to change to resizable mode.

**Additional context**
I can try to program this, but  not sure if it's possible to move the context menu around?

**Comment by Hydrox6** [comment]
Assuming you meant the viewport (as the game frame includes the Inventory and Chatbox UI stuff), it probably wouldn't be a good idea to mess with this, especially since the menu can appear on that UI normally; there'd be some weird interactions with having the menu appear closely outside the viewport.

This would also require internal changes, and for such a niche thing it's probably not worth the upkeep internal changes cause.

If this were something that's entirely impossible, then maybe, but given you can get this functionality in either resizeable mode (as you said), it would be much easier and more consistent to just use that instead.
