### ISSUE TITLE
Suggestion: Add chat messages to Time Tracker so when a (notification turned on) timer is finished, a chat message is sent rather than flashing the screen

### ISSUE THREAD

**Issue by MyJorts** [runelite/runelite#13240]

**Comment by Hydrox6** [comment]
All of these are controlled by the general notification settings founder under `RuneLite`. What you're requesting can already be done with `RuneLite` -> `Enable game message notifications`. imo this shouldn't be implemented on a per-plugin basis, since things will get incredibly messy. Something like #10404 is probably the way to go here, allowing each plugin to say how they want their notification to appear.
