### ISSUE TITLE
[Mac OS] Full screen bugs when opening a tab and then closing. 

### ISSUE THREAD

**Issue by CnPx98** [runelite/runelite#13303]
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)

**Describe the bug**
When going into full screen mode when opening any tab and then closing it the game does not snap back to full size and there is a black area the same size as the tab down the side. To put the game back to full screen you need to select the green button in the top left to make the window smaller and then go back to full screen again. I am using a 2016 MacBook Pro running Mac OS Catalina 10.15.7

**To Reproduce**
Open and close tab in fullscreen.

**Expected behavior**
The game to go back to full screen when closing a tab. 

**Screenshots**
<img width="1280" alt="image" src="https://user-images.githubusercontent.com/72352047/109855399-1f57ae80-7c50-11eb-87e6-46d36875008b.png">

**Environment (please complete the following information):**
 - OS: Mac OS Catalina
 - 1.7.2.1
 - 2.1.5

**Comment by jeremybahadirli** [comment]
I've looked into this and have learned a few things.

1. When closing the plugin panel or sidebar _in windowed mode_, the client's `ContainableFrame` contracts by the width of the closed component. This is to keep the game at the same size and "pull in" in the sidebar, rather than keeping the window at the same size and widening the game to compensate. This behavior is togglable in RuneLite > Resize type.
2. RuneLite's integrated fullscreen ("maximized fullscreen") is used when clicking the "Custom window chrome" maximize button. This is roughly equivalent to the macOS option-click green button, which expands the client to fill the desktop space, without entering a macOS native fullscreen space. This sets `ContainableFrame`'s "extended state" to `Frame.MAXIMIZED_BOTH`, indicating it is maximized in both the vertical and horizontal directions.
3. Entering macOS native fullscreen does not modify the frame's extended state. In macOS native fullscreen,  `ContainableFrame`'s extended state is `Frame.NORMAL`.
4. When a component is closed, the `ContainableFrame` checks its `isFullScreen()` method prior to contracting. If true, `ContainableFrame` will not contract, because the window should continue to take the full screen width when in fullscreen.
5. `isFullScreen()`'s implementation checks the "extended state" to determine whether it is fullscreen, as follows:

`	private boolean isFullScreen()`
`	{`
`		return (getExtendedState() & Frame.MAXIMIZED_BOTH) == Frame.MAXIMIZED_BOTH;`
`	}`

6. Since `isFullScreen()` checks the extended state to determine if the game is fullscreen, and macOS native fullscreen does not set the extended state to `Frame.MAXIMIZED_BOTH`, the `ContainableFrame` contracts when closing a component in macOS native fullscreen, causing the black area. Essentially, the client thinks it's in windowed mode.
7. There are multiple ways to solve the issue. To me, the most logical would be to set the `ContainableFrame`'s extended state appropriately when entering or exiting macOS native fullscreen.
8. To my knowledge, there is no way to query the current macOS fullscreen state. It is, however, possible to attach a `com.apple.eawt.FullScreenListener` to the window, triggering a `com.apple.eawt.event.FullScreenEvent`when entering or exiting fullscreen, which could be used to set the frame's state appropriately.
9. Unfortunately, RuneLite's `orange-extensions` is incompatible with the current `java.desktop`'s `FullScreenEvent`.
	java.desktop: `com.apple.eawt.event.FullScreenEvent `
	orange-extensions: `com.apple.eawt.AppEvent.FullScreenEvent `
10. Ideally, RuneLite will need a multi-release `orange-extensions` to enable compatibility with the current Apple fullscreen api.
11. There are other ways to bandage a solution, such as checking if the window expands the full screen width, rather than using `isFullScreen()` when on macOS. These solutions are not ideal.

Thankfully, **this issue can be temporarily fixed** by setting RuneLite > Resize type > Keep window size, in the RuneLite configuration, for reasons that should now be clear.

**Comment by Adam-** [comment]
> 9\. orange

I've made the required changes to orange-extensions for Java 11 https://github.com/runelite/OrangeExtensions/commit/2151440281b73126583c7b6fdf053ff1b043ffba

**Comment by Adam-** [comment]
fixed in #16696
