### ISSUE TITLE
feature request: qwerty keyboard pluggin?

### ISSUE THREAD

**Issue by shreaper** [runelite/runelite#13320]
I'm sure a lot of us use the microsoft on-screen keyboard, and have noticed that using it with the client is very annoying at times. whether it be that the shift button doesn't stay on as you use other applications, or it covers the gameplay when in use. So, why can't we have a keyboard plugging which will only work on the client itself? we have a calculator plugging why not a keyboard?

**Comment by Hydrox6** [comment]
I feel this would have room for abuse, and re-implementing a system feature for such a narrow use case feels highly excessive.

> the shift button doesn't stay on as you use other applications

This is likely due to how the onscreen keyboard handles focus switching, not specifically due to RuneLite

> it covers the gameplay when in use

Unless you have the tiniest screen, why not just move the keyboard? If the issue is that it's always on top, look into making it not do that, or making it partially see-through. Again, not really a RuneLite thing

> we have a calculator plugging why not a keyboard?

There is a very big difference between an application that does maths on what you tell it and a piece of software that provides input to the game.

> I'm sure a lot of us use the microsoft on-screen keyboard

I see a lot of the messages that come through the server, and I can recall very few people even mentioning using the onscreen keyboard; usually it's people telling other people to use it for a sticky shift.

It also might just be worth finding a program that does it better. I use Linux (btw) and the one that came with my distro (Onboard) doesn't really have any of the issues you mention due to being able to configure it.

Personally interested in hearing what other people have to say about this.

**Comment by Nightfirecat** [comment]
We're definitely not interested in implementing an onscreen keyboard for input to the game

**Comment by shreaper** [comment]
> 
> 
> We're definitely not interested in implementing an onscreen keyboard for input to the game

Thank you for considering it, I'll just have to make due with the onscreen keyboard then.
