### ISSUE TITLE
Accessibility: Font Size

### ISSUE THREAD

**Issue by YourFriendJessie** [runelite/runelite#13357]
Game font too small and sometimes unreadable.

Solution: Setting to change game font to .12

Alternatives:
N/A

**Comment by Hydrox6** [comment]
The game font is just a series of statically sized images; you can't just "change the font size"

Either way, it doesn't matter since `Stretched Mode` makes the UI bigger, which also makes the font bigger, and the client itself is DPI aware (at least one Windows, and with launcher version 2.0 and higher).
