### ISSUE TITLE
Random Game Crashes

### ISSUE THREAD

**Issue by jackpakela-pq** [runelite/runelite#13356]
Here's a quick description: Sometimes when I'm playing OSRS on the Runelite client (Windows), the game will freeze (for about 3 or 4 seconds), and then automatically close out on its own. When viewing the logs folder, I'm not seeing any notable information that relates to the game crashing. I'm not really sure why this is happening. My PC isn't incredible, but it has the specs certainly to run OSRS on Runelite. For example, in a log file... There is multiple lines where it says:
**2021-03-20 --:--:-- [RuneLite] INFO  net.runelite.client.RuneLite - RuneLite 1.7.2.2 (launcher version 2.1.6) starting up, args: none**

Most of this is because I need to reopen the client after it randomly freezes and closes automatically. Not sure what's happening. I did uninstall an external plugin as well, and soon after doing that, it crashed again (coincedence?)

**Additionally, here's the locations/actions that cause these crashes:** Either I'm killing Demonic Gorillas, or I click on a Emote (such as Dance), and it will sometimes cause this freeze & exit out glitch to occur. Generally though, I can get through hours of gameplay without crashes. In fact, this only happens once every couple weeks on average, so it's quite rare. Any ideas of why this is happening? Maybe I need to clear cache, but I'm not sure how to do that. Should I switch over to the 'all platforms' client? Also, this happens if I leave a client open for too long throughout the day. If I close out of the game after I'm done playing for a little bit, and hop on later and open a fresh client, then the issue occurs less.

Yes, my graphics card drivers are up to date, and yes so is my OS. Please help me if you can. Thanks.

I've had this issue occur as well on the Jagex OSRS client on another laptop. Is it possible it has to do with RAM/Virtual Memory, and it just closes out because of that? I've heard people telling me to "Turn off GPU" in the Runelite settings, but I honestly don't think that's the issue here. Thanks for your help!

**Comment by Nightfirecat** [comment]
Are there any `jvm_crash_pid` files in your log folder? Do you have any windows logs (from the built-in error reporting program or otherwise) of this crash?

This is likely caused by a driver issue, even if your drivers are up-to-date, so we may not be able to fix it.

**Comment by Juhkela** [comment]
> Are there any `jvm_crash_pid` files in your log folder? Do you have any windows logs (from the built-in error reporting program or otherwise) of this crash?
> 
> This is likely caused by a driver issue, even if your drivers are up-to-date, so we may not be able to fix it.

I haven't gotten any of those errors, but on previous logs I've had:
**2021-03-05 02:10:05 [Client] ERROR n.r.c.p.t.farming.FarmingTracker - Offset error! Observed new offset of 10, previous observed offset was 5 (5) Player Loc:WorldPoint(x=2671, y=3376, plane=0)**

**2021-02-28 20:10:10 [pool-3-thread-1] WARN  n.r.client.ClientSessionManager - Resetting session
java.net.UnknownHostException: api.runelite.net**

Sorry, this is all I could find (after scanning through all of my logs). If it is a driver issue, do you have any suggestions for what I could try out? I'm wondering if it could relate to Memory usage. Runelite causes Memory to be high (60-70% plus) when looking in the Task Manager. That combined with browsers open might cause a crash like mine? I'm wondering if Discord could be related as well since I've heard there are people who've had similar issues. 

Additionally, I've had this exact same thing happen on another laptop (using the Official Jagex OSRS Client), so I'm not sure. 
If this helps as well, I do have **Throttlestop** running to limit my CPU output to 2.0 GHz at all times when playing (this helps keep my laptop temperatures down - I would undervolt if I could, but intel due to intel locked their i5-1035G7 chip due to plundervolt). Perhaps I could try running without having throttlestop on?

**Comment by Juhkela** [comment]
**UPDATE:**
Looks like Windows had a critical update. I performed the update, and we are 2 days in without any crashes like the one described above. Will comment again if it happens again though.
