### ISSUE TITLE
Client redesign suggestion

### ISSUE THREAD

**Issue by psikoi** [runelite/runelite#1342]
Me and the fellas over at the #development discord channel have come up with a few improvements to the current client UI, these are my proposed changes and I'm open to any suggestions or feedback.

# The main client frame
I feel like the current one is too "default-looking" and needs a bit of personality, in all my mockups bellow, a couple of changes I made were:
- Having my **new and unofficial** logo on the top left corner
- Having the discord/login/screenshot buttons slightly seperated from the minimize/maximize/close buttons to avoid confusion **(This is unfinished as I do not know where to place the buttons)**
- Darker colors on the top bar and side bar (this improves contrast between client UI and the game itself)
- Having the "selected" indicator of the buttons be a slightly darker color behind them

![](https://i.gyazo.com/a22b499561b517fc685b967573d51c4c.png)

# The grand exchange plugin (side panel)
There was nothing wrong with the current version, I just wanted to apply some of the new design rules to make it more modern, get rid of the borders and use different shades of grey for contrast and separation, changes made were:
- Material design style tabs
- Taller search bar, to give it more room to breathe (and removed border)
- Smaller and lighter search icon, just looks better imo
- Removed the borders on the ge item results
- Smaller and simpler scrolling bar that matches with the rest of the design

![mockup ge](https://user-images.githubusercontent.com/3278148/38569731-fdee52f2-3ce3-11e8-9129-df390114d9d1.png)

# The hiscores plugin (side panel)
The hiscores panel had some issues, nothing to big, it just needed to be realigned with my new proposed look, a few changes were made:
- Made the search bar more in line with the rest of the dark layout
- Moved the account type button to the top, this follows a more logical sequence (Search Name -> Select account type -> View results)
- Changed the selection indicator on the buttons to a orange underline
- Reduced the size of the font on the skill levels
- Removed the bottom information panel as it was occupying a lot of unnecessary space, moving it to a on-hover action, this is also more inline with the current in-game behaviour
- Switched the order of the combat/total level indicators, to match the ingame order

![mockup hiscores](https://user-images.githubusercontent.com/3278148/38569813-37d57a0e-3ce4-11e8-9025-8e7018ff2cc1.png)

# The config side panel
Again, I think there is nothing wrong with the configs panel, just changed it a bit to match the rest of the design, changes made were:
- Darker colors
- New search bar
- Removed the square around the buttons, to give it a cleaner look
- Added a line separating the configs, just to give them some structure
- **On the second mockup only:** instead of lowering the opacity on the wrench icon, I just removed it
to avoid user confusion

![mockup config oldschool](https://user-images.githubusercontent.com/3278148/38569887-65c9035e-3ce4-11e8-8726-288e4b9f4ca0.png)

## After some discussion on discord, some people asked me to try a material switcher look to the configs, here is that:

![mockup config material](https://user-images.githubusercontent.com/3278148/38569903-6f47baec-3ce4-11e8-8f10-083813c72541.png)

# The XP Tracker plugin (side panel)
Many people like this plugin as it is, I think it could be better, however I'm not sure I have the solution, either way, here's an attempt:
- Made the progress bars have rounded corners
- Changed the progress bars' colors to match the skill icon
- Changed the skill icon to be darker, so that the level on top of it stands out more
- Made the expanded tracker information different, following a "Key: value" structure, keeping the value in white to make it stand out.
- Reduced the size of the total exp indicator
- Moved the reset all button to the right side

![mockup trackers](https://user-images.githubusercontent.com/3278148/38569994-a2a6f10a-3ce4-11e8-8234-df71b82ca1e0.png)

# PS: I'd be happy to develop some custom components to help these changes

**Comment by Stickaplex** [comment]
Personally I like it how it is currently but not like I have anything against your version so if I'm outvoted I won't complain too much =p

As for functionality I really only have one thing that I saw that needs addressing after a quick look through and thats the last thing you posted "XP Trackerplugin". The reset button imo needs to be at the top because if you have enough skills "open" it creates a scroll and I would rather not have to scroll to reset.

**Comment by Infinitay** [comment]
In addition to what Stickaplex said, instead of centering the reset all button, you could add another label showing your Total XP gained for this session, and keep the reset on the right if you wanted to

**Comment by SomeZer0** [comment]
This looks nice

**Comment by LeviSchuck** [comment]
Here be my comments with the perspective of a web developer.


## Main client frame: 
1. The logo is more striking and less noisy, I think that's a good thing for recognition. However to my eyes it also looks like a cape or even close to the logo of impactjs http://impactjs.com/ I do like orange and dark neutral though.
2. Is client version useful to end users? They have to update whenever runescape updates anyway. I say throw this out.
3. The spacing seems unnaturally decided. I do think it is appropriate to separate these user-actions from the OS controls. Perhaps a horizontal bar between? Or something more fancy like a curve color change for the backdrop--isolating it from the user actions.
4. This darker color is pleasant.

## Grand exchange plugin:
1. I already like the tab underline / centered styling. 
2. I feel the spacing between the search bar and the tabs is unnatural
3. The bolded 'whip' text is surprisingly harder to read
4. It's nice the icons show up..
5. Do we want to show alc prices when they are zero? (This is probably more change in behavior)
6. The borders indeed are unnecessary when going more material style.
7. I like the new scroll bar, it is closer to what discord has as a reference.

## Highscores:
Really you should use the same user as a reference so we don't see a difference in data..
1. I do like the icons having their own boxes for *man mode selection. It also seems appropriate at the top as it changes what you see.
2. The tooltip seems nice. It is easy on the eyes. Consistency with in game behavior is `trippple+++;`
3. I do like the alignment of the total indicators.
4. The trophy seems more appropriate than an arbitrary blue star. 

## Config side panel:
1. Really not sure what is up with this bold font, it is harder to read and makes my eyes want to defocus.
2. I like the better contrast with the background and the icons.
3. Should we just not show a wrench when there's no settings, rather than a dimmed wrench?
4. Line separations does help keep the titles and affordances easier to coordinate. However this is inconsistent with the material design inspired display in the grand exchange plugin

RE: Material switcher
I do like the toggle switches easier. The color difference is nice, though the value needs a bit more work. 
![plugin-demo-gray](https://user-images.githubusercontent.com/245911/38535384-d02a498e-3c48-11e8-9931-9f8eaad17302.png)


## XP Tracker plugin
1. I like these rounded borders. 
2. The colors, like red, yellow, green for the progress complete is kinda odd to me, given it's not like a health thing, and at high levels, the progress is so slow the colors lose their meaning.
3. Really feeling inconsistent with the plugin panel and the grand exchange plugin panel..
4. The labels like Actions left: are less important than the values themselves. I look at "651" more than "Actions left". The focus should be on the value, not the label. 
5. I think it is the right move to move the reset button down since it is less used and less important than the progress bars.
6. Aren't the values displayed under the skill (exp gained ..) attached to the skill? Why is there a separation line of the same color as the background there? It makes it seem cut off, rather than an attached stub.
7. Not sure what is going on with fonts in these previews, but those numbers seem fuzzy to me.

**Comment by psikoi** [comment]
@Stickaplex I too think there's nothing "too" wrong with the current one, but don't let that ever stop you from trying to improve, if you feel like your attempts were unsucessful, just don't do it :P it's just a suggestion. But I do agree that the reset button should be at the top, I forgot the trackers would stack very high, will update my mockup in a second, thank you!

@LeviSchuck First of all thank you for the compreensive feedback, I have some things to say:

# Main client frame:
1. Please keep in mind this was just a resized png, if the logo suggestion gets approved (currently an issue in the runelite.net project) I will be making a vector version of the logo, so it will look a lot sharper and defined. As for the impactjs, it does look similar, I did not know of that logo but I see the concern.
2. Okay fair point, agreed.
3. It does feel unnatural. at first I simply separated them from the others, with the intent of finding a better position later on, and that time never came as I was not sure where to place them, however I did not understand your suggestions, mind showing me a visual example?

# Grand exchange plugin:
2. Upon reviewing, I think you are right, I will try and make it make more sense.
3. Agreed, will change.
4. The current version also has the icons, but the API was down when I was putting together this issue so no images were loaded.
5. I just copied it off the current client, but good question. I have been working with the ge plugin to add some more functionality to it, so I may take a look at this.

 # Highscores:
Again, the API was down for quite a while so I couldn't get real data, my bad, will update this.
1. I thought so, makes more sense from a usability stand point
4. Yea I couldn't really figure out why they were using a blue star.

 # Config side panel:
1. I had a few runescape fonts already installed and confused them, I fixed it for some mockups but some have slipped with the old one, will fix.
2. I also like the icons by themselves, however they were some concerns on discord about it looking like a label instead of a button, so it could happen that users would think of it as a "enabled/disabled" indicator instead of a switch.
3. That was my suggestion, as you can see by my second mockup I hid the cog for some configs as they were not available, I should probably have made that more apparent, but there was some discussion on discord about it and we couldn't come to agreement on that. (however I agree with you)
4. You are right, will change.

**I did not understand what you mean't by the value.**

 # XP Tracker plugin
2. Just my thought exactly, but on my example, the colors matches the skills, not the progress itself.
3. Mind explaining further?
4. Great point, will change.
5. See @Stickaplex's comment and it might change your mind, it changed mine.
6.  I do see your point, however I think that considering it's 1px tall and when compared to the rest of the margins of the image, it's reasonable to assume it's attached, just extra information.
7. Same thing as before, will fix.

**Comment by LeviSchuck** [comment]
The label vs the value
![xp](https://user-images.githubusercontent.com/245911/38567066-dc2693f2-3caa-11e8-8670-215f9f94bcee.png)

The label is less important than the value, making the value harder to read makes it harder to use.

**Comment by psikoi** [comment]
I understood that, that was your 4th point, I had doubts on the 3rd

**Comment by YasinY** [comment]
The dark theme has too much of "OSBuddy" with itself. Imo if this is being considered, I'd vouch for actually creating your own custom themes / choosing community made themes.

**Comment by LeviSchuck** [comment]
Oh, I see.

Value in the sense of color theory. That's why I put up an image in gray-scale. 
http://learn.leighcotnoir.com/artspeak/elements-color/hue-value-saturation/

For those with diminished color reception and for view in the periphery, the value of the toggles needs more contrast.

**Comment by LeviSchuck** [comment]
![gs](https://user-images.githubusercontent.com/245911/38535384-d02a498e-3c48-11e8-9931-9f8eaad17302.png)

I suggest making the false value darker

**Comment by YasinY** [comment]
@psikoi I'd agree with the dark theme when the alignments of the icons would change for example:
![image](https://user-images.githubusercontent.com/10624021/38568157-3c50c92c-3ce8-11e8-88a3-00537134f916.png)

maybe make them horizontal instead of vertical (I'm talking about the icons on the right bar)

Because right now, it goes too much with the osbuddy theme with the current icons/order/alignment of icons

**Comment by psikoi** [comment]
Updated the first post and applied some of the feedback from this comment section.

# Main frame
- Deleted the version indicator next to the left side logo.

# Ge plugin
- Decreased the margin between the search bar and the first result item to be equal to the distance between the tab and the top bar
- Improved the font on the "whip" search term
- Moved the elements to the right, centering them in relation to the right toolbar, not the scroll bar.
- Changed the "before" picture to better represent the current client status

# Hiscores plugin
- Improved the font on the search bar
- Changed the data on both the before and after images to better present the changes
- Slightly moved the "2277" total level to the left

# Configs plugin
- Improved the font
- Removed the horizontal lines
- On the material version: made the "off" version of the switcher darker

# Experience trackers plugin
- Created a new total experience area on the top
- Moved the reset all button next to the total indicator, to prevent the user from having to scroll down when many trackers are stacked
- Changed the indicator's color to grey and the value's color to white on the expanded tracker
- Changed the before image to better represent the current client status

**Comment by YasinY** [comment]
Also, another suggestion about the high alch issue, if it's 0, instead display N/A

so it's High alch: N/A instead of High alch: 0

**Comment by WestArjan** [comment]
I would love this to be a 2nd optional theme. It looks alot cleaner!

**Comment by deathbeam** [comment]
If this will be implemented it will replace the default one.

**Comment by Floukru** [comment]
I really like this, but I don't think this is a priority? However I'd like to see it in the near future.

**Comment by deathbeam** [comment]
Well, one of the good things at being open source is that there is infinite number of people who can work on infinite number of things at once :D So, @psikoi working on this one as priority will not slow down any other progress in the client by the slightest.

**Comment by sethtroll** [comment]
Just a thought, what about trying to emulate osrs xp tracker? something like 

![this](https://user-images.githubusercontent.com/5454364/38774124-e28633d2-4025-11e8-82da-2ea7454e9249.png)

(rs one for reference)
![rs](https://user-images.githubusercontent.com/5454364/38774129-153b3192-4026-11e8-9b45-f73fc16af6ef.png)

I guess this does make it look eerily similar to konduits

**Comment by psikoi** [comment]
@sethtroll Actually I drew some last night that are very similar, except they don't have the info at the bottom.

It's a tricky game between clean ui and information display.

![](https://i.gyazo.com/2a4640a23923fb4a483a9d3fc74b3f2b.png)

**Comment by sethtroll** [comment]
Did you have a redesign for the info panel in mind?

I threw something up real quick, not sure what else to put there

![mockup](https://user-images.githubusercontent.com/5454364/38788904-5af83f82-40fc-11e8-8437-af46125d9607.png)

**Comment by psikoi** [comment]
I hadn't yet, but now I do! a couple tweaks and it'll fit in real nicely, give me a few minutes.

**Comment by psikoi** [comment]
@sethtroll what do you think of this?

![](https://i.gyazo.com/c8d1537922d2bcba7089a3663c1efcb6.png)

**Comment by sethtroll** [comment]
Yeah looks good, could probably throw in current online players somewhere and also add a twitter link

**Comment by psikoi** [comment]
The dream lives on, this suggestion has been developed and is awaiting approval and merging, planned to be merged on the 17th of May. 🎉 🎉
