### ISSUE TITLE
Invalid Credentials

### ISSUE THREAD

**Issue by cwsaunders** [runelite/runelite#13493]
**Describe the bug**
I keep getting 'invalid credentials' when I try to log in. Despite being able to log into the official OSRS website, OSRS launcher, and play on Steam.

**To Reproduce**
1. Download RL v. 1.7.5
2. Enter email, password, and use authenticator app (Authy)
3. Enter

**Expected behavior**
Logging in

**Environment (please complete the following information):**
 - Windows 10
 - RuneLite version: 1.7.5
 - Launcher version: 2.1.16

**Additional context**
Just downloaded it today.

**Comment by Hydrox6** [comment]
RuneLite does not change the login flow in any way. It used to be that key handlers ran on the login screen, causing a semi common issue of players taking screenshots while typing in their password, though this has since been fixed. As far as I know, this same functionality also applies to hub plugins, so unless you're consistently typing your password wrong (I know them feels), something else could be intercepting input (eg. AutoHotKey or other key-rebinding software).

Try typing in your password slowly, and watch if a character doesn't cause a new `*` to appear. Then have a look for anything that might be rebinding your key in specific situations (ie. when a specific window is focused)

For further questions of support, please join the [Discord](https://runelite.net/discord)
