### ISSUE TITLE
Idle Notifier Support for Creating Jugs of Water

### ISSUE THREAD

**Issue by NixyOSRS** [runelite/runelite#13504]
When turning a Jug into a Jug of Water with a sink or fountain, the Idle Notifier does not trigger upon completion of an inventory. I believe this should happen under the Idle Animation Notifications, as there is a 'reach emote' to the water spot you're utilising.

While I totally appreciate this is fairly niche to ironmen and not at all a priority, it would be handy to have as part of the plugin.

**Comment by FlashBasedGod** [comment]
You have my sympathy here because I had to fill up 2,000 jugs on my ironman. Looking into it, however, it seems the animation for filling up buckets/jugs is a fairly general animation, and including it could cause some annoying issues with the idle notification triggering at unintended times. Regardless we can at least try and add it.

**Comment by Nightfirecat** [comment]
In what situations would it be annoying to add notification triggers to that animation? For people who may be incidentally encountering that animation during active play, it wouldn't trigger anyway due to their activity.

**Comment by arnaudperalta** [comment]
This enhancement would require to edit the test `checkAnimationReset()` in IdleNotifierPluginTest.java. I'm a beginner in this project and I wonder why this test exists in a first time ? How can an animation can be resets and why the player should use the LOOKING_INTO animation to reset it the first one ?

**Comment by Nightfirecat** [comment]
That test exists to ensure that changing from some animation which would trigger a notification if idling afterward would not trigger if some other (non-triggering) animation occurred between them. I don't know why `LOOKING_INTO` was chosen instead of some dummy value, so I agree the test should be changed to accommodate this enhancement.

**Comment by Nightfirecat** [comment]
Added in d58cecdb8d5a2d6958a5bcf1381805c6d64be7b8
