### ISSUE TITLE
Add drop all option to specific items?

### ISSUE THREAD

**Issue by AussieYetti** [runelite/runelite#13866]
Just wondering if it would be possible to add a drop all feature?

It would work like the highlight npc  feature where you have to type in specific items that you want to shift click (or another key) to drop all.
It would make things like barbarian fishing, wood cutting and mining a bit nicer to empty inventory rather than spam clicking shift click to drop everything.

**Comment by Cyborger1** [comment]
Sorry, this is not something the RuneLite developers can add. Such a feature would be effectively macroing, which is against Jagex's Terms of Service.

If such a feature were ever to be added, it would have to be implemented by Jagex themselves in the base client, which would require a player poll. It would be essentially guaranteed that this poll would not pass, as the entire game is balanced around the current item dropping mechanics and the players are very protective of the current game balance.

In particular, those exact training methods you're mentioning would see a significant increase in XP per Hour, which is why something like this is unlikely to ever be added in the game by Jagex.
