### ISSUE TITLE
Almost switched to this client

### ISSUE THREAD

**Issue by EatMyWeani** [runelite/runelite#1396]
The initial downfalls I saw with Runelite were no xp drops, no 3rd party source on the GE values of items (GE tends to not be as accurate or quick to update as 3rd party), and no indication of when I should drink prayer potions. I may have missed where these things were on my screen or messed up the settings, though I did run through all the settings and I thought I set them accordingly. If these things were added, I would switch to Runelite and recommend it to everyone.

**Comment by SomeoneWithAnInternetConnection** [comment]
If, by 3rd party, you mean "OSB", then yeah. That's a little bit sticky to do, since they don't actually have any documentation, and we'd rather not depend on a proprietary, undocumented, API. There's been *some* work done on that front though (#1277) but it's not really in a merge-able state right now.

We use the client's built-in XP drops. Turn them on. If you don't like the built-in XP tracker, you can disable that by right clicking on the (built in) "XP" orb, and picking "setup).

I don't believe we've got a "Yo, drink your potion now!" indicator, but if you've got the item stats plugin turned on then the text in the tooltip will be green if you aren't going to be wasting any of the potion, yellow if you're going to be wasting some of it, and red if you're going to be wasting all of it. #598 is the issue that's currently open for that.

**Comment by MagicfTail** [comment]
There is a notification for when your prayer gets low tho

**Comment by ShaunDreclin** [comment]
Also just fyi: this isn't a discussion forum, it's for posting bug reports or specific feature requests :p

**Comment by Stickaplex** [comment]
do we have a discussion forum though? besides disc

**Comment by SoyChai** [comment]
Discord is the place to go for discussion as far as I know.

But yeah, this is an issue tracker, meaning every thread here is meant to be a specific feature request that can be "closed" if it's added later on.

**Comment by deathbeam** [comment]
This issue is in completely invalid format, reopen new one as separate feature requests, closing.
