### ISSUE TITLE
GPU Plugin uncapped framerate capped at 60 on 165HZ monitor

### ISSUE THREAD

**Issue by stevenwaterman** [runelite/runelite#14320]
**Describe the bug**
When enabling the 'Unlock FPS' option on the GPU plugin, the game is capped at 60fps on my 165Hz monitor. The monitor is definitely running at 165Hz and other games can run at that framerate without issue. There is no way to override the auto-detected vsync framerate. Please note that I'm running Linux (see env section), this may be platform specific.

**To Reproduce**
1. Use a HFR monitor and open RuneLite on that monitor
1. Enable GPU plugin with very low draw distance and AA disabled to ensure you're not GPU-limited
2. Enable 'Unlock FPS' in GPU plugin
3. Enable FPS Control plugin, disable all limiters and enable the FPS indicator
4. FPS indicator displays constant 60FPS

**Expected behavior**
FPS should increase above 60, up to the native monitor framerate

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04
 - RuneLite version: 1.8.0
 - Launcher version: 2.1.5
 - 4 monitors, one is 165Hz, that's the one it's open on. See the attached `xorg.conf` for monitor config (renamed to .txt so github would let me upload it) [xorg.txt](https://github.com/runelite/runelite/files/7441464/xorg.txt)
 - Using the appImage version

**Additional context**
Add any other context about the problem here, e.g. logs. Your client logs can usually be found in
`C:\Users\<your_user_name>\.runelite\logs` on Windows and `~/.runelite/logs` on Linux and macOS.

There's nothing in the logs other than the GPU plugin being enabled / disabled when I switch to/from HD.

Happy to run any additional diagnostics you would benefit from, just let me know

**Comment by g-i-g** [comment]
so I spent an embarrassingly long time looking into this, and I don't think it's a runelite issue. I see from your xorg.txt that you're using nvidia, and I am as well, so I'm thinking this is an nvidia-specific issue.

in `nvidia-settings`, go to X Screen 0 -> X Server XVideo Settings, and see which display is set to sync. in my case, it was my 60hz monitor instead of my 144hz one. I tried to change it there to the correct monitor, but for some reason, the setting doesn't propagate to other applications, even after an X restart.

fortunately, there's an environment variable you can set: `__GL_SYNC_DISPLAY_DEVICE`. assuming DP-3 is your high-hz monitor (check xrandr), you can do something like this:

```
__GL_SYNC_DISPLAY_DEVICE=DP-3 ./RuneLite.AppImage
```

and then you should be able to enjoy your uncapped fps.

**Comment by stevenwaterman** [comment]
Adding the environment variable worked for me. It'd be ideal if there was just a way to disable vsync, but this is definitely a me-specific issue rather than a RL issue

**Comment by Nightfirecat** [comment]
Given this is not our bug and there's not really anything we can do to help it, I am closing this issue.
