### ISSUE TITLE
Emojis

### ISSUE THREAD

**Issue by sadegr** [runelite/runelite#1464]
![konduit emojis](https://user-images.githubusercontent.com/20391979/38709437-06a1d710-3e89-11e8-9fbe-aa40fd174803.png)
This request is for an optional (togglable) plugin that allows players to see emojis sent by other players in OSRS chat. Konduit (another 3rd party OSRS client) already provides this feature (the screenshot shown above is from Konduit).

Players would be able to type Emoji shortcodes (as used on GitHub, Discord, etc. - see [here](https://gist.github.com/oliveratgithub/0bf11a9aff0d6da7b46f1490f86a71eb)) in public, private, and clan chat to cause the corresponding emoji to show up in the in-game chatbox for players with the emoji plugin enabled. The normal text would show up unmodified to players with the emoji plugin disabled. Emoji shortcodes could be typed by themselves or as part of a larger text string to cause emojis to show up, and multiple emojis could be used per line of text.

Example: typing `:ok_hand:` in public chat would cause the 👌 emoji to show instead of the `:ok_hand:` text to players with the emoji plugin enabled. To players with the emoji plugin disabled, the text itself (i.e. `:ok_hand:`) would show up as originally typed.

**Comment by sethtroll** [comment]
If someone wanted to make the plugin and it was toggled off by default I would be okay with that. OSBuddy and Konduit both have this (I think) and we've always tried to keep the competition even in terms of plugins.

**Comment by sanderdegroot** [comment]
I've attached a screenshot of a few Konduit emojis (it wouldn't have to be the same set of icons) along with the text that was typed underneath for reference.

**Comment by GETrackerDan** [comment]
I've given it a thumbs up although I'm not a big fan of this in game and it just reminds me of private servers and a bit trashy if I'm honest. If somebody who has it toggled off doesn't see the emoji or :ok_hand: code/text and as @sethtroll has said toggled off as default I don't see an issue with it being built and added into the client. I'm sure there will be many people who would like this.

**Comment by MESLewis** [comment]
How would the images be stored in the client? ATM we use mostly cache images, I am not sure if there is precedent set for where other images go.

**Comment by sanderdegroot** [comment]
@MESLewis I would imagine a new folder in runelite-client/src/main/resources/ would be a pretty good place for them.

**Comment by deathbeam** [comment]
Even disabling the emojis by default still do not prevents other people from typing them out to chat, and you would still see the text even without emojis. Emojis just promote dumb chat, I don't think we should implement that. If you wan't to use emojis, just hop on some Discord server or Twitch chat, there is no place for them in game itself.

**Comment by sethtroll** [comment]
To play devils advocate: the other clients mentioned already offer this so you would still see those people typing them in chat? In my opinion, I would never use this but if it's something someone wanted to make it and use, I wouldn't care.

**Comment by devLotto** [comment]
Whoever implements this: Please use Twitter emojis and make them anti-aliased. Konduit's ones look horrible

**Comment by SoyChai** [comment]
I actually think anti-aliased ones would look rather bad, as you can see by the 😂 emoji on the far right. Every other icon used in the OSRS chatbox uses a quaint pixel style that we should be interested in preserving.

Ofc the downside of that would be an enormous amount of pixel art editing.

**Comment by deathbeam** [comment]
What about just replacing the common emojis with images then? I believe that should please everyone, no weird `:joy: :blahblahblah:` stuff in chat, simple `:D, :(` and stuff like that. And I agree that using anti-aliased emojis would feel off. Also, probably making them smaller than Konduit's, because having them height of the entire line looks horrible.

**Comment by MagicfTail** [comment]
That is the opposite of what I would prefer, I like my random 🔥 and 👌 s, but usually just use the normal smileys, and would like for them no to change

**Comment by ShaunDreclin** [comment]
I don't think that's a good solution, we should follow what other clients are doing.

We don't want a situation where every different client is using different systems for emoticons

**Comment by ShaunDreclin** [comment]
https://www.webpagefx.com/tools/emoji-cheat-sheet/

Yeah emoticons are different, emojis on most modern platforms use this^ system,

**Comment by jerwuqu** [comment]
For people without a emoji-supported 3rd-party client, seeing a bunch of emoji codes in chat will undoubtedly be very annoying. This is why having just a few emojis for regular emoticons is better: seeing a `:)` in chat is a lot nicer on the eyes than `:simple_smile:`. If those common ones are not enough, then what is the reason for having all the other ones? Just memes?

**Comment by MESLewis** [comment]
When it comes down to things that specific it'll be up to whoever wants to write the code for it. There's a lot of hypothetical discussion in here so far and not much code. I think things as specific as what strings to replace with what icons can wait for an implementation to surface.

**Comment by TheeWiki** [comment]
Twitch emojis would be a nice thing to consider when doing this up. and maybe a few Discord ones that are actually good enough to display/use.

**Comment by deathbeam** [comment]
I don't think that is good approach, it's better to discuss this first than to have exactly same conversation after someone will actually spend their time to write it. There is nothing someone implementing the plugin can do to prevent the points that I and @jerwuqu presented, so implementation does not really matter at this point, so it will be too late to discuss it when the implementation will be done. The solution with using emoticons is perfect compromise imo. 

We can't use twitch emojis outside of twitch I believe, and probably same thing applies to Discord ones.

**Comment by jerwuqu** [comment]
The height of a chat message is about 16px (and you probably don't want to use all of that). I don't think a Twitch emoji could fit in there and still look remotely decent.

**Comment by SoyChai** [comment]
I do feel like as a client which may be extremely popular in the future, we have a responsibility to get this right in a way that won't irritate vanilla players for years to come.

I'd definitely prefer an approach which doesn't use :colon_codes: because these only work well on services like discord, where *everyone* is guaranteed to see the transformed emoji.

**Comment by Gamer1120** [comment]
I would also like to propose to add Twitch emotes like Kappa

**Comment by sanderdegroot** [comment]
The issue with *not* using `:colon_codes:` is that there are far too many emojis out there to represent using any other system. Sure, you can get away with standard smileys like `:)` for a few of them, but how do you represent emojis such as 💯, 💩, 👌, etc. using a convention that users who do not have an emoji client plugin will be able to understand?

Furthermore, I think we would do well to support all or the majority of the standard emojis used on Discord/GitHub/most modern smartphone keyboards, not just the basic smiley/frownie faces. These basic emojis can already be expressed fairly well using text (e.g. `:)`), so being able to show an image instead of these wouldn't add much value. On the other hand many emojis that *cannot* easily be represented using text express far more complex ideas, so being able to show the corresponding emoji instead of their `:colon_code:` would add a comparatively large amount of value. I don't think anybody that wants an emoji plugin wants it for the standard smileys which can already be represented easily using text (`:)`).

As such I say we either a) support all/the majority of emojis or b) don't add an emoji plugin at all. If someone does decide to work on this, I would place my support behind using a `:colon_code:` system for three reasons:
1. Compatibility with Konduit's emoji plugin, so that RuneLite users are able to see emojis typed by Konduit users and vice versa
2. Standardization - many existing services (Discord, GitHub, etc.) use `:colon_code:`s and there seems to be an agreed upon standard and several publicly available lists showing emojis and their corresponding `:colon_code:`, Unicode code point, etc.
3. There is a very large number of emojis, far too many to devise a system of our own that users will be able to remember.

**Comment by deathbeam** [comment]
You just described the problem. With adding support for emojis the colon_code needs to be represented with the image otherwise it is hard to understand. So it will be problem for any non-konduit and non-runelite user or simply for user with the plugin disabled.

That is why emoticons are better choice, because they can be easily expressed with both text and image, without the need to use 3rd party client.

**Comment by ShaunDreclin** [comment]
I don't think it's that hard to understand even if the image doesn't render, most people know the emoji codes haha

**Comment by SoyChai** [comment]
I don't think running out of codes is a problem if we agree that we simply don't need the entire set of 2,600+ emojis in RuneLite, but could instead make do with a much more focused set of emojis that *is* representable using more stealthy text representations.

**Comment by sanderdegroot** [comment]
I still stand behind using `:colon_code:` syntax, but for those of you who oppose this idea - could you give me some examples of how you'd like to see emojis encoded? Again, *in my opinion* 90% of the case for adding emojis to RuneLite as a plugin is being able to show non-standard emojis that cannot be represented using standard text. We can already represent the more common ones as `:)` etc. How would you suggest representing emojis such as 💯, 💩, 👌 if not the standard `:colon_code:` notation?

**Comment by deathbeam** [comment]
Well, I personally do not want to represent or promote usage of such emotes at all as I stated earlier. It is unfriendly to other players that do not like emojis, and I guarantee you that there are plenty.

**Comment by ShaunDreclin** [comment]
I mean if they bother people that much it's easy enough to ignore anyone who uses them.

**Comment by jerwuqu** [comment]
I don't see why "emojis such as 💯, 💩, 👌" are needed, they both require the use of codes that won't make much sense to users that aren't avid memesters and they don't contribute much to a conversation. I could see the use for custom emojis for things such as the skills and prayers in the game, but even those are hard to justify when they would require codes in chat.

**Comment by ShaunDreclin** [comment]
People use emojis to communicate. When they're already supported in so many places that you use every day, it's off-putting to not be able to use them somewhere.

I really don't think the argument of the codes annoying people who don't use emoji-enabled clients holds much water, when Konduit already rolled out support for it. I rarely if ever saw anybody complaining about Konduit players using the codes

**Comment by deathbeam** [comment]
People use emojis to communicate on platforms that are designed to communicate with emojis. In-game chat is not.

**Comment by jerwuqu** [comment]
It is a reason because we aren't responsible for all, or even the majority, of chat communication in the game.

**Comment by SoyChai** [comment]
I really want to see people *consider* the chat experience of vanilla users when making points in favour of this, because so far I'm seeing very little compassion towards them. 🙁 Those people don't have an option to toggle plugins and modify features like we do.

**Comment by SoyChai** [comment]
I presume you mean chat commands like `!Price` and `!Lvl`? Honestly I'd like to see us add those to the silent `::` commands if possible, since that's possible now thanks to #1819.

**Comment by jerwuqu** [comment]
Yes, care to elaborate? @ShaunDreclin

**Comment by ShaunDreclin** [comment]
Well you'd have to send something for !lvl since other clients need to see the command, but yea the price command could be changed to silent

**Comment by sanderdegroot** [comment]
I can certainly sympathize with the argument that the vanilla chat experience should remain unaffected as little as possible. As such I think an option to not show the emoji text to users who don't have emojis enabled should be included.

So we would have one toggle to enable/disable the emoji plugin as a whole; if disabled, there would be an option to show or hide the emoji text (e.g. `:joy:`). If the "hide emoji text" setting is enabled, we would just remove any emojis from chat messages before displaying them to users (this could have performance implications which we can look into later should this turn out to be an acceptable compromise). Potentially a second option to show letter emojis like 🅱️ as their regular letter counterpart (`b`) if the first option is disabled; this would cause words like 🅱️oneless to show up as `boneless` rather than `oneless`.

Thoughts? I understand adding emojis is a touchy subject since use of emojis is often associated with an immature/uneducated demographics, but based on how many Konduit users I've seen using it, I think there is a demand for this feature.

**Comment by SoyChai** [comment]
The comment above *is* a good idea for RuneLite users... the problem is realising that vanilla players (ones who use the official Jagex client) won't have an opt-out from any text codes that we introduce into the chatbox, and we shouldn't forget about them, even if we believe RuneLite is a superior client.

It's true that the purity of public chat is slightly muddied due to standard OSB commands, and we're already contributing to that ourselves. That doesn't mean chat is completely ruined and can't get any worse though; we still need to be reasonable if we really love this game and its userbase.

**Comment by ShaunDreclin** [comment]
In a perfect world there would be something that lets third party clients communicate with each other without needing to use chat haha then we could do all sorts of stuff including emoji that doesn't disrupt vanilla users

**Comment by jerwuqu** [comment]
I think you just described a regular chat client.

**Comment by SoyChai** [comment]
Cross-client communication would be amazing for stuff like this, though it'd probably take something bigger than emojis for it to be worth building an entire web framework for it. Maybe in the future?

**Comment by Nightfirecat** [comment]
As of now, Konduit (the only major third-party client to implement emojis) is now defunct. While I'd personally still like to see them implemented, that fact does mean that we'd be the lone client with it implemented, which is not ideal.

**Comment by ShaunDreclin** [comment]
rip the dream 😢 

if we did do this we'd definitely want to get osb to do it too, when it was first proposed konduit still had a pretty large userbase

**Comment by deathbeam** [comment]
Let's wait for jagex to implement this :p

**Comment by LeoFurnari** [comment]
@Nightfirecat 
>which is not ideal.
I mean it is the sum of people contributing to it, so it just makes it unique.

**Comment by devLotto** [comment]
I think I agree with @deathbeam, emoticons should get us pretty far while avoiding the ``:joy:``-style text that some players don't like.

I don't think we need all 2800 emojis, these and maybe a few more should be enough to express a wide range of feelings:

🙂  :)
😂 :'‑)
😊 :3
😀 ^o^
😅 ^\_^
😄 =D
😉 ;‑)
😝 :‑P
😛 :P
🤔 :‑/
😕 :/
😐 :‑| 
😑 :|
🙁 :(
☹️ :‑(
😢  :'(
😭 :'‑(
🤐 :‑X
😣 >_<
😎 8-)
😇 o:‑)
😈 >:‑)
😡 >:(
😯 :‑o
😮 :o
😱 D=
👌  Ok
👍 +1
👎 -1
❤ <3
💔 </3
💤 zzz

**Comment by Adam-** [comment]
Added in #8811
