### ISSUE TITLE
Runelite Loot Tracker partially reset

### ISSUE THREAD

**Issue by mumbomination** [runelite/runelite#14747]
My runelite loot tracker was partially reset after a few weeks of not using it. I was logged in runelite the whole time, and when I began PVMing again, at first, it was fully reset. I pressed the "import loot tracker" button, and though some of my loot has been saved between sessions (K'ril, Theatre of Blood), some are gone completely, like Vorkath and Kraken even when I closed and opened runelite again. It seems to align with what the website says as well, since the website also has my loot partially wiped.

I have gone without PVMing for longer than this, but I never had any problems. Could it be because my loot tracker has too many entries? (25,000 Moss Giants are in the tracker)

**Comment by Adam-** [comment]
The import only imports loot which would have been visible on the client, and not all loot (the subset of loot visible on the site but not in the client). 

If you have certain events like tob which you want to have imported you could bump them to the top of the list by getting another loot drop, reset-all the loottracker, and then restarting the client and re-importing. But it would push down something else off of the list probably which wouldn't be imported.

This only works currently because I am running both loot tracking systems simultaneously so loot is being submitted and tracked in both.

**Comment by mumbomination** [comment]
> 
I really hope my loot is not lost forever since it was able to be imported in the first place.

Can I really reset-all then get all my loot info back by importing? since the warning does say "my loot will permanently be deleted".

 If so, then I guess my course if action is to get 1 kill for everything I want tracked after resetting (ToB, kraken, zammy, arma, bandos, grotesque guardians,) then import again?

**Comment by Adam-** [comment]
Reset-all won't remove it from the old storage system so it allows you to reset/re-import it again if you want.

**Comment by mumbomination** [comment]
> Reset-all won't remove it from the old storage system so it allows you to reset/re-import it again if you want.

So I guess I could try. Would it help if I gave you my runelite client file/profile to see what happened here? Since I saw you suggest that over discord to some other people having the issue, but they had it solved by restarting.

**Comment by Adam-** [comment]
No, I think that was for something unrelated to this.

**Comment by mumbomination** [comment]
> No, I think that was for something unrelated to this.

Alright, I tested the reset-all suggestion and it worked. Looks like I'll have to get every boss I care about on my log as quickly as possible before importing again, thanks for the help.
