### ISSUE TITLE
ChatFilter G.E. only

### ISSUE THREAD

**Issue by TheHillsa** [runelite/runelite#14816]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always
frustrated when [...]

Chat filter is primarily used to prevent spam in the G.E. Because it sometimes catches messages that are not spam, particularly outside the G.E., an option that only enables it in the G.E. would solve this in most cases.

**Describe the solution you'd like**

An option that automatically activates chat filter in spam hot spots, primarily the G.E.

**Comment by Hydrox6** [comment]
Given that what `Chat Filter` filters is entirely controlled by the user, if it's filtering content elsewhere the user should change their filter to be more specific.

**Comment by TheHillsa** [comment]
> Given that what `Chat Filter` filters is entirely controlled by the user, if it's filtering content elsewhere the user should change their filter to be more specific.

This is not a useless suggestion. Here is an example: "Duranke Has wön 22m Röll: (58) @ [04:29:08]"

If I filter "has won" or "has lost" or "roll" this ends up filtering too many non spam messages. However, if this feature could be enabled for the G.E. only, this would be solved.

**Comment by Hydrox6** [comment]
That's why regex filtering exists, so you can be more specific. with filters that follow a pattern instead of exact text

**Comment by TheHillsa** [comment]
> That's why regex filtering exists, so you can be more specific with filters that follow a pattern instead of exact text

There is no guide as to how to use it. While filtering words/sentences is straight forward. 

The majority of people who use Runelite like myself are not software engineers.

**Comment by Hydrox6** [comment]
There are many guides and tools for making regex online. Yes it's advanced, but it's not something impossible for people to learn/use. It also remains the easiest way to support something like this for near *every* situation.

Because the main thing with adding a toggle for a specific area is that the GE isn't the only place with spam. There's also Wintertodt, Lumbridge castle for F2P, certain PvP banking hotspots, ToB, CoX, and probably many more. When we already have a tool that does what you asked for (filtering spam without hitting real messages), it doesn't make much sense to add a much narrower tool that would also stop the plugin from working in the vast majority of the world, something that would definitely confuse users.

**Comment by TheHillsa** [comment]
> There are many guides and tools for making regex online. Yes it's advanced, but it's not something impossible for people to learn/use. It also remains the easiest way to support something like this for near _every_ situation.
> 
> Because the main thing with adding a toggle for a specific area is that the GE isn't the only place with spam. There's also Wintertodt, Lumbridge castle for F2P, certain PvP banking hotspots, ToB, CoX, and probably many more. When we already have a tool that does what you asked for (filtering spam without hitting real messages), it doesn't make much sense to add a much narrower tool that would also stop the plugin from working in the vast majority of the world, something that would definitely confuse users.

Alright. 

Doing it the straight forward way still blocks around 95% of the spam which enables me to read public chat.
