### ISSUE TITLE
Timestamp format changes after closing and reopening client

### ISSUE THREAD

**Issue by Nell13** [runelite/runelite#15447]
### Type

Incorrect behavior

### Operating System

Windows

### OS Version

Windows 10 Pro

### Bug description

I am logged into my RuneLite account. When I change the timestamp format to `[mm]`, the timestamps correctly use this format until I close and reopen the client. When I reopen the client, the timestamp format is automatically changed to `["mm"]` which is also reflected in game.

1. I right-clicked the format and set it back to default, then closed and reopened the client. settings.properties has `timestamp.format=[HH\:mm]`
2. I set the format to `[mm]` through the runelite interface and then closed the client. settings.properties now has `timestamp.format=[mm]`
3. I launch the client again and see that the timestamp format has changed. settings.properties now has `timestamp.format=["mm"]`

### Screenshots or videos

https://www.youtube.com/watch?v=bsL1yprI1gY

### RuneLite version

RuneLite version: 1.8.30
Launcher version: 2.4.2

**Comment by Adam-** [comment]
This was caused by how the config service tries to config values as json, as it interpreted it as json `["mm"]` due to the lax parsing rules gson has. This has caused other problems for us in the past, so I've changed it to just treat everything as a string, similar to how the properties work on disk https://github.com/runelite/api.runelite.net/commit/02a51e2aedde5ead05c314565a5973a5cb60851a
