### ISSUE TITLE
Implings plugin: "Show Spawn locations" option does not do anything in puro-puro

### ISSUE THREAD

**Issue by ashelleyPurdue** [runelite/runelite#15492]
### Type

Incorrect behavior

### Operating System

Windows

### OS Version

Windows 10

### Bug description

I've enabled impling spawn locations, but no spawns are showing.  A similar issue was opened and closed [four years ago](https://github.com/runelite/runelite/issues/2087).  Seems like it's come back.

### Screenshots or videos

![image](https://user-images.githubusercontent.com/8558767/184511043-dd470633-c544-47a5-982b-a921307516fe.png)

### RuneLite version

RuneLite version: 1.8.30
Launcher version: 2.1.7

**Comment by Hydrox6** [comment]
The spawn locations are only shown for impling types you have highlighted, to reduce visual clutter. Additionally, in Puro Puro only lower level implings have static spawn locations; higher tier implings use dynamic spawn points which we don't show.

As a result, you can't see spawn points because you have none of the implings highlighted that actually have spawnpoints.
