### ISSUE TITLE
Bank Tag vs OSRS "Always set placeholders"

### ISSUE THREAD

**Issue by Senidian** [runelite/runelite#15542]
### Type

Incorrect behavior

### Operating System

Windows

### OS Version

Windows 11

### Bug description

When using the bank tag tab, removing specifically the Games necklace(5) from the tab removes it entirely, rather than showing there are 0 stacks of the item. It seems to leave a 0 stack for every other kind of jewelry or item in general. 

### Screenshots or videos

With Gamenecklace(5) in bank tag tab: 
![2022-08-22_14-46-38](https://user-images.githubusercontent.com/111791013/185996148-b9bb698d-94b7-4ba5-bc2a-805bef24777c.png)

Without:
![2022-08-22_14-43-02](https://user-images.githubusercontent.com/111791013/185996242-9f9d4313-c5b5-416c-a590-069cc28c30d0.png)
 

### Logs

[client.log](https://github.com/runelite/runelite/files/9396832/client.log)
[launcher.log](https://github.com/runelite/runelite/files/9396833/launcher.log)

**Comment by Enriath** [comment]
This is because the placeholder is shared between multiple items, and you haven't added it to the bank tag. Shift drag the item to the bank tag tab to "variation" tag it, which will put all variations of an item into the tab. The same thing works for stuff like Barrows armour and the Dragonfire shields.

For further questions of support, please join the [Discord](https://runelite.net/discord)
