### ISSUE TITLE
Runelite crashes when entering Kephri's puzzle room in TOA

### ISSUE THREAD

**Issue by RLChristof** [runelite/runelite#15568]
### Type

Crash or hang

### Operating System

Windows

### OS Version

Windows 10, build 19044.1826

### Bug description

Runelite hangs/crashes when entering Kephri's puzzle room in TOA. 

No TOA plugins are installed, quest helper and all associated fight cave plugins have either been disabled/uninstalled

Path taken in TOA
Ba Ba > Croc > Ahhka > Kephri
Also have attempted
Ba Ba > Kephri <client hangs>
Kephri <client hangs>

Every time I get to Kephri, and enter the puzzle room, the client hangs, and I have to go into task manager to kill the process/task

### RuneLite version

Runelite: 1.8.32.1
Launcher 2.4.5

### Logs

[client.log](https://github.com/runelite/runelite/files/9438938/client.log)
[launcher.log](https://github.com/runelite/runelite/files/9438939/launcher.log)

**Comment by Nightfirecat** [comment]
Since this issue was opened, we've made a number of changes which should reduce the amount of memory the client in general uses, which should address this issue. Let us know if it is still a problem for you.

For some more information, you can read the blog post we published on it here: https://runelite.net/blog/show/2022-09-04-recent-performance-regressions-and-tombs-of-amascut
