### ISSUE TITLE
Client Crashes at TOA

### ISSUE THREAD

**Issue by Deacon207** [runelite/runelite#15577]
### Type

Crash or hang

### Operating System

Windows

### OS Version

Windows 11

### Bug description

It only happens while I'm at TOA, the screen will freeze on the frame it is on, then if I minimize and bring it back up, it is just a blank screen. It has happened 6+ times in the last 24 hours. 

### RuneLite version

Runelite version: 1.8.32.1
Launcher version: 2.4.5

### Logs

[client_2022-08-27.0.log](https://github.com/runelite/runelite/files/9440325/client_2022-08-27.0.log)
[launcher_2022-08-27.0.log](https://github.com/runelite/runelite/files/9440326/launcher_2022-08-27.0.log)

**Comment by Nightfirecat** [comment]
Since this issue was opened, we've made a number of changes which should reduce the amount of memory the client in general uses, which should address this issue. Let us know if it is still a problem for you.

For some more information, you can read the blog post we published on it here: https://runelite.net/blog/show/2022-09-04-recent-performance-regressions-and-tombs-of-amascut
