### ISSUE TITLE
GE Price Average

### ISSUE THREAD

**Issue by DarcMag1k** [runelite/runelite#15935]
### Type

Incorrect behavior

### Operating System

Windows

### OS Version

Windows 10

### Bug description

When viewing the grand exchange prices, sometimes the GE Price Average is wrong ( different than the pricing in the actual GE ) then after a while it corrects its value. And because of this change in GE price, it's affecting the high alchemy profit calculator.

### Screenshots or videos

![Screenshot 2022-11-20 115915](https://user-images.githubusercontent.com/118663193/202898542-855f9759-958a-4ac8-96f0-1a4e26876743.png)
![Screenshot 2022-11-20 115937](https://user-images.githubusercontent.com/118663193/202898544-9c8e2820-8fba-40ff-ba81-48cb9567fb38.png)

### RuneLite version

RuneLite Version: 1.9.3
Launcher version: 2.5.0

**Comment by Enriath** [comment]
The prices the client uses by default is provided by the wiki, which uses data that we provide (that they then process to try and keep consistency) https://prices.runescape.wiki/osrs/

This data is available to all client plugins, and is used in multiple core plugins. For the most part this data is much more accurate than the vanilla prices, as they don't change to reflect buying/selling as often.
If a hub plugin is inaccurate because it isn't using said data, that's on the hub plugin to fix.

Issues and suggestions for hub plugins must be made on that plugin's repository; they are not maintained by us. The repo is usually accessible from the Support link on the plugin.

**Comment by DarcMag1k** [comment]
Ok I understand but the plugin in question here is the Core ITEM PRICES plugin. I haven’t downloaded any other prices plugins whatsoever. The GE PRIVE AVG on this plugin differs a lot from the prices given when you open other OSRS launchers such as the Steam one. Please is there a way to revert back to these prices instead of the plugin’s. Because when I turn the plugin off the examine button doesn’t show the prices at all.

**Comment by Enriath** [comment]
As I've already mentioned, by default RuneLite will use pricing data that is much more accurate than vanilla data you would find on the Steam or Mobile clients, or the OSRS website. The Item Prices plugin, being a core plugin, also uses this data; it's not "affecting the high alchemy profit calculator" as you initially suggested.

If you want to use the less accurate vanilla data for whatever reason, the option to disable it is under `RuneLite` -> `Use actively traded price`, though I'll say again that this data is for the most part **less accurate** than if you leave the option enabled. Instead of using the OSRS website for price information, it would be better to use the wiki's site linked in my last comment.

**Comment by DarcMag1k** [comment]
Ohhh okkk I see now your point. Thank you so much for clearing things up and for the advise. I’ll keep using the plugins data for sure if that’s the case.

Best Regards,
Mohamad Fakih

On Nov 20, 2022, at 1:42 PM, Enriath ***@***.***> wrote:

﻿

As I've already mentioned, by default RuneLite will use pricing data that is much more accurate than vanilla data you would find on the Steam or Mobile clients, or the OSRS website. The Item Prices plugin, being a core plugin, also uses this data; it's not "affecting the high alchemy profit calculator" as you initially suggested.

If you want to use the less accurate vanilla data for whatever reason, the option to disable it is under RuneLite -> Use actively traded price, though I'll say again that this data is for the most part less accurate than if you leave the option enabled. Instead of using the OSRS website for price information, it would be better to use the wiki's site linked in my last comment.
