### ISSUE TITLE
Bug: World Hopper: High-Risk world showing when "Normal" world type filter selected.

### ISSUE THREAD

**Issue by Nick2bad4u** [runelite/runelite#16301]
### Type

Incorrect behavior

### Operating System

None

### OS Version

Win 11

### Bug description

Noticed the bug when I changed my world hopper to show only "normal" worlds

### Screenshots or videos

Settings
![Settings](https://user-images.githubusercontent.com/20943337/220181673-7972b997-9dd7-4627-8448-d193fc057cd8.png)
High Risk Showing:
![HighRiskSowing](https://user-images.githubusercontent.com/20943337/220181721-480fd715-56d3-4faf-8805-bc2f509f9722.png)

### RuneLite version

Runelite Version: 1.9.11.1
Old School Version: Rev 211
Launcher Version: 2.4.5

**Comment by Alexsuperfly** [comment]
it is a normal world, only has the extra item prayer disabled

**Comment by Nick2bad4u** [comment]
> it is a normal world, only has the extra item prayer disabled

Its not a PvP world?

**Comment by Nightfirecat** [comment]
No. See also: https://oldschool.runescape.wiki/w/Server#High-risk_worlds

**Comment by Nick2bad4u** [comment]
> No. See also: https://oldschool.runescape.wiki/w/Server#High-risk_worlds

I see.. Would we consider that to be a normal world though?

**Comment by joe-wee** [comment]
This is still an issue- there's a separate filter for "High risk" under the "world type" filter and selecting "normal" does not remove high risk worlds from the list. Selecting "high risk" does correctly show ONLY the high risk worlds, but selecting normal shows high risk.

This is an issue because there's a chat confirmation before world hopping if you try to hop into a high risk world, even though they aren't inherently PVP worlds. IMO "normal" should show only normal worlds where there's no caveats or warnings when you hop to them.

**Comment by Adam-** [comment]
This was not clearly a bug previously, because there was no high risk world filter. But now there is since a7410dc093906e5c1db3148c7545243f21054da2, this is definitely a bug.

**Comment by Adam-** [comment]
fixed in 061cb6b5239aa652a12d327efed0797abf3042a6
