### ISSUE TITLE
New profiles deleted all old settings 

### ISSUE THREAD

**Issue by jevonsp** [runelite/runelite#16313]
### Type

Incorrect behavior

### Operating System

Windows

### OS Version

Windows 10

### Bug description

Opening runelite deleted all my settings and downloaded plugins 

trying to log back in etc doesnt do anything, do i have to rebuild my settings?

### RuneLite version

1.9.11.1
2.4.5

### Logs

[client.log](https://github.com/runelite/runelite/files/10805776/client.log)
[launcher.log](https://github.com/runelite/runelite/files/10805777/launcher.log)

**Comment by Felanbird** [comment]
Github is for technical issues with the client/launcher - join the discord for support
![image](https://user-images.githubusercontent.com/41973452/220680975-ebe95451-e020-4d35-822e-9b7df6561d27.png)

**Comment by chasertonz** [comment]
so my  account was hacked by the original owner that i bought from yet the website i got it from gavem me the username an password and i played on it for at least 7 months.. anyways i got fucked up on zanz and forgot password like 10 times in one night and recovery questions werent mine nd they wouldnt let me get the account back becuase they were able to o research and relize that the original owner had a dif useername and pass.. so is there any way possible i can find out what the password would be because i thnk its still the same i was just fucked up and coudnt remember
