### ISSUE TITLE
[MacOS] Closing the side panel doesn't resize the game.

### ISSUE THREAD

**Issue by Cloudbarrage** [runelite/runelite#16503]
### Type

Incorrect behavior

### Operating System

MacOS

### OS Version

Ventura 13.4

### Bug description

After closing the side panel in full screen the game doesn't reoccupy the space and displays a black bar on the other side of the screen instead.

This happens even on a new RuneLite profile, disabling the GPU plugin doesn't help and is unaffected by enabling or disabling the stretched mode plugin.

The workaround is to navigate to a different virtual desktop and then back.

Interestingly this only happens most of the time, while writing this bug report it did work correctly on one occasion and then broke again after exiting and reentering the full screen mode. The behaviour then was that it switched sizes a few times until it fit again.

### Screenshots or videos

https://user-images.githubusercontent.com/9503253/232854221-74e48bf2-47f5-4419-ba76-3f74c12d7b81.mov

### RuneLite version

RuneLite version: 1.9.15.1
Launcher version: 2.6.3

**Comment by adam-a** [comment]
I can look into this one. Having the same issue. Will update after investigation.

**Comment by adam-a** [comment]
> 

I've actually experienced this same thing (clicks not 1:1 with position of cursor) and I'm running Ventura 13.4 -- I have a feeling its related.

**Comment by adam-a** [comment]
Please see https://github.com/runelite/runelite/pull/16696 

Fixed it for me.

**Comment by adam-a** [comment]
@Adam- Understood -- it doesn't seem like there was a resolution though. Maybe an update for the fullscreen API broke things requiring a release for `orange-extensions`? 

If you could link the changes you made for [#13303](https://github.com/runelite/runelite/issues/13303) I'd be happy to take a look myself.

**Comment by Adam-** [comment]
There doesn't have to be a resolution for it to be a duplicate. However it contains the thought process of the person who figured out this issue before you, and so it is good to have the issues linked. The issue then was that it was not possible to attach a full screen listener because orange-extensions was targeting Java 6. This is detailed in the issue. I've very recently, in the last month, updated our orange-extensions version to one targeting Java 11, which is why you are able to write #16696

**Comment by adam-a** [comment]
@Adam- Got it. Makes sense! Thanks for the details and for taking care of the update.
