### ISSUE TITLE
Can't see the plugin 117HD

### ISSUE THREAD

**Issue by NotaSoap** [runelite/runelite#16501]
### Type

Incorrect behavior

### Operating System

Windows

### OS Version

Windows 10

### Bug description

i tried to delete/download runelite just to make sure it was up to date, even if i search 117HD, 117 HD or just HD i dont see it.. i tried to look if the plugin was merge with another.

### Screenshots or videos

![image_2023-04-18_084118510](https://user-images.githubusercontent.com/131167418/232780363-542ab14a-6328-46e8-9b17-466f9418a68f.png)
![image_2023-04-18_084133400](https://user-images.githubusercontent.com/131167418/232780424-48409ec2-9391-42e9-977b-fbc1c71eb2c2.png)

### RuneLite version

![image_2023-04-18_084146891](https://user-images.githubusercontent.com/131167418/232780484-62c454dd-ff17-480d-a87c-ef4b9d73c43e.png)

**Comment by osmanshaikhSystemsltd** [comment]
Hi, I am facing the same issue. I have also checked https://runelite.net/plugin-hub/ and it doesn't show 117 HD plugin there. Seems like the plugin has been removed?

**Comment by SaffiCauthon** [comment]
The 117HD plugin was temporarily disabled due to causing various issues; it will be back soon.

![RuneLite Tweet Regarding 117HD](https://i.imgur.com/EPf1MnJ.png  "RuneLite Tweet Regarding 117HD")

https://twitter.com/OldSchoolRS/status/1648305099943313408

https://twitter.com/RuneLiteClient/status/1648309565061038081

https://github.com/runelite/plugin-hub/commit/ba4e92dc05c00ef58188ef2c685d503287ce14e3
