### ISSUE TITLE
Motherlode Mine's node timers inaccurate

### ISSUE THREAD

**Issue by JShenobi** [runelite/runelite#16512]
### Type

Crash or hang

### Operating System

None

### OS Version

Win10

### Bug description

The circular timers showing when a depleted node in MLM will respawn have not been updated to reflect the new times as of the March 15 2023 update: https://oldschool.runescape.wiki/w/Update:The_Last_of_Poll_78

It appears the new time, at least for downstairs, is only 60s.

### RuneLite version

Runelite Version 1.9.15.2
OSRS Rev 213
Launcher Version 2.1.6

**Comment by Fillz** [comment]
I've been doing some tests, mostly upstairs, in the motherlode mine. It seems, as you said, that the respawn time is 60 seconds most of the time. However, sometimes it is shorter. The shortest respawn time I've observed is around 32 seconds after the ore vein is depleted. During my tests, the respawn time has never been more than 60 seconds.

**Comment by ShayanImran** [comment]
What would be the expected behavior here? From my understanding the timer was hard-coded is that correct?

**Comment by JShenobi** [comment]
Correct, there is no configuration in the plugin for the timers. 

The expected behavior would be the node respawning as the timer-circle fills up completely, instead of respawning and removing the circle when the circle is only a third full.

**Comment by Fillz** [comment]
@JShenobi That is partly correct. I have been looking through the code, and from what I can tell this is how it works:

There are two hard coded values. A max respawn time value (the max amount of game ticks it will take for an ore-vein to respawn) and a min respawn time value. This is because the ore-vein can actually respawn faster than the max-value and according to comments in the code, the min value is based on the developer's observations.

So what happens is that the pie timer you see on top of the rock in-game will start ticking when the ore-vein despawns, and will complete when the max time is reached. BUT! It will re-color the pie timer from yellow to green when the min time is reached (the pie timer has not completed yet at this point), indicating that the ore-vain can potentially respawn during the remaining time window. In the current code, the max time is 277 game ticks (~166 seconds) and the min time is 150 game ticks (90 seconds).

As I wrote in my first comment, it now seems that the max respawn time is 60 seconds and I have observed (as I assumed the first developer did) a minimum time of around 32 seconds. A solution could be to change the max/min timers to these values.

I'll update the code and make a pull request after I've had time to test this more. I encourage others to test this too and report what they find.

**Comment by Adam-** [comment]
The plugin was written prior to this update <https://secure.runescape.com/m=news/the-last-of-poll-78?oldschool=1> so probably all of the timing code and comments in it are no longer accurate.

**Comment by Fillz** [comment]
@Adam-  Yes, you are definitely right. However, as I wrote in my previous comment there still seems to be inconsistencies in respawn times (which is reflected in how the code is currently written). Question is how we want to handle this. Do we want to adjust the timers to something that is approximately correct (this is the previous solution in the plugin) or try to find out how jagex calculates the timers somehow?

**Comment by Adam-** [comment]
If you can observe a new min/max time for the respawn, just changing those values would probably be sufficient. I do not know if there is any deeper logic to the way that the respawn works.

**Comment by Fillz** [comment]
I'll go ahead and do that. We can always adjust the values in the future. The approximate min value should at least come pretty close to the true one.
