### ISSUE TITLE
When "Right Click Moves Camera" is enabled in the Camera plug-in, I am unable to right click objects that only have examine options (even when "Right Click Objects" is also enabled).

### ISSUE THREAD

**Issue by XVXboy** [runelite/runelite#16938]
### Type

Incorrect behavior

### Operating System

Windows

### OS Version

Windows 11

### Bug description

This issue just started today. I have tried uninstalling runelite and reinstalling it to no avail. When "Right Click Moves Camera" is enabled in the Camera plug-in, a setting I have used for as long as I have used Runelite, I am no longer able to right click on objects that only have an examine option. I.e., I CAN right click on the sheep at makeover mage, but I cannot right click on the lil' lamb nor any of the plants or decorations in the mage's house. This issue persists whether or not "Right Click Objects" is also enabled.

I can right click objects normally when the "Right Click Moves Camera" is disabled.
I realize this is a pretty minor bug, but as someone who enjoys reading the examine text on objects, especially during quests, this is very frustrating. Any help would be appreciated.

Also apologies if this issue has been addressed elsewhere. This is my first time using Github.

### RuneLite version

1.10.10.1
2.6.8

### Logs

[client.log](https://github.com/runelite/runelite/files/12364771/client.log)
[launcher.log](https://github.com/runelite/runelite/files/12364773/launcher.log)

**Comment by Felanbird** [comment]
![image](https://github.com/runelite/runelite/assets/41973452/6445f658-e747-41c5-8623-394e85d9e5a2)

**Comment by Felanbird** [comment]
> Hey there. As stated above, this issue persists whether or not "Right Click Objects" is also enabled.

My mistake I did miss that part in both your original discussion and this one.

**Comment by Adam-** [comment]
The functionality which lets you right click objects with only examine was removed because I did not think anyone used it. I would not think the game would be very playable. Why do you only have two mouse buttons but also want to examine objects? The thought was people would swap mmb <-> right click and then mmb to open the menu.

**Comment by Adam-** [comment]
Also it is not clear to me how a "right click examine" setting would interact with the new "right click objects" option.

```
		                    right click examine?    right click object?      move camera
		  has object op     Y                       Y                        N
		                    Y                       N                        ?
		                    N                       Y                        N
		                    N                       N                        Y
		
		 has examine op     Y                       Y                        N
		                    Y                       N                        N
		                    N                       Y                        Y
		                    N                       N                        Y
```

Since the case of: has object op, right click examine=on, right click object=off, does not seem to have a clear solution. It makes sense to open the menu since you might want to examine it. But it also makes sense to move the camera since you don't want to click on objects.

**Comment by XVXboy** [comment]
> The functionality which lets you right click objects with only examine was removed because I did not think anyone used it. I would not think the game would be very playable. Why do you only have two mouse buttons but also want to examine objects? The thought was people would swap mmb <-> right click and then mmb to open the menu.

I personally always preferred the right click to both move my camera and open the menu for objects. I can understand why you would come to these conclusions though! I suppose I can just learn to live with the change.
Sorry for the hassle!

**Comment by moodyxxu** [comment]
Hey, 
Is this a permanent change or could it be reverted to how this previously worked? Although niche I have used this since playing OSRS.

**Comment by Adam-** [comment]
I think the addition of allowing right click objects to move camera is good, so I do not want to remove that. But as I said in my previous comment, it is unclear to me how it can work combined with an option to allow right clicking objects with only examine.

**Comment by MBradbury** [comment]
Also just noticed this change and would appreciate a "Right click examine" option. As for your truth table my expectation would be:
~has object op and ~has examine op => move camera = True
has object op => move camera = ~right click object?
has examine op => move camera = ~right click examine?
has object op and has examine op => move camera = False

So the ? would be Y.

Are all objects examinable or is that a separate attribute? If all objects are examinable, then I would expect the ? to be N because has object op implies has examine op.

**Comment by Morcleon** [comment]
Could there be an option to revert to previous behavior where there's a selector for whether or not examine options are ignored? Otherwise, is there a way for me to revert the update that changed this? Examine was really quite nice to have as a possibility and it feels like a shame to remove it as an option entirely.

**Comment by Adam-** [comment]
> Also just noticed this change and would appreciate a "Right click examine" option. As for your truth table my expectation would be: ~has object op and ~has examine op => move camera = True has object op => move camera = ~right click object? has examine op => move camera = ~right click examine? has object op and has examine op => move camera = False
> 
> So the ? would be Y.
> 
> Are all objects examinable or is that a separate attribute? If all objects are examinable, then I would expect the ? to be N because has object op implies has examine op.

All objects which have ops are examinable, but not all examinable objects have ops. So I think the `?` in the truth table might be `N`.

**Comment by Adam-** [comment]
I've added an option for right clicking objects with examine in 02ab046602a5dcff8419ac6ff56b5904f073a1fb like how the truth table describes.
