### ISSUE TITLE
Make 200 the max lv for virtual levels vs 126

### ISSUE THREAD

**Issue by Stickaplex** [runelite/runelite#1699]
Discussed on discord a bit. But just want to make this so it doesn't get forgotten.

126= ~188m-200m xp
200= 200m xp

Pretty simple

**Comment by Kamielvf** [comment]
Obviously this should not be added since 200m xp is not even lvl 127. We could have it say MAX orso but 200 is completely wrong.

**Comment by Stickaplex** [comment]
200 is just saying 200m essentially. Not saying its lvl 200. Just looks weird. I just like how osb did it with theirs as it looks the cleanest imo. That being max vs 200 vs 200m

**Comment by deathbeam** [comment]
Just put infinity symbol instead of number at 200m exp :d

**Comment by SoyChai** [comment]
I do like the idea of having *something* to indicate XP-maxed skills in the client, because it'd help extremely dedicated players feel valued when they use RuneLite, and those players often tend to be streamers and community figures. But this solution feels unsatisfying because of how... forced it seems? I'm sure we could find ways to indicate this more subtly, like using a different colour or a small icon.

**Comment by Stickaplex** [comment]
honestly that wouldn't be too bad of an idea...would just need some playing with to make it all purty

**Comment by Kamielvf** [comment]
"max" wouldn't be too bad. I don't know about colouring it but it can work

**Comment by Stickaplex** [comment]
I just personally think having 'max' looks weird next to a skill tab full of numbers personally.

**Comment by Dovry** [comment]
https://runescape.wiki/w/Virtual_levelling

Might be an idea to steal from RS3
