### ISSUE TITLE
Idea on how to add a "Lookup" option in player menus.

### ISSUE THREAD

**Issue by RobinWeymans** [runelite/runelite#17]
I would like to add this to the highscore plugin. I found some getters in the Client class of the RuneScape API for menu options, but there is no way to change them there.

Where should I look for this?

Robin

**Comment by Adam-** [comment]
That's great. It is easier to discuss development questions on IRC [irc.rizon.net #runelite](http://qchat.rizon.net/?channels=runelite&uio=d4) than here, if you'd like to join.

In order to generate setters for the fields, you need to set setter=true within the Export annotation. The menu arrays seem to all use the same instance for the lifetime of the client - so you could just fetch a reference to that without ever having to set it.

You would have to generate a setter for menuOptionCount, though. We do this already for the username field, look at how that works.
