### ISSUE TITLE
(Certain) achievement diary cape teleport locations missing from worldmap

### ISSUE THREAD

**Issue by YvesW** [runelite/runelite#17197]
### Type

Incorrect behavior

### Operating System

None

### Bug description

The achievement diary cape teleport locations are still missing from the worldmap. However, most achievement diary masters (teleport locations), do have at least a task master icon on the map. Specifically the flax keeper and the jungle forester have no icon.

- Two-pints: task master icon
- Jarr: task master icon
- Sir Rebral: task master icon
- Thorodin: task master icon
- **Flax keeper: no icon!**
- Pirate Jackie the Fruit: task master icon
- Kaleb Paramaya: is on another plane that's not viewable. Interestingly enough, the same goes for Duradel and the Karamja gloves, while they do have icons! However, probably no one tps to Kaleb since they can tp to Duradel.
- **Jungle forester: no icon!**
- TzHaar-Mej: task master icon
- Elise: task master icon
- Hatius Cosaintus: task master icon
- Le-sabré: task master icon
- Toby: task master icon
- Lesser Fanatic: task master icon
- Elder Gnome Child: task master icon
- Twiggy O'Korn: task master icon

### RuneLite version

-

**Comment by Birger9** [comment]
Can take a look at this issue, been looking for a beginner issue =)

**Comment by grossmann4** [comment]
I was looking through `runelite/runelite-client/src/main/java/net/runelite/client/plugins/worldmap/TeleportLocationData.java` and looked on the world map and realized that none of the skill cape teleports are on there. I'm working through adding the skill cape teleports to the file but not sure what to do about the icons for them since the cape ones dont seem to be in the same spot as all the other ones.
