### ISSUE TITLE
rog ally support

### ISSUE THREAD

**Issue by Collin2245** [runelite/runelite#17252]
### Type

Crash or hang

### Operating System

None

### OS Version

windows 11

### Bug description

Hello, I was wondering if there is any sort of work around/knowledge about the gpu plugin when turned on on the rog ally, when compute shaders is checked, the game crashes on launch. Open gl vesion 4.6 is downloaded and supported and windows and all amd drivers are up to date. I know of a few other people that have the issue as well but no fix has been found yet.

### RuneLite version

RuneLite 1.10.17.1 
Launcher version 2.6.9

### Logs

[client.log](https://github.com/runelite/runelite/files/13573084/client.log)
[launcher.log](https://github.com/runelite/runelite/files/13573085/launcher.log)

**Comment by Nightfirecat** [comment]
I don't see any log messages indicating a crash. Are you seeing `jvm_crash_pid` files in your logs folder?

**Comment by Collin2245** [comment]
Hey, no I do not, unfortunately. it basically just black screens and goes white, doesn't actually close out or anything so it might not be a crash, but it does stop responding.

**Comment by 780miscursed** [comment]
I have a very similar problem with a 7840u which shares the same 780m as the rog ally z1 extreme. If i enable the gpu plugin with compute shaders:
My entire system will freeze for about 10 seconds before black screening for a moment, 
AMD Bug report tool appear; Runelites sidebar will remain functional but the canvas where the game is normally will be translucent.
The 117 plugin is seemingly more stable but still fallovers reliably within 5 minuites or near instantaneously if somewhere busy such as blast furnace on a blast furnace world.
HDOS does seem to work fairly reliably but i'm not keen on the look, nor am I happy to lose my loot tracker logs. 

I've been through around 3 different graphics drivers since getting this PC and all of them have produced the same results, which I've reported to AMD to no avail.

**Comment by rmb938** [comment]
I have the same issue on my rog ally. When gpu plugin is enabled the whole screen goes black, after a few minutes it comes back with the runelite game canvas being white. Then I have to open task manager to kill runelite and reopen it and disable the gpu plugin before logging in again. No logs in runelite saying it crashed.

**Comment by ryzenvideous** [comment]
Same issue.

**Comment by 780miscursed** [comment]
My GPU plugin appears to be working as expected with compute shaders enabled since restoring my BIOS to factory settings. I hasten to add that I never modified my BIOS from factory settings. However, in AMD's control panel under Performance > Tuning > Memory Optimizer, this setting appears to override your UMA framebuffer setting in BIOS and force you to have a scaling 512MB or 4GB vram reservation, which can cause issues for some older titles. As long as you never drop down the Memory Optimizer setting, it never takes effect. Have other affected individuals changed this setting?

**Comment by ryzenvideous** [comment]
> My GPU plugin appears to be working as expected with compute shaders enabled since restoring my BIOS to factory settings. I hasten to add that I never modified my BIOS from factory settings. However, in AMD's control panel under Performance > Tuning > Memory Optimizer, this setting appears to override your UMA framebuffer setting in BIOS and force you to have a scaling 512MB or 4GB vram reservation, which can cause issues for some older titles. As long as you never drop down the Memory Optimizer setting, it never takes effect. Have other affected individuals changed this setting?

I can't find such settings under the performance tab..

**Comment by SonderAu** [comment]
Logged in to comment, that on my Ally Z1 Extreme, turning OFF compute shaders within Runelites GPU plugin, and setting the "Memory assigned to GPU" within Armoury Crate from 4GB to Auto results in the GPU plugin loading perfectly. This primarily for me now means a singular Runelite profile between devices. Hope it helps someone else!

**Comment by aHooder** [comment]
A couple of people reported in the [117 HD plugin Discord](https://discord.gg/U4p6ChjgSE) that disabling hardware acceleration in [`RuneLite (configure)`](https://github.com/runelite/runelite/wiki/RuneLite-Launcher-Configuration) stopped the plugin from crashing on integrated AMD Radeon 780M GPUs found in ROG Ally handhelds. Kudos to [JoePav for finding it (Discord server message link)](https://discord.com/channels/886733267284398130/886739001837498418/1200081485177303134)

**Comment by clarkey2110** [comment]
Did anyone get anywhere with this please? As most others, I can get GPU working without the compute shaders option ticked but that’s what allows the increased render distance and is the main draw of using GPU plug in for me 😭

**Comment by ryzenvideous** [comment]
Looks like the new AMD Driver update managed to solve it!

**Comment by Adam-** [comment]
> Looks like the new AMD Driver update managed to solve it!

If you can specify which driver version has fixed this issue, others might appreciate it.

**Comment by ryzenvideous** [comment]
> > Looks like the new AMD Driver update managed to solve it!
> 
> If you can specify which driver version has fixed this issue, others might appreciate it.

Ah, no, they should be grateful I announced it in the first place and ask nicely.
