### ISSUE TITLE
ComponentID class missing

### ISSUE THREAD

**Issue by Entrana-RSPS** [runelite/runelite#17431]
### Type

Crash or hang

### Operating System

None

### OS Version

Win 10

### Bug description

ComponentID in net.runelite.api.widgets.ComponentID; is missing in the download. this is giving issues loading plugins

### Screenshots or videos

https://gyazo.com/3e3bd346b9c2a391d37bca2abecd81a6

### RuneLite version

lateast

### Logs

no logs

**Comment by Rowan-Mulder** [comment]
Same issue here.
Updated the project, used Maven clean+install Build scripts but couldn't run Runelite.class due to ComponentID class missing. 
Checked to see if I could add Maven dependency, updated indexed Maven Repositories and after this ComponentID popped up which I could select to add from the Maven Artifact Search, but nothing happened when adding it.
Am I doing something wrong?
![image](https://github.com/runelite/runelite/assets/62886548/47e202b0-6d64-4554-8e58-88f9a6b1c786)
