### ISSUE TITLE
regeneration meter: Special attack regeneration meter doesn't interact with Lightbearer switch correctly after update

### ISSUE THREAD

**Issue by JoshuaDunbrack** [runelite/runelite#17677]
### Type

Incorrect behavior

### Operating System

Windows

### Bug description

After today's update changed the behavior of special attack regeneration when switching to Lightbearer, the spec regeneration meter has not been adjusted to match.  

Prior behavior: When equipping Lightbearer, set the special attack regeneration timer to 15s
New behavior: When equipping Lightbearer, if special attack regeneration is longer than 15s, set the timer to 15s. Otherwise, leave it unchanged.

The special attack regeneration timer stays out-of-sync until special attack energy is full or the lightbearer is unequipped. It seems like a relatively straightforward fix, and I intend on making the necessary changes.

### RuneLite version

RuneLite v1.10.26.2
Launcher v2.6.7
OSRS rev 221

**Comment by Nightfirecat** [comment]
This behavior was changed by Jagex today, we need to make changes to the plugin to handle its new behavior

**Comment by Alexsuperfly** [comment]
how about 
`// if time since last regen > 25 ticks ago`
`// equipping lightbearer will not reset time`
`// ex: 30 ticks since (20 remain) -> 5 ticks since (20 remain)`
`ticksSinceSpecRegen = ticksSinceSpecRegen > 25 ? (ticksSinceSpecRegen - 25) : 0;`
on [this line](https://github.com/runelite/runelite/blob/master/runelite-client/src/main/java/net/runelite/client/plugins/regenmeter/RegenMeterPlugin.java#L133)

**Comment by JoshuaDunbrack** [comment]
> `ticksSinceSpecRegen = ticksSinceSpecRegen > 25 ? (ticksSinceSpecRegen - 25) : 0;`

I was planning on `ticksSinceSpecRegen = max(ticksSinceSpecRegen - 25, 0)`, but the result is the same, yeah.

**Comment by Alexsuperfly** [comment]
ahh yea, yours looks nicer
