### ISSUE TITLE
Wiki plugin does not set blowpipe correctly (wrong darts?)

### ISSUE THREAD

**Issue by vaisest** [runelite/runelite#17688]
### Type

Incorrect behavior

### Operating System

Windows

### Bug description

Title. If I have amethyst darts in my blowpipe and open the DPS calc, dps is much lower than expected until I re-choose the right darts

### RuneLite version

1.10.26.4/Rev 221/2.6.10

**Comment by jayktaylor** [comment]
As far as I'm aware, there is no client-side data available to RuneLite about what darts are equipped inside of your blowpipe (unless we track user interactions), therefore this should probably be solved by https://github.com/weirdgloop/osrs-dps-calc/issues/293 rather than a change in the RL plugin.

**Comment by Nightfirecat** [comment]
Closing this issue accordingly as this will most likely be addressed on the dps calc side of things.
