### ISSUE TITLE
only show own items - broken in cox

### ISSUE THREAD

**Issue by EJLeet** [runelite/runelite#17846]
### Type

Incorrect behavior

### Operating System

MacOS

### Bug description

with only show own items ticked, potions and secondaries dropped by bosses don't display a menu. picking them up and dropping them does show the menu. This is for all potions and secondaries.

### RuneLite version

current

**Comment by CarlOmega** [comment]
Might add to this some weird behaviour I am seeing with this setting.

Also doesn't work with some item spawns and items on table.

**Comment by Adam-** [comment]
I had made it show item spawns for a few days, but a bunch of people did not like the change in behavior, and so I changed it back. If we wanted to show item spawns again it would have to probably be with a separate setting. I am not sure this has ever worked in cox since the item drops there I think aren't real items?

**Comment by EJLeet** [comment]
Cox items used to work before you made it show item spawns. I’m not sure what you mean by real items, they have an item id as far as I know.

**Comment by Adam-** [comment]
They are weird because anyone can pick up the items that get dropped. Maybe they are normal items with no owner?

**Comment by EJLeet** [comment]
Perhaps yes. If that’s the case then an exception of some sort might have to be paid for cox items.

**Comment by Felanbird** [comment]
This setting was replaced with the `ownership filter` options, as far as I know it works as expected in CoX, except for what's reported in #18432
