### ISSUE TITLE
Clue Step missing "Speak to Uglug Nar."

### ISSUE THREAD

**Issue by Tenadrin** [runelite/runelite#18064]
### Type

Incorrect behavior

### Operating System

Windows

### OS Version

Windows 11

### Bug description

i was doing a medium clue when the step "Speak to Uglug Nar." came up and it didn't show up with the clue plugin. i tried logging in and out, and restarting my client but it did not fix the issue. After completing the step i was able to get the next step to show so i seems its an issue with the step itself.

### Screenshots or videos

![Screenshot 2024-07-18 161012](https://github.com/user-attachments/assets/ab5e4434-b2e8-4ca1-b70f-d89c3d577110)
![Screenshot 2024-07-18 161403](https://github.com/user-attachments/assets/205d4e0f-9e1f-4a5c-8040-c2f90178b697)

### RuneLite version

Runelite version: 1.10.34
Launcher version 2.6.7

**Comment by Felanbird** [comment]
Already fixed in 8c0dc822566b6a7f8c3844db4a25804562ae39e4 - there just has not been a RuneLite update since then.

If you interact with the challenge scroll you'll still be given the old hint which has the answer if needed.
![image](https://github.com/user-attachments/assets/24675e8a-0e2b-4101-914d-c6c36fbfd7a7)
