### ISSUE TITLE
Chat filter filters out messages from logged out clanmates

### ISSUE THREAD

**Issue by KnightosMaster** [runelite/runelite#18136]
### Type

Incorrect behavior

### Operating System

Linux

### OS Version

Arch Linux

### Bug description

If Chat Filter is turned on, messages from clan mates disappear once they log out, even though filtering is not enabled for clan chat.
Here are my settings, nothing related to clan chat is enabled so I would not expect ANY filtering to be made in my clan chat.  
![image](https://github.com/user-attachments/assets/792cc554-045f-4073-9948-7cf8ca35a547)
https://github.com/runelite/runelite/blob/d7cbfc9725098c969cc631150822f88543610683/runelite-client/src/main/java/net/runelite/client/plugins/chatfilter/ChatFilterPlugin.java#L314
According to this it seems that even if filtering is turned off this can still kick off if a person is not **currently** a member of the chat channel. 

### RuneLite version

RL: 1.10.35
Rev 223
Launcher: 2.7.1

**Comment by YvesW** [comment]
One could argue if this is the desired behaviour, undesired behaviour, or maybe it could be seen as a bug.

It's caused by ``isClanChatMember`` using ``ClanChannel.findMember``. Once these people log out or (probably) leave the channel, they are not seen as clan members anymore. Thus, their messages in CC will get filtered, even if ``filter clan chat members`` is not enabled. https://github.com/runelite/runelite/blob/d77149e33061b31d17e72b7dc0e4b7d1679262a6/runelite-client/src/main/java/net/runelite/client/plugins/chatfilter/ChatFilterPlugin.java#L323-L338

You could additionally check for ``ClanSettings.findMember``, which should contain all cc members. Keep in mind that this does not include the clan guests or guest clan guests, which ``ClanChannel.findMember`` does include.

**Comment by KnightosMaster** [comment]
Okay so I think I solved this issue, and figured out the source of my confusion, and it was mostly user error.
I have misinterpreted the options in the menu (guess I didn't notice the MEMBERS word), to mean that ticking the options means that you want filtering for your friends chat, etc. This is not the case, it filters every chat, and does not filter messages from friends, etc, unless you enable these options. This could be made a bit clearer in the documentation imo, but it's fine.

The bigger problem that occured is that I accidentally placed in a rule for `rsma||` (with pipes), which resulted in all of the messages being filtered, which I do not completely understand why happened but was definitely not intended on my part (it's been this way for years :skull: )

Based on this I'll close this.
