### ISSUE TITLE
Menu Entry Swapper for Shanty to be left click buy pass instead of trade

### ISSUE THREAD

**Issue by CurvedHorn** [runelite/runelite#1821]
Menu Entry Swapper for Shanty to be left click buy pass instead of trade

**Comment by inewman** [comment]
I'll do this. I'll make it its own option for now but maybe we should consider consolidating this with swapPay, swapTravel, or even a new option for combining gates/fees in general (like Port Phasmatys; I would say Al-Kharid but paying the toll is the default option already in OSRS 🤔).

**Comment by inewman** [comment]
After some thinking, there are a few Travel-related NPCs that also have Trade options (ex: Shantay, Trader Crewmember). In the current live build of RuneLite, Trader Crewmembers can have their options for Travel (Charter) and Trade swapped to the first position. If either option (but not both) is enabled, the correct option is swapped into the first position as expected. If both options are enabled in the configuration, **Trade takes priority**. This is because the Trade swap takes place before the Travel swap and both are strictly checked.

For Shantay, it makes more sense for his Travel option (Buy-pass) to take priority over his Trade option because for every player, a majority of their interactions with Shantay are to buy passes.

For Trader Crewmembers the situation is slightly more complicated because Ironmen use Trader Crewmember stores to train crafting. I can see why Ironmen would want Trader Crewmembers to have Trade as their primary option.

I think it's probably best to put Shantay's Buy-pass option within the scope of swapTravel and to reorder the Travel and Trade swaps such that the Travel options always come first if both options are selected. Ironmen can temporarily disable travel options to trade more easily (and are likely to have to charter to find new shops anyway).

**Comment by Adam-** [comment]
This can be swapped now via the custom left click swap option in dadf3661e13be1e201ade1addadd554fda346cc3
