### ISSUE TITLE
Show Status Widget

### ISSUE THREAD

**Issue by Hulksters** [runelite/runelite#18228]
### Type

Other

### Operating System

Windows

### OS Version

Windows 11

### Bug description

how do I see the widget status ?

### Screenshots or videos

![Capture](https://github.com/user-attachments/assets/1be816cf-f423-4cf4-8c23-d157b5e6e003)

### RuneLite version

110.36.3

**Comment by cdfisher** [comment]
There are a few different things in there:

- The health bar is part of the Opponent Information plugin and will appear if you attack something.
- The next one down is part of "Boosts Information". It'll show up if you sip a potion or otherwise do something that applies a buff or debuff to your skill levels.
- The bottom is from "Timers & Buffs".
