### ISSUE TITLE
Loot Tracker : Araxxor

### ISSUE THREAD

**Issue by saviorwave** [runelite/runelite#18242]
### Type

Incorrect behavior

### Operating System

Windows

### OS Version

Windowns 10

### Bug description

I purchased a Abyssal Bludgeon in between Araxxor kills and it decided that the bludgeon i got from the GE was part of my Araxxor loot.

### Screenshots or videos

![Screenshot 2024-09-07 125618](https://github.com/user-attachments/assets/9145396e-6556-4b5e-ac59-63343b16e00d)

### RuneLite version

Runelite Version: 1.10.36.3
Launcher Version: 2.6.4

### Logs

[client.log](https://github.com/user-attachments/files/16919260/client.log)
[launcher.log](https://github.com/user-attachments/files/16919261/launcher.log)

**Comment by Felanbird** [comment]
This is very likely due to the fact that you weapon swapped during the looting process.

When a boss does not have normal looting mechanics, we look at the inventory and mark down any changes as new loot, I've seen it more commonly happen while doing a bird house run.
![image](https://github.com/user-attachments/assets/19fceba4-651a-447c-870f-ef95c4c48586)
e.g. my own loot tracker for birdhouses

**Comment by Adam-** [comment]
This is just a limitation of the way the loot tracking works currently. Since it goes directly to your inventory there isn't a way to filter out other sources of inventory changes.
