### ISSUE TITLE
Ursine Chainmace causing issues with animation smoothing

### ISSUE THREAD

**Issue by samuio3** [runelite/runelite#18257]
### Type

Incorrect behavior

### Operating System

Windows

### Bug description

When using the Ursine Chainmace, many animations are not smooth when using animation smoothing. This is most notably on using teleports and combat. 

### RuneLite version

1.10.37     
2.6.7

**Comment by LlemonDuck** [comment]
Yeah, this is intentional. If you saw it working within the last few weeks, it was only until the bug was fixed.

The chainmace's idle animation does not smooth correctly, and, under the current system, we cannot separate it out from the other animations mentioned, like combat and teleports, when both are set on the player model simultaneously.

Clip of the erroneous smoothing:

https://github.com/user-attachments/assets/75b33089-cbb6-405e-a563-dbeb04f6db3e

**Comment by Adam-** [comment]
After some additional discussion we've figured out that changes that were made earlier was over aggressively filtering some animations which didn't need to be, and @LlemonDuck has patched it.
