### ISSUE TITLE
farming contract tracker doesn't work

### ISSUE THREAD

**Issue by setter43** [runelite/runelite#18260]
### Type

Incorrect behavior

### Operating System

Windows

### OS Version

10

### Bug description

Snapdragon Contract at the farming guild not showing Icon

### RuneLite version

1.10.37

**Comment by cdfisher** [comment]
This should be fixed by 3b56b9f3dc489356b0028761013ef8d285bb7bd3

**Comment by BanRokas** [comment]
It seems for me that I was reverted back into using net.runelite.api.NullNpcID from net.runelite.api.NpcID.
And I could not find any NullNpcID reference to guildmaster Jane in runelite.api. Tho NpcID seems to be working nicely.
Currently plugin code is using NullNpcID instead of NpcID. Is that what you guyz intended to do?

**Comment by SpartanLegends** [comment]
I have this issue with my main account and my alt account when I updated NVidia graphics drivers (which crashes RuneLite with the 117 HD) and reopened RuneLite to find my contract not showing at the farming guild.
![2024-09-12_20-10-34](https://github.com/user-attachments/assets/00d1b886-a3d0-4587-9043-2fa715b790a1)

**Comment by Felanbird** [comment]
version 1.10.37.1 of RuneLite was released along with the fix for this issue. If you're still experiencing this issue, restart your client.
