### ISSUE TITLE
Bank tags broke bank armor deposit button

### ISSUE THREAD

**Issue by jlragr** [runelite/runelite#18325]
### Type

Incorrect behavior

### Operating System

MacOS

### OS Version

Sonoma 14.4.1

### Bug description

I had the slayer skill open (looking at the level for araxxor) and while this window was open, I accessed my bank. Now when I use the bank, I can't click the deposit armor button unless I turn off bank tags. 

### RuneLite version

Runelite version: 2.6.13
Launcher version: 1.2.0

**Comment by CK6853** [comment]
Can't replicate on Windows 10, RL 1.10.38, launcher 2.6.10. 

To confirm whether this is a distinct issue - have you tried restarting your client? There was an issue with the "deposit worn items" button and the bank tags plugin immediately post-update about 12 hours ago (nothing to do with the Slayer menu) and it was fixed by a client restart.
