### ISSUE TITLE
[Opponent Information] Araxxor Health

### ISSUE THREAD

**Issue by Hammmed** [runelite/runelite#18433]
### Type

Incorrect behavior

### Operating System

None

### Bug description

It seems as though Araxxor's Health in the Opponent Information plugin is displaying as a percentage even when other Display Style options are selected in the plugin. 

### Screenshots or videos

![Screenshot_2024-10-14_at_9 36 40_pm](https://github.com/user-attachments/assets/b496c9b1-4890-4a1b-ab92-f974fb0d37e7)

### RuneLite version

RuneLite Version 2.6.3

**Comment by cdfisher** [comment]
I took a look at the [NPC information](https://github.com/runelite/static.runelite.net/blob/gh-pages/npcs/npcs.json) and Araxxor isn't listed there, which would cause this issue to happen. Since Opponent Information doesn't know how many hitpoints Araxxor has, it defaults to showing the percentage instead.

Looking further, it appears that the wiki scraper [encountered duplicate IDs](https://github.com/runelite/runelite-wiki-scraper/actions/runs/11284930399/job/31386908675#step:5:700) for Araxxor on the wiki page, so it didn't grab the hitpoints value from the page.

Taking a look at the wiki page showed the ID parameter was listed as being the same value in two different instances of the `{{Infobox Monster}}` template. I've adjusted the wiki page so that the scraper shouldn't have this issue the next time it runs.

**Comment by Hammmed** [comment]
Oh nice, I was having a little poke around to see where the issue might be last night but couldn't figure it out.

Thanks for sorting that out! I'll go ahead and close this issue out.

**Comment by cdfisher** [comment]
> Oh nice, I was having a little poke around to see where the issue might be last night but couldn't figure it out.
> 
> Thanks for sorting that out! I'll go ahead and close this issue out.

It may be a few days to actually be "fixed" in the client since that won't happen until the wiki scraper runs again but it should be resolved once that does happen.
