### ISSUE TITLE
Swap Shift Click option drop down list appears invisible

### ISSUE THREAD

**Issue by EpicDuckRS** [runelite/runelite#18476]
### Type

Incorrect behavior

### Operating System

Windows

### OS Version

Windows 11

### Bug description

When attempting to swap shift click options on any item, the drop down list to select what options you want to have shift-click abilities on does not appear.

### Screenshots or videos

![Shift-Click-Swap-Unavailable](https://github.com/user-attachments/assets/1a0fcda3-7e12-4b73-8d0d-c0709db512e8)

### RuneLite version

RuneLite version: 1.10.42
Launcher version: 2.6.10

**Comment by Felanbird** [comment]
Did you try safe mode mentioned at the top of the bug report template? You didn't include your logs so I can't check if you have.

**Comment by EpicDuckRS** [comment]
> Did you try safe mode mentioned at the top of the bug report template? You didn't include your logs so I can't check if you have.

I did not originally put RuneLite into safe mode. I just retried in safe mode, and the issue still stands. I did not think to post any logs because a crash did not occur, here is the log for safe-mode enabled below:

[launcher.log](https://github.com/user-attachments/files/17535094/launcher.log)

**Comment by cdfisher** [comment]
We need your `client.log` as well

**Comment by EpicDuckRS** [comment]
> We need your `client.log` as well

[client.log](https://github.com/user-attachments/files/17535246/client.log)
[launcher.log](https://github.com/user-attachments/files/17535247/launcher.log)

**Comment by buncieboy** [comment]
Had the same issue, looked into code, turns out my item swaps -> customizable shift-click option was disabled in the menu entry swapper settings. Enabling that fixed the issue.

Strange thing is I use the plugin-presets plugin, so I'm fairly sure that setting has been off for years, but shift-clicks always worked before. The config for shift clicks hasn't been touched for 4 years, so tried looking at recent changes to menu entry swapper plugin to understand why it worked before, but from the changes I saw it wouldn't have worked previously if the config was set to false (as intended) so no clue why it used to work. Only other explanation is I somehow manually set it to false then synced that to my plugin-preset, or the plugin-preset plugin disabled the setting somehow.

Either way might be worth hiding the menu entry for swap-shift click if customizable shift-click is set to false (and same for customizable left click) to avoid future confusion.

**Comment by EpicDuckRS** [comment]
> Had the same issue, looked into code, turns out my item swaps -> customizable shift-click option was disabled in the menu entry swapper settings. Enabling that fixed the issue.
> 
> Strange thing is I use the plugin-presets plugin, so I'm fairly sure that setting has been off for years, but shift-clicks always worked before. The config code for shift clicks hasn't been touched for 4 years, so tried looking at recent changes to menu entry swapper plugin to understand why it worked before, but from the changes I saw it wouldn't have worked previously if the config was set to false (as intended) so no clue why it used to work. Only other explanation is I somehow manually set it to false then synced that to my plugin-preset, or the plugin-preset plugin disabled the setting somehow.
> 
> Either way might be worth hiding the menu entry for swap-shift click if customizable shift-click is set to false (and same for customizable left click) to avoid future confusion.

I want to say that it was enabled, but then I disabled it then re-enabled it. After re-enabling "Customizable shift-click" it worked! Very strange. Thanks for pointing this out. I wonder if after further updates that maybe it bricks the customizable shift-click option? Either way, this was the solution for me as well. Thank you
