### ISSUE TITLE
Item Stats Plugin not displaying stats for quiver (charged/uncharged)

### ISSUE THREAD

**Issue by kevin-octanelending** [runelite/runelite#18516]
### Type

Incorrect behavior

### Operating System

Windows

### OS Version

Windows 10

### Bug description

When hovering over the dizana's quiver, in either the charged or uncharged state, the Item Stats plugin shows 0 stats across the board.

### Screenshots or videos

![image](https://github.com/user-attachments/assets/3f2cdbcb-8e88-4581-9891-4ef149906213)
![image](https://github.com/user-attachments/assets/1a6eb63a-d28a-4dee-8215-6aa3ba46c8af)

### RuneLite version

![image](https://github.com/user-attachments/assets/2e3fdcdb-dc9a-4e06-bfed-fed975bcc892)

**Comment by Felanbird** [comment]
This is being caused by the way the wiki is handling the uniqueness of the quiver, they put a comment next to the `ranged attack` and `ranged strength` values asking people NOT to edit them, and our wiki-scraper expects _only_ a value to be there, so it's throwing an error and not obtaining the stats of the item.

```
2024-11-08T01:55:05.4995228Z Item Dizana's quiver has an non integer arange
2024-11-08T01:55:05.4996715Z Item Dizana's quiver has an non integer rstr
```
```
|arange = +18 <!--DO NOT change this PLEASE, the charged quiver's bonus is PASSIVE and only applies to arrows/bolts, including it here would be misleading-->
|rstr = +3 <!--DO NOT change this PLEASE, the charged quiver's bonus is PASSIVE and only applies to arrows/bolts, including it here would be misleading-->
```
