### ISSUE TITLE
Option to have raids overlay stay up during the raid

### ISSUE THREAD

**Issue by Stickaplex** [runelite/runelite#1871]
Have the option to have the raids overlay (the scouting helper) stay up permanently during the raid.

-Would fill out unknowns as the raids load more.
-Maybe have an option to 'minimize' it so its not fully in the way in additon to bring it back to its normal size

**Comment by Kamielvf** [comment]
I have this almost fully working, I'm just rewriting some of it and cleaning code up. I hope to PR it soon.

**Comment by chsami** [comment]
Awesome keep up the great work!

Op di 24 apr. 2018 11:06 schreef Kamiel <notifications@github.com>:

**Comment by Stickaplex** [comment]
@Kamielvf does this include the 2nd part of this?

**Comment by Kamielvf** [comment]
Yes, plus some more features.

**Comment by Aciz** [comment]
@Kamielvf I don't know if you're still working on this, but I have a few suggestions:

* Option to print the raids scouter layout & rooms into chatbox, similar to how OSBuddy does, rather than keeping the overlay always open
* Option to recolor the letters in layout string, to make it easier to follow the layout of the raid. A quick mockup I made, colors could be different or even user configurable.

![image](https://user-images.githubusercontent.com/14221121/42628840-fefb1ce0-85d9-11e8-975a-7e377d24df14.png)
