### ISSUE TITLE
Slayer count off by 1 when logging out/in

### ISSUE THREAD

**Issue by deathbeam** [runelite/runelite#2038]
Based on Discord report slayer task count is off by 1 sometimes when you logout and relog after a while mid slayer task. The issue occurs using regular killing method (so no cannon/barrage/bursting). User reported that it occured while killing Black Dragons with rcb.

**Comment by MagicfTail** [comment]
It was caused by the user using a genie lamp on slayer

**Comment by Foulwerp** [comment]
I have had this happen to me multiple time killing iron dragons too. Slayer plugin will still show what you have to kill but display 0 instead of 1. Which is confusing because then I think my task is done and leave to find out I still need to kill 1. 

I have never used a genie lamp on slayer.

**Comment by ShaunDreclin** [comment]
Do we have a better way of determining when the player kills a monster? The slayer xp drop doesn't seem reliable enough.

**Comment by nmq12** [comment]
Occurred for me today at Iron Dragon. 1 over. Was using fire bolt with fire staff.

**Comment by Gamer1120** [comment]
One thing I want to note that on OSBuddy (about 3 months ago, no idea if it still happens), if you kill multiple monsters on the same game tick, the slayer counter only decreases by 1. Maybe it is not possible to detect how many monsters were killed on the same game tick?

**Comment by LeviSchuck** [comment]
Gamer1120, due to how RS works, some events are bundled together and it is difficult to attribute what in game actions lead to the results. 

You can see this happen if you try to clean like 10 grimy herbs as fast as possible. Only maybe 3 to 7 "actions" may come through.
The same concept may apply if you are using the dwarf cannon and two monsters die in the same tick. The reward is granted in one step instead of two.

**Comment by deathbeam** [comment]
I guess duplicate of #1046 or so.
