### ISSUE TITLE
Windows 10 custom notifications

### ISSUE THREAD

**Issue by Juzzed** [runelite/runelite#2060]
In Win10 you can't click in the red area. 
![unbenannt](https://user-images.githubusercontent.com/25037124/39382444-cc476182-4a65-11e8-8021-4e0efbcd605e.png)

**Comment by Reasel** [comment]
I was thinking we could send a game noise instead since [#1568](https://github.com/runelite/runelite/pull/1568) would make it so that we can play game sounds through mute. We could let the user pick from a list of possible game sounds. Instead of windows notification it would just send the ACB special noise for example.

**Comment by deathbeam** [comment]
This is problem only on Windows, neither OSX or various Linux distros have this problem.

**Comment by Nightfirecat** [comment]
It's not an issue on Windows 7 as it uses the bubble-style tray notifications which don't block clicks outside of that area.

**Comment by deathbeam** [comment]
So, it looks like purely windows 10 issue, hmm.

**Comment by TzZek** [comment]
This issue is indeed terrible to deal with when your on Win 10, blocked my prayer one time, not sure what a work around could be besides I believe there is a way to enable the old win 7 bubble notifications with a regedit.

**Comment by Jalopyy** [comment]
https://winaero.com/blog/enable-balloon-notifications-in-windows-10-using-a-registry-tweak/ 

@TzZek @Juzzed

**Comment by raiyni** [comment]
This is fixed by the `RL Tray Notifications` external plugin
