### ISSUE TITLE
puzzlesolver: add support for the Monkey Madness puzzle box

### ISSUE THREAD

**Issue by devLotto** [runelite/runelite#2063]
Our current algorithm for solving puzzle boxes (IDA* with Manhattan distance) depends on the puzzle having been randomized only a small amount of times (<30). Clue puzzles always seem to have less than 30 steps.

The Monkey Madness puzzle box appears to be using around 65 steps, which leaves the algorithm to run for a solid 2 minutes or more before the solution is displayed, which is unacceptable.

Maybe a special case for the MM puzzle can be added, where it uses some other algorithm. One that doesn't give the optimal solution but still helps the user.

Also, the MM puzzle uses inventory ID 221 instead of 140. The item IDs in the container consist of even numbers, and can as such not be passed into the current ``convertToSolverFormat`` method. This differs from the clue puzzle container 140, which has no gaps.

**Comment by steffenhauge** [comment]
Currently toying with a custom solver for MM puzzles (solve top row, then solve left column, ie. reduce size to 4x4 etc.) It's currently very ugly but very fast, since it's not an optimal solution, but mimics the "human" way to solve it.
Some results:
Using this puzzle for testing:
`int[] mmPuzzle = new int[]{6,0,12,3,2,1,5,13,19,4,7,11,8,16,10,15,21,17,18,14,20,22,-1,23,9};`
- Pure custom solver:
27ms 246 steps
- Reduce to 4x4 and solve with IDA*:
2942ms 140 steps
- Reduce to 4x5 and solve with IDA*:
34ms 192 steps
- IDA* only:
18 mins 61 steps

Thoughts about this?
