### ISSUE TITLE
"Panic by the mausoleum in Mortyania" clue pointing to confusing location

### ISSUE THREAD

**Issue by troypressley1** [runelite/runelite#2082]
For the emote clue scroll "Panic by the mausoleum in Mortyania. Wave before you speak...". The red flashing arrow on the mini-map points at the island you need to get to, but they way it leads you doesn't get you to the island.

You have to go through the experiment cave first, so the arrow should point that way, and then north-west once inside the cave to the ladder that leads you right to where you need to be.

**Comment by Roughsketch** [comment]
I believe this is just a limitation of the current design. In this case, an emote clue can only have one location associated with it which is where you're supposed to do the emote. In order to guide someone it would need to have several locations and know when to switch them. 

Perhaps that can be an enhancement for later?

**Comment by deathbeam** [comment]
Looks like this is working as intended
