### ISSUE TITLE
Ground items do not refresh after dying and returning back

### ISSUE THREAD

**Issue by deathbeam** [runelite/runelite#2140]
Currently when you die at some places, example:
* Cerberus
* Abyssal Demons in Catacombs
* Abyssal Sire

after you return your ground items will not be shown on ground unless you pickup one ground item.

**Comment by Reasel** [comment]
The underlying issue is that we only rebuild the grounditems when a new item appears on the layer, the config changes, or the game state changes. But since when you die we only trigger on the respawn and upon return none of the conditions are met. Short of tracking death location and triggering when it is in sight I think the only surefire way to solve this is rebuild every tick, which seems like overkill to me.

**Comment by Adam-** [comment]
Fixed in 2ef485dc309ecc15ccb1c9ef7cc946587ab1b0c2
