### ISSUE TITLE
Reminders Not Being Removed when Task is Done

### ISSUE THREAD

**Issue by Exstatic** [runelite/runelite#2186]
I have RuneLite remind me when I need to get my daily battlestaves. The problem is that it keeps reminding me even after I get the staves as shown here: https://i.imgur.com/8n88scB.png

**Comment by Jalopyy** [comment]
I noticed this too, I assumed it has something to do with the check to not show this being saved locally every day, since I often switch between desktop and laptop.

**Comment by Infinitay** [comment]
If someone can pull #1129 and try it out for themselves to see if they no longer have an issue that'd be wonderful, otherwise you'd have to wait until after Thursday when I'm done with my final exams. That PR has been out for a while now and as far as I remember, it fixed the issue you all are describing.

Of course one thing to note is that if you have the chat history plugin enabled, of course the message will still be there. Otherwise, it will only send the message once every (RuneLite) session.

I am currently rebasing the PR.

**Comment by deathbeam** [comment]
This should be fixed in #5212 . Reopen if issue still occurs
