### ISSUE TITLE
Tithe Farm: Timers reset on map loading

### ISSUE THREAD

**Issue by ShaunDreclin** [runelite/runelite#2375]
Every time I cross one of the loading zones in tithe farm, all the timer overlays reset to full.

**Comment by Unmoon** [comment]
This _can_ be fixed, but it's a very ugly hack where on gamestate change to loading you add a "dont remove" value to each plant and remove the value on despawn event. It's because every time you load a new area, objects get despawned and then immediately spawned again.

Adam didn't like the fix when I had it initially, so I just figured it's acceptable to have the bug since it only happens once when you enter the area.

**Comment by Abextm** [comment]
I think the best way to do this would be to not use a despawn event, and just check for existence every tick, like the HunterPlugin does. Because there aren't many objects its a probably not bad for performance either.

**Comment by ShaunDreclin** [comment]
Whoops, misclick lol

There's a loading zone inside the farm so depending on which patches you use you can actually run into it quite often

**Comment by Unmoon** [comment]
Yeah, but I meant it only happens once per entry unless you do some really weird pathing.

**Comment by dekvall** [comment]
Is this still a problem after the Hosidius rework? Tithe farm is now 1/3 of what it once was.

**Comment by dekvall** [comment]
This can be closed as Tithe farm now is of a more appropriate size.
