### ISSUE TITLE
Item drop despawn and visibility timers

### ISSUE THREAD

**Issue by Sovexe** [runelite/runelite#2383]
Suggestion
- Ability to track the time remaining until an item on the ground despawns
- Ability to track the time remaining until an item becomes visible to other players
- Ability to limit tracking to only certain items by name or by type
  - For example tracking only food and pot despawns

Things to discuss
- How to go about displaying the counter 
  - Pie chart or maybe inline with ground indicator information
  - Want to minimize clutter
- How to handle stacks of the same item
- Special Cases that affect timers
  - Items dropped in an instanced area
  - Items dropped on death
  - Are there other special circumstances that effect item despawns?

This would be very helpful for juggling items in areas such as GWD where you might have gotten more supplies from drops than you can actually hold

**Comment by blenderbottle1** [comment]
This is a pretty good one. I would like this as well.

**Comment by Castro3halo** [comment]
Think this would be awesome.

**Comment by tikeyike** [comment]
This would be a neat feature to have, but how would to implement it? Like a timer for every item that you or a monster drops? or maybe one timer per tile where there is an item on the ground that just dropped?

**Comment by vilzuh** [comment]
Support. 
I'm suggesting a toggle to choose between showing timer on items dropped by me and by others. To help with clutter you could have timer only on items dropped by yourself. Maybe additional toggle to always show timer on highlighted items or at value tier and above.
In my vision the timer would be additional line on top of loot pile showing just a number for seconds left before first item despawning. Numbers could switch color to indicate whether the items are visible to others.

**Comment by Adam-** [comment]
I've been doing some work on this recently based off #4708. The only despawn timers we can measure with any accuracy are from 1) items you have dropped, and 2) items you received as loot from a kill.

Items other players drop are indistinguishable from static spawns the world has, which never despawn, so I don't see a way we could do it without also showing despawn timers on static spawns which I'd rather not do.

I have made #9423 with this.

Stacks of duplicate items are handled by keeping the time of the oldest item, which is always the minimum value for any item in the stack, and invalidating the timer whenever any item is picked up, since it is not possible to determine client side which item is picked up in a stack of duplicate items.

Currently I am not handling items placed on tables, and items dropped on you drop on death.

**Comment by VictorVation** [comment]
@Adam-  - is it possible to support visibility timers as well? i.e. how long it will be till others can see my drops?

**Comment by Adam-** [comment]
Yes I have that in the current PR.

**Comment by JacoboMoral** [comment]
> Items other players drop are indistinguishable from static spawns the world has, which never despawn, so I don't see a way we could do it without also showing despawn timers on static spawns which I'd rather not do.

Static spawns could be added manually. Even though I understand not doing it, as it's a tough task and an ugly solution.

**Comment by Adam-** [comment]
added in #9423
