### ISSUE TITLE
Pyramid Plunder display correct doorway

### ISSUE THREAD

**Issue by newuser28374** [runelite/runelite#2446]

**Comment by Kaorixx** [comment]
Possibly op?

**Comment by Reasel** [comment]
I think this is fine as long as it is only for what you have seen. IE it isn't synced per world by anyone using RL.

**Comment by Stickaplex** [comment]
Honestly kind of curious how the doorways actually work...i know they change and that if your in the room with some1 else its the same door for both of you...but if the other person has left by the room it changes (can tell because a skele/swarm will be right outside the door they went through)

So maybe it changes if room is empty or not? Idk assume some pattern to it

**Comment by Reasel** [comment]
AFAIK its on a timer similar to Kourend Library where its the same location for everyone on that world for 20-30 minutes and then it will switch. That is why its better to run Pyramid Plunder in groups since you can figure out which door is good.

I think what you need to do is check when the player successfully goes through a door and mark it. One door per level and then if they go through another door mark that one. It wouldn't update for other players going through a door, but it would at least tell you where you know it works.

**Comment by deathbeam** [comment]
Looks like this is not possible other than tracking when other player goes through the doorway before you, what we do not really want to implement
