### ISSUE TITLE
Farming timer shows fruit trees being completed before they are actually available for harvest

### ISSUE THREAD

**Issue by Nightfirecat** [runelite/runelite#2491]
title. I recently did a farm run where my fruit trees were labeled as "Done" in the farming plugin, but still needed about 1 more hour of time to finish growing--only updated once I came within range of the trees.

**Comment by AlbinCederblad** [comment]
When you plant a fruit tree it will start growing at a certain point in 5-160 minutes, then grow one cycle every 160 mins until done. This initial time is what you experienced as "about 1 more hour" i think. The code doesnt seem to take into account that initial time, since it's not possible as far as i know, unless you stand there and wait for it to happen. It could be changed so that it always adds one more growth cycle to the estimated done time, but then again you maybe could have harvested it earlier.

This is just my guess.

**Comment by Jimichaelk** [comment]
Could we get the ability to add or subtract minutes from when it thinks the growth time is? Personally as an example my growth happens 3 minutes before it says. This becomes a problem because if I plant a crop at 11:58 I’ve missed he 12:00 growth time because it happened at 11:57. This causes the plugin to think its first growth will be at 12:00 when its actual first growth tick for a 10 min crop will be at 12:07 which the plugin calls 12:10. This is really annoying it it’s a tree because it will be off by 80 or 160 minutes instead of 10 or 20. If we could add or sub like 5 minutes to the growth time and have the plugin act upon the modified growth time instead that would be amazing.

**Comment by fermonos** [comment]
Farm timers seem to be broken. If I plant a herb at 5:03pm for example and it takes 80m to be able to harvest, it should be done at 6:23 and will be 80m on the timer, but for some reason runelite rounds up to the nearest 10 minute.

so example I plant at 5:03, it will say it's done at 6:10pm and will only take 67m, meaning you'll arrive 13 minutes early. Even sometimes some of the patches can even be off by 30m. - This also happens for all types of farming products example trees, bushes, flowers, not just herbs.

I suggest either fixing the timers so when you plant a herb it will count down from 80m or have it so the user can make a customisable timer like what you can do right now but make it automatically so when the client determines a ranarr seed has been planted it will count down from what the custom time has been put in the settings by the user.

Thank you so much for taking your time to read, I've attached a link https://i.imgur.com/u4C2ipP.png to show the 'bug' in question. The herbs in the picture were all planted from within 10s-120s of each other, but as you can see it says they'll only take a total of 67m (13 minutes early), while it should be 78m-80m. One is even off by 33m.

I sincerely hope this is fixed, it can be really annoying because when you show up to a herb in it's last cycle of growing, if you are near by while it's supposed to finish it's cycle and be ready to harvest you can stop it and make the whole of the last cycle to repeat. For herbs, it's only around 10 minutes or so but it can go into hours for trees, and almost even a day for the hardwood tree if you turn up early, so yeah. It can become quite annoying.

**Comment by raiyni** [comment]
@fermonos growth stages happen certain ticks, not when you plant them.

The rounding for the plant times still might be wrong though.

**Comment by deathbeam** [comment]
If this is wontfix it should not be open, so closing. We can reopen whenever we would be able to figure out when the tick happens, what will probably not be in near future.

**Comment by spychopat** [comment]
Hello,
I know we can't know when the grow tick happens, but could we get a setting to always predict the time one tick later ? i don't want to go leave my activity, prepare and go to my tree to realize it's not ready yet
i would be fine with going to them one grow tick too late
