### ISSUE TITLE
Shift-click config for things outside of inventory

### ISSUE THREAD

**Issue by Stickaplex** [runelite/runelite#2539]
Wasn't sure the best way to word title but essentially just shift click for various things like could set shift-click to be collect on banker or talk to or w/e other options there are for various npcs or things in game that have more than 1 'command'

**Comment by jonesdev** [comment]
Am I mistaken in thinking this already exists via menu entry swapper?

**Comment by Stickaplex** [comment]
menu entry swapper is just so you can left click things like bank/trade simple stuff like that. shift click would be a different action.

so example would be if you had both on would be: left click->bank. Shift+left click->collect

**Comment by SomeZer0** [comment]
This would be overpowered for certain situations, increasing XP/h.

For example: Swapping pickpocket to be the first option when BlackJacking.

Making a universally configurable menu swapper for the game world would make a lot of issues like this. Instead of making the universal rule and blocking certain actions, which would be more annoying to do, and would also confuse users; "why isn't menu swapper working for X npc on Y action?" Making custom rules for individual NPCs/Objects lets us make sure that there are no overpowered menu swaps which would be abuseable.

**Comment by Stickaplex** [comment]
So would you prefer i say request a list of shift click menus id want swapped then? Seems like it would be a rather long list for everything not op then

Dont get me wrong though i get your point

**Comment by deathbeam** [comment]
We cant allow free customization of entries outside of inventory, that would be overpowered, closing as wontfix
