### ISSUE TITLE
Other clients settings import 

### ISSUE THREAD

**Issue by Gamer1120** [runelite/runelite#2687]
Allow OSBuddy and Konduit settings to be imported somehow.

**Comment by Infinitay** [comment]
I was looking at a way to import Konduit's bank tags, but their files are encrypted so I'd figure OSB's is the same?

**Comment by southernzax** [comment]
I was actually planning on working on this originally but after discussing it in the Discord I think the issue bubbled down to the maintenance required would likely be really big since to maintain it would mean keeping up with other clients changes anytime they make an update as well as our own to the way things are done.

That was the general consensus anyways, if the opinion has changed and is considered an acceptable project I would definitely love to tackle it but I also see the concerns for config changes/updates to other clients or our own possibly breaking things very often.

**Comment by deathbeam** [comment]
I would close this, I dont think its worth maintaining w/e change other clients decide to make and rely on that for having working feature. Also seems like people are not having trouble with migrating.
