### ISSUE TITLE
Make old deobber not easily compatible with client

### ISSUE THREAD

**Issue by KevinFerm** [runelite/runelite#2803]
With the risk of just reiterating something you've already thought of, it might be a good idea to change the implementation enough that the removed deobber is not easily compatible with this client anymore.

**Comment by R030t1** [comment]
This suggestion makes no sense. The deobfuscator doesn't violate the DMCA. Redistributing code from Jagex verbatim does. It *may* be against the DMCA to distribute the deobfuscated code, though that would still need to go to court. Distributing instructions on how to deobfuscate the client **can not** be in violation of the DMCA because it does not contain any copyrighted work save that of the authors of the deobfuscator.

[Reverse engineering for interoperability](https://en.wikipedia.org/wiki/Reverse_engineering#Overview) is legal, even if the original vendor of the goods you are inspecting does not want them to be interoperable with anything else.

Keep in mind that if Jagex had a valid DMCA complaint they could just go to GitHub to get the repositories taken down. They may not have done so because their lawyers realize they do not have a valid complaint. Is any binary distributed by Jagex hosted in the runelite repositories?

**Comment by vmsplice** [comment]
@R030t1, so if I understand correctly, Jagex pressured Adam to remove the deobfuscator from this repo even though it wasn't strictly necessary? Can we get it back? Or can someone fork this project and include it? If @KevinFerm's suggestion ends up being implemented, it should be possible to create a compatibility layer that just translates the calls between the different implementations, right?

100% open source client is definitely something worth fighting for. Unfortunately I don't have the necessary skills to make it happen but I'd be glad as much as I can.

**Comment by SoyChai** [comment]
It was removed because Jagex is currently disallowing `the sharing of tools used to deobfuscate Old School RuneScape code, and then re-publishing said code`. So we're going to host that code privately (ie. closing the source) to appease them. Adam just wants to avoid a legal argument here.

**Comment by vmsplice** [comment]
I don't know about the legal argument if only thing it breaks is the ToS but I understand why Adam doesn't want to take the risk.

So only the deobfuscator is made closed source and everyone will still be able to modify, compile and use the client as they wish, they just need the deobfuscated offsets from RuneLite devs after each update?

Seems too good to be true. Adam's statement is even more worrying:

> The two clients become not too dissimilar at that point, both with a closed API implementation. What this means for developers is you must rely on our exposed API and are no longer able to extend or modify it

How exactly are you going to have a closed API when all of the client is open source and for anyone to extend or modify? By crippling the now-closed-source deobfuscator in such a way that the client is only able to obtain certain information about the game state?

**Comment by SoyChai** [comment]
Nope, you'll still be able to build the client yourself. Runelite's API surface is still open to view and access, we're just hiding the implementation of that API. It's not necessary to see its inner workings in order to write and test new plugins for RuneLite, but it will be more difficult to understand what you're doing.

**Comment by ShaunDreclin** [comment]
Think of it like putting on Shaun-goggles

**Comment by R030t1** [comment]
@vmsplice: That is what it looks like. There is no legal reason that I can see for the team to have removed the deobfuscator. I have been playing runescape for many years, and in those years dozens of deobfuscators have come and gone. Not a single author was prosecuted even though many of them were publicly available.

@SoyChai: Like I said, reverse engineering is legal regardless of what Jagex thinks. They can refuse to do business with the developers if they want but that is it. Please do not simply roll over. If anyone is truly concerned (which a number of people appear to be, since they have given into Jagex's baseless request) they should contact the Free Software Foundation at info@fsf.org explaining the problem and requesting legal help.

For reference, here is [Jagex Limited v. Impulse Software](https://www.moparisthebest.com/downloads/jagex_ltd_vs_impulse_software.pdf). The claims that copy protection measures were circumvented are suspect. The main actionable claims are that Impulse Software reused Jagex's assets.

If the open source portion of the project is abandoned in this way I expect the user base to decline as people support their own open source forks. It has happened before. There are communities online that have been dealing with these issues longer than some people have been playing RuneScape.

**Comment by SirFireNewt** [comment]
It should be noted that you can find the deob in most of the forks still, so grab a copy while you can I guess.

**Comment by reb1995** [comment]
What was the deob named in previous versions.... Looking for it in forks.

**Comment by Mod-MattK** [comment]
The Deob was namned "Deob 317".
