### ISSUE TITLE
Dark Totem Bank Reminder

### ISSUE THREAD

**Issue by RDumais** [runelite/runelite#2856]
I would like to see if someone could create a simple icon or something in the bank interface notifying the player if they have the 3 required pieces of a dark totem. I often find myself with all three pieces in my bank when I should have combined the items. 

'Players must assemble the totem if they wish to receive further totem pieces from monsters within the Catacombs.' -OSRS Wiki

**Comment by Tylemagne** [comment]
It should add to the chat "Please assemble all your totem pieces to receive more!" the first time you open your bank when you log in. Anything else would be too annoying for me.

**Comment by RDumais** [comment]
That would nice as well. Any kind of notification is welcomed.

**Comment by Reasel** [comment]
I think this may be better fixed with something more robust like [#2474](https://github.com/runelite/runelite/pull/2474)

**Comment by winterdaze-rs** [comment]
No longer needed due to recent update 

> Players may now continue to gain Dark Totem pieces in order even if they have not combined their existing pieces.
If you already have an incomplete set of dark totem pieces, the game will attempt to select a piece that will complete the set. This means that the chance of completing your set has not been made harder by this update. 

(https://secure.runescape.com/m=news/qol-and-w45-changes?oldschool=1#_ga=2.179262115.643276230.1553127169-664269094.1536735508)
