### ISSUE TITLE
Menu Swap Changes - Dark Core / Teleport Items

### ISSUE THREAD

**Issue by DuhFonzz** [runelite/runelite#2925]
1. Simple swap option for the core at corp to make "walk here" the default option instead of attack. OSB Has similar option and would be nice.

2. Break down "teleport item" category to allow more options. As is turning it on means having to right click the mythical cape to wear it to have left click enabled on games necks.

**Comment by Nightfirecat** [comment]
For (2), this can be fixed with #1556. (once that's merged, the "Teleport item" option should realistically be removed in favor of allowing users to set up their own left-click and shift-click configurations)

For future reference, you should generally submit one GitHub issue per bug or suggestion. That way, it can be tracked better by project maintainers.

**Comment by Adam-** [comment]
Walk here on the core was added in 1fb5365e7c7a8ff5d3f65604c25c9e8358a0fefd.
