### ISSUE TITLE
Feature Request: Anti-Drag

### ISSUE THREAD

**Issue by anon199469** [runelite/runelite#3200]
Is it possible to have anti drag back to how it used to be? I’d rather not have to use AHK like everyone else who used anti drag without shift. We shouldn’t cater to streamers. If there is a big enough issue I’m sure JaGex will reach out. This is honestly just QoL

**Comment by Adam-** [comment]
We are not comfortable pushing this any further than OSB has at this time.

**Comment by jbaker5011** [comment]
@anon199469 you can still emulate how it used to work with Windows by enabling Sticky Keys and then pressing shift

**Comment by anon199469** [comment]
I use shift to drop stuff. High level PvPers already use software for this and Jagex has said it is fine. I just don’t like the streamer favoritism. It wasn’t an issue until Skill Specs complained

**Comment by matthewpetch** [comment]
> Jagex has said it is fine

Where?

**Comment by forsco** [comment]
I'm not sure how I stand with this looking from both sides.

If people are just going to work around the shift anti-drag albeit by sticky keys or AHK is there much of a point changing it to this?

**Comment by BigMemeYek** [comment]
Pkers already have their own version bring it back 😡

**Comment by anon199469** [comment]
JaGex fixes the drag issue closer to EoC. They implemented it into their game because hey saw it was a QoL update. It should be the same here.

**Comment by joshbz93** [comment]
Revert please.  Shift is used to drop items.  At least give an option to use a different key.

**Comment by iguaan** [comment]
It's not about if we consider this balaned, I don't think anyone here at least is arguing that this is way too overpowered, it's about doing what has been already done for a while. In RL (and also OSB) you can just keep using this feature the same way as it was 'pre-nerf' if you disable shift-drop and use sticky keys to stuck a shift key. This is an easy way of covering RL in case someone starts whining about the feature being too overpowered.

**Comment by SoyChai** [comment]
Following behind OSBuddy when it comes to potentially advantage-giving features is normal practice for us, since their company has much closer communication with Jagex than we do. It's unfortunate that we didn't make this decision *before* releasing the Anti-Drag plugin, that was obviously a mistake; but we have to stick to our guns now.

Big sorry to anyone who was starting to get comfortable with it! :(

**Comment by joshbz93** [comment]
Feature that tell you what bosses are in a raid: OK (although literally cheating in my opinion)
Feature that guides you through boss fights: OK.  
Feature that guides you through clue scrolls: OK.  
Feature that keeps you from accidentally dragging an item: Over Powered. 
????????????????????

**Comment by Reasel** [comment]
@SomeZer0 Where did Jagex approve that?

**Comment by SomeZer0** [comment]
MMK / Amenity.

**Comment by anon199469** [comment]
It’s honestly just remapping and they’ve stated you’re allowed to remap keys so why not add the feature back?

**Comment by Reasel** [comment]
Care to link? As far as I know anything AHK is bannable as per Jagex statement [here](http://services.runescape.com/m=news/mouse-keys---changes--clarification?oldschool=1).

Quite clearly states 

> Historically, we have not given bans for some usage of programmable mouse keys (such as AutoHotKey). If players kept their usage of such software to an acceptable standard, we would not take action against them. **This is no longer the case.**

**Comment by anon199469** [comment]
And on that link it says you’re allowed to remap your keys. That’s all this is, simple remapping which from the above statement is allowed.

**Comment by anon199469** [comment]
I agree 100%. Allow a toggle or remove the feature in a whole. You’re able to use it either way so what’s the big deal?

**Comment by jar17** [comment]
I'm not sure I see why this features is any more overpowered than current features like Auto-Demonic Gorillas (it's way overpowered in my opinion). Being that this is something most everyone with the need to do it already has workarounds for, why not just keep it implemented in the RuneLite client?

**Comment by larrydubz** [comment]
This is one of the main reasons why i switched over to RL because you didn't have to toggle on with a binded key for anti drag. There's literally no difference if you have to bind a key or not because it works the same way. It's quality of life. Please give us it back

**Comment by BestinBin** [comment]
this need to make a comeback stat!!!!! one of the best features on RuneLite :dancer:

**Comment by DiamondPKer** [comment]
Hey first off wanted to let you guys know great job with the client! The only issue i'd like to see (which i heard used to be an option) is if we could possible turn off the shift key needed for anti drag? i use the shift key for a lot of things and I tihnk it would be easier if the option was just enabled or disabled. Sorry my english is not greatest but if you have any questions let me know

**Comment by 07Arab** [comment]
Would it be possible to allow us to pick from a set of buttons (CTRL,ALT,TAB,etc) instead of just SHIFT for the button required to be held down for the Anti-Drag plugin. What pre-set buttons that can be picked can be at the discretion of the developers.

Why? This would help prevent a conflict with most people already using SHIFT to shift drop items with the vanilla setting OSRS already has. I know there is workarounds about this aswell but I think this might be a more smoother solution.

Any thoughts on this matter is appreciated ^.^

**Comment by DiamondPKer** [comment]
First time on GitHub but someone told me I could comment about this issue here. I support the reintroduction of Anti-Drag. This has assisted me enormously with skilling. This was one of the sole features on RuneLite that I constantly told my friends about. A lot of them made the switch over after they found out about this plug-in (they were on the fence between OSB and RL). I really hope you guys reconsider <3 Thanks for the great client!

**Comment by Throwaway9911** [comment]
seriously you guys are acting like jambrex...just add the plug in back . We dont need to copy osb we are our own client

**Comment by Prozomb** [comment]
Support

**Comment by Infinitay** [comment]
I agree with some of the points other users have made. We have plenty of other plugins that are far more overpowered than an anti-drag plugin that what I see as a QoL plugin. Succumbing to the complaints of to 2-3 (from what I heard) streamers is pretty dumb in my opinion as you're taking the word of a few against the word of many other players, and for what, hoping they'll endorse RuneLite? 

Yes, we should follow OSB in some aspects as they're closer to Jagex, but if thats the case, why do we still have a demonic gorilla plugin, wasn't that the other big controversy? Yet we argued it simply helps the player not having to memorize what they can easily do on their own.

I really think we should revert this plugin back to it's original state, without the requirement of having to hold down any other key. I don't want to resort to having to use AHK or another program, or rebasing my local build to revert these changes as it's tedious and shouldn't be needed. 

------

However, contradicting my arguement above, I do agree it's unfair to other players on the **vanilla** client and pking, which is why I'm proposing disabling the functionality/required to hold down shift or another modifier when the player is **interacting with another `Player`**. I'm not sure if this will affect performance or functionality, but it gives both the PvMers/Skillers what they want, and PKers what they want, without the streamer favoritism. The best of both worlds.

**Comment by SoyChai** [comment]
Anti-drag is still a feature, you just have to hold the Shift to key to use it for now.

**Comment by Nezd** [comment]
@SoyChai and what do i have to do so i dont click shift key

**Comment by CaraPis** [comment]
Use an ahk script:
LButton:
Click
Keywait, LButton
return

Be sure to use the keywait otherwise you'll be autoclicking

**Comment by AverageHumanoid** [comment]
Removing an option that requires AHK to work around is stupid.

**Comment by zeruth** [comment]
Remapping keys is allowed so yeah idk why it was ever removed. esp when everyone is trying to work it around to how it was.

**Comment by deathbeam** [comment]
The decision was that we dont do this because OSB does not. After/if OSB will add this this can be reopened
