### ISSUE TITLE
2005 Interface - Chat Box not changed

### ISSUE THREAD

**Issue by Viizva** [runelite/runelite#3201]
Great update today 5/24/2018. 

The option for the **2005 interface** should also change the text box because that is major part of the theme itself. Can the 2005 interface setting be updated to **change the chat box** as well.

**Comment by Viizva** [comment]
Its just that classic the teared paper look is so nostalgic :) 

It doesn't have to be exact like the 2005 one! A photoshopped one that isn't exact but still encompasses the same amount of lines would be awesome.

**Comment by Viizva** [comment]
@Adam-  I have been in contact with people in the development channel on discord and from their feedback and needs I have made this for RuneLite! https://imgur.com/a/KgltZd3

I am not sure how to submit and official request so I can posting it here!

**Comment by troypressley1** [comment]
I would definitely use that^

**Comment by Veteranhd** [comment]
**Is your feature request related to a problem? Please describe.**

Im not a fan of the way the chatbox looks and I would prefer a toggle option 
that shows the old chatbox which will make the interface official instead of looking 
like its pasted on the OSRS gameframe.
**Describe the solution you'd like**

The exact chatbox from 2005 being implemented with 
no extra stones... when you click the trade/compete button 
add a feature that caters to the clanchat if thats not possible im ok with it bare bones.


**Additional context**
Add any other context or screenshots about the feature request here.
![tgyh](https://user-images.githubusercontent.com/40017995/41082097-bb262ea4-69f2-11e8-8838-68076c0e3bdf.png)

**Comment by Viizva** [comment]
The current "updated" chat box doesn't look **high quality** like the way RuneLite is known for. The un-updated chat box looked better than what we have now.

I went ahead came up with my design below
![Image](https://i.imgur.com/XEUT3M3.jpg)

I was also able to contact Sebas and was shown how it would look in game 
![Image](https://i.imgur.com/OlTVpGM.png)

Imo it looks **better than the current updated** model. Please consider this design as I feel it looks higher quality and matches the client's hard work and attention to detail.

**Comment by Nightfirecat** [comment]
I'd recommend continuing with a new issue to request a better 2005 interface chatbox. This particular issue has been resolved.

**Comment by tannerdino** [comment]
> The only thing I can't find is a screen of what the old preferences panel looks like! I'm sure someone has one, can anyone post it here?

![image](https://user-images.githubusercontent.com/61213166/231619873-3b6ca375-efbd-432a-8868-042f83cff771.png)

Note this is probably like 2003, rs2 beta. Theres no music icon, and thats supposed to be barb village xd
