### ISSUE TITLE
OSRSBeatz Plugin

### ISSUE THREAD

**Issue by jjdtsb** [runelite/runelite#3390]
It would be amazing to have a plugin for RuneLite that replaces default music tracks with the remixed soundtracks by [OSRSBeatz](https://www.youtube.com/channel/UCs1rnF_c_VSg74M5CQ-HKWg). I've asked OSRSBeatz for approval and he's totally cool with the idea!

**Comment by redj0** [comment]
On it mate

https://www.youtube.com/watch?v=tJYBAo5G_4E

**Comment by alowaniak** [comment]
Since there hadn't been much movement on this issue for a while I went ahead and did something similar myself.
Initially I did a pretty big overhaul in the existing music-plugin, but I wasn't 100% happy with that + had some annoying bugs.
So I moved it into an external plugin here https://github.com/alowaniak/music-replacer

**Comment by Nightfirecat** [comment]
Per @alowaniak, the [Music replacer plugin](https://runelite.net/plugin-hub/show/music-replacer) on the hub can do this.
