### ISSUE TITLE
crashing on fedora 27 in GNOME when trying to customize color of screen markers

### ISSUE THREAD

**Issue by Theyflower** [runelite/runelite#3431]
**Overview of issue:**
When I click the icons with the alt text "Edit border color", and "Edit fill color" my entire desktop environment freezes and then RuneLite crashes. After RuneLite crashes everything returns to normal. During the freeze I can still interact with the desktop environment (move mouse, etc.) and sound continues to play but the picture stays frozen until RuneLite is done crashing.

This does not occur when I click the "Toggle background transparency" icon or any other buttons in the Screen Markers interface.

There is no output to the terminal when this crash occurs.

java version and operating system
```[aaron@oniongarden runescape]$ alias runelite
alias runelite='java -jar ~/games/runescape/runelite.jar &'
[aaron@oniongarden runescape]$ java -version
openjdk version "1.8.0_171"
OpenJDK Runtime Environment (build 1.8.0_171-b10)
OpenJDK 64-Bit Server VM (build 25.171-b10, mixed mode)
[aaron@oniongarden runescape]$ cat /etc/fedora-release 
Fedora release 27 (Twenty Seven)
```
**Reproduce the error:**
Click the click the icons with the alt text "Edit border color", and "Edit fill color".

**Related issues:**
I searched for open issues with crash in the title and none seemed relevant

**Suggested fix:**
The first place to look for something causing this issue is in the screen markers code, otherwise I've no clue.

**what i've tried**
I have tried to [disable hardware acceleration](https://github.com/runelite/runelite/wiki/Disable-Hardware-Acceleration) but when I try this RuneLite just crashes before launching.
```[aaron@oniongarden ~]$ java -jar ~/games/runescape/runelite.jar --mode=OFF
Exception in thread "main" joptsimple.UnrecognizedOptionException: mode is not a recognized option
	at joptsimple.OptionException.unrecognizedOption(OptionException.java:108)
	at joptsimple.OptionParser.handleLongOptionToken(OptionParser.java:510)
	at joptsimple.OptionParserState$2.handleArgument(OptionParserState.java:56)
	at joptsimple.OptionParser.parse(OptionParser.java:396)
	at net.runelite.launcher.Launcher.main(Launcher.java:68)
```

If y'all need any more info let me know.

**Comment by Kamielvf** [comment]
That crash when disabling hardware acceleration is because you are trying to pass the argument to a launcher version that does not support it. If you want to disable hardware acceleration, download the new launcher from the main website.

There should be an `application.log` file in `~/.runelite/logs` which might contain more info about the application crash you are talking about. Worth checking even if there's no output to terminal (which I would expect.. oh well)

**Comment by utsukami** [comment]
Do you use the window compositor [compton](https://github.com/chjj/compton)? Because I have a similar issue just using a window manager and no desktop environment. It also happens to me with any color customization options in the client (XP Drops, Chat Commands, etc.), not just in the screen markers.

If you do use it, kill compton before attempting to change any color related options and load it back afterwards. Not sure if this will help but I hope it will.

System & Java info:
```
$ uname -r
4.9.95-gentoo

$ cat /etc/gentoo-release
Gentoo Base System release 2.4.1

$ java -version
openjdk version "1.8.0_161"
OpenJDK Runtime Environment (IcedTea 3.7.0) (Gentoo icedtea-3.7.0)
OpenJDK 64-Bit Server VM (build 25.161-b12, mixed mode)
```

**Comment by deathbeam** [comment]
Looks like this is OS issue. Check https://github.com/runelite/runelite/wiki/Troubleshooting-problems-with-the-client if you will be having more trouble in future
