### ISSUE TITLE
Add event for widget text changed

### ISSUE THREAD

**Issue by Toocanzs** [runelite/runelite#3439]
The API is missing a good way to know when a widget's text has changed.

Either an event for widget text changes or maybe a general widget updated event would be very useful

**Comment by Nightfirecat** [comment]
On the one hand, this can be useful sometimes. On the other, most widgets that change text are caused by scripts in which case a script callback could be used to trigger code. This has been discussed in discord and the consensus seems to be that adding this event would cause a lot of event spam, which is probably not good.

**Comment by deathbeam** [comment]
Based on what @Adam- said we do not want this event even though it would be useful also for clue scroll plugin, so closing
