### ISSUE TITLE
Daily Task accounts

### ISSUE THREAD

**Issue by RickertdeH** [runelite/runelite#3503]
I'd like to be able to set reminders for specific accounts. Not all my accounts can collect herb boxes daily but they all do get the messages, same for staves for example. 

Is it possible to set the reminders per OSRS account instead how it is set now?

**Comment by Hydrox6** [comment]
Currently no. The way the config system works does not support multiple accounts at the moment.

Sorry

**Comment by RickertdeH** [comment]
Unfortunate @Hydrox6 ! It would be cool to have something like an account picker when you open RL, and an easy switcher when switching accounts. (Similar to Netflix and quick switching like the google website ecosystem)

**Comment by Hydrox6** [comment]
That would likely be the case once multiple accounts are handled. That, or a config would be loaded depending on the username of the account you log in with, which could make a switching system become part of the Username sync plugin.

**Comment by RickertdeH** [comment]
That would make even more sense. 
However it does seem to do this already for farming patches. I noticed it earlier. If you open up a new client and type in only your username with the RL farming tab open it will load the current statuses without even logging in completely. @Hydrox6

**Comment by Hydrox6** [comment]
The way the farming tracker works is by storing patch data inside your settings.properties file. It stores this along with your username, hence why it knows your patch data when you type in your username. This isn't really feasible for all the settings, as there are ~560 settings (or ~620 if you include farming), and duplicating the data with entries for different usernames would cause the file to balloon in size pretty quickly, causing potentially slower load times.

**Comment by RickertdeH** [comment]
So it currently stores everything locally? Would an alternative be that everything is stored server side along with your RL login? 
Only then the problem is moving it to the server instead of locally..

**Comment by Hydrox6** [comment]
Yeah, farming plugin is entirely local. Have a poke around in your settings file, searching for `farmingTracker`. Lots of encoded gibberish.

The server does store your config, if you log in with the Account plugin that is. The dream would be multiple files, maybe names after each user, that contain the settings for that specific RuneScape account. These files could be easily stored on the server like the current config is now, and since they're separate, loading each would take as long as the current settings take to load.

**Comment by RickertdeH** [comment]
Yeah that sounds like a solution. Would have to find a solution that not everyone can just type in a username and dig up their information. Are you aware of any plans of this in the near future? I'd like to see farming times stores on the server side as well. (struggling when switching between laptop and pc).

**Comment by Hydrox6** [comment]
Well, there wouldn't be information leaks if you had to log in to the correct Google account to actually sync the settings, like you have to do now.
Farming timers should be stored on the cloud with your settings, you just have to log in to RuneLite with your Google account so that the settings sync (if you haven't logged in, it's a little green door at the top right)

**Comment by RickertdeH** [comment]
I might have to check, I should be logged in on both. Thanks for the help.

Does this ticket stay open?

**Comment by Hydrox6** [comment]
Until one of the admins closes it, or you do.
