### ISSUE TITLE
Recolour messages that Jagex has pre-coloured

### ISSUE THREAD

**Issue by Kurama2121** [runelite/runelite#3553]
It would be nice if the color changer pulled in the default colors so it would be easier to change and know what you are changing vs having a guessing game. For example, I cannot seem to change the image red text regardless of the setting I have tried, and since you only get it so rarely it isnt easy to figure it out. Its only when getting certain drops (clues, long bone) and when completing slayer tasks.

<img width="482" alt="screen shot 2018-06-01 at 9 17 58 am" src="https://user-images.githubusercontent.com/39833426/40845927-b73d145c-657d-11e8-9399-d67144ddad4e.png">

**Comment by Hydrox6** [comment]
The problem with a lot of the new text is that the colours are hardcoded. Take that Pink raids text for example: it uses the same message type as those 3 lines of text when you join a Clan Chat (CLAN_CHAT_INFO), just with a manual Pink colour shoved onto it. I'd imagine that Task Complete colour is forcefully recoloured Server (SERVER) messages.

Making the Chat Colour config defaults *look* like the actual defaults would be awesome, and before Adam rewrote it, that was the case (though the new system is much better), but messing with these manually coloured messages isn't something we currently do, and would be an absolute pain.

Never say never though, just give it time.

**Comment by Kurama2121** [comment]
Interesting Hydrox, I know it is a newish feature so I have hope it will get better, being able to change what was provided is already great in itself.

**Comment by Kamielvf** [comment]
If you can change the defaults to respect the default ingame colour that would be great nonetheless @Hydrox6

**Comment by Hydrox6** [comment]
My original config did do that, but one of the things Adam did was make it so that Colors could be unset and not break everything. Notice that a lot of the config values in [net.runelite.client.config.ChatColorConfig](https://github.com/runelite/runelite/blob/master/runelite-client/src/main/java/net/runelite/client/config/ChatColorConfig.java) aren't default. I guess this removes some strain on the config file by not adding all 50 options by default. 

funny side note, the config was only slightly modified from my original one, as the positions still start at 31. This does technically allow me to simply slot in my old Config file with some minor edits (package, etc), but without knowing exactly why Adam did non-default colours, I'm not sure how good of an idea this would be.

Also, if I'm messing with the config, I'm adding support for headings somehow and using them. Adding (transparent) to the end of the strings does not show up well.

**Comment by Kaptn225** [comment]
Hydrox6, do you know whether there's a way to configure the Grand exchange messages ("x/y bought" and "finished buying y")?

**Comment by Alexsuperfly** [comment]
The [Force Recolor](https://github.com/Alexsuperfly/RuneLite-Hub-Plugins/tree/force-recolor) plugin on the hub should be able to do everything you want for this.
