### ISSUE TITLE
Packet Loss Tracker 

### ISSUE THREAD

**Issue by F-RCE** [runelite/runelite#3569]
DDoSing is a big problem in OSRS. Everyone knows about it but we can't really do much.

Being able to view Packet Loss would be a big help when reporting DDoSers to Jagex.

I've tried using programs like Wireshark and Teamspeak (it has a built-in packet loss tracker) but its inconvenient.

The plugin should have a "Simple" and an "Advanced" option. 

The Simple option would just display the % of lost packets at the top right of the screen (close to where the FPS is currently displayed)

The Advanced option would display more information such as size, type, etc..

I know this probably won't happen as its completely unrelated to OSRS or RuneScape in general but thought I'd suggest it anyway.

**Comment by jessebake** [comment]
Packet loss in itself doesn't have a direct correlation with a DDoS attack and I don't think that Jagex would consider packet loss as any type of evidence. Packet loss can be caused (and intentionally simulated) by many things like local network congestion, router QoS, and network testing tools. Adding a feature like this could possibly even increase the amount of false DDoS reports. On low bandwidth internet connections packet loss can even be caused by simple things like downloading larger files.
