### ISSUE TITLE
Slayer task still appears even when it is over

### ISSUE THREAD

**Issue by RandaliciousRS** [runelite/runelite#3631]
- After completing a slayer task the slayer plugin does not recognize this and still appears with the overlay that you have x amount left to kill https://i.imgur.com/HfBzCiV.png

<details>
 <summary>https://i.imgur.com/HfBzCiV.png</summary>
 
 ```
  https://i.imgur.com/HfBzCiV.png
 ```
</details>

**Comment by DannysPVM** [comment]
Thanks for reporting the issue Randalicious, I'll take a look at that real quick. Seems like it should be a quick fix.

**Comment by evansloan** [comment]
I've had this same issue with lizardmen.

I believe it was because I had left the area while my cannon was still firing and killing the lizardmen. Since I wasn't in the area I don't think the client was tracking those lizardmen that were killed, which caused the plugin to fall behind. Right clicking the slayer helm and selecting "check" re-synced the plugin.

**Comment by edgarsaurus** [comment]
I've had the opposite issue where the slayer counter tells me I'm at 0 even though my task isn't over yet. I still had 1 hellhound left.

**Comment by sethtroll** [comment]
This issue was probably caused due to (I'm assuming you were using a cannon)slayer XP drops being combined when multiple of the same NPC dies on the same tick. Same issue occurs when you are barraging a slayer task. Related to #1046

**Comment by deathbeam** [comment]
This looks like duplicate
