### ISSUE TITLE
Feature Request: The ability to play any music track even it's not unlocked

### ISSUE THREAD

**Issue by CypherNL** [runelite/runelite#3665]
**Is your feature request related to a problem? Please describe.**
Not really a problem. But i'd like to be able to play the Theathre of Blood tracks without unlocking them myself since i don't play this game anymore.

**Describe the solution you'd like**
The feature to override the ID of the tracks that the music player is currently playing. So that the track you've requested will be played.

**Describe alternatives you've considered**
Maybe green text every track and let that track play even it's locked. Make sure that this is client-side so you can't unlock the Music Cape due to this. (Don't think that's going to happen but you never know).

**Additional context**
With the Theatre of Blood updates, it will contain some new instruments (So far the opera voice choirs is confirmed by myself) that my client to play new OSRS tracks doesn't have unless i can get the latest client to work for myself although i'm not a coder. This function would also be nice for the players that just want to play the tracks they can't unlock due to high requirements.

**Comment by devLotto** [comment]
The soundtrack ID for a song isn't known before it's unlocked and played, unless you listen to all of them in the cache to "bruteforce" which ID a track has. This means we wouldn't be able to let you play brand new tracks, because we wouldn't have found the ID yet.

In due time these new tracks will probably appear on YouTube or the OSRS wiki, so I'd just wait for that. OR you can dump the tracks using https://github.com/runelite/runelite/blob/master/cache/src/test/java/net/runelite/cache/TrackDumperTest.java and then try to find the ones you're looking for.

**Comment by Melvinkooi** [comment]
The MIDI files aren't a problem for me since i can download the full cache for myself. What's the problem for me is that the music player contains new instruments that i can't access.
Also for IDs. There's an user that lists every track ID and updates it quite occasionally. 
https://oldschoolrunescape.wikia.com/wiki/User:RS_Orchestra (Scroll down for the list)

Also, Jagex fills the nearly empty slots for the new music tracks. For example ID 585 near 584 - The Dark Beast Sotetseg is empty right now. When an update arrives for a new track, ID 585 will be used for the new track.

Honestly, i wouldn't mind if you need to input the track ID you want to play and redirect the url above for the tracklist and a note that you need the fully downloaded cache. Of course it's not the most friendly solution. But for me it's good enough.

**Comment by trelkins3** [comment]
The theater of blood OST is now available on music streaming platforms, if that helps at all :P 

I feel like in terms of general usage the fact that this will let you access content you haven't unlocked is maybe questionable.

**Comment by CypherNL** [comment]
Honestly I'm not really needing this feature anymore since I've pretty much have the ability to listen to every Old School RuneScape track through other means. Not to mention Jagex is releasing more OSTs to music streaming platforms makes this issue redundant for me.
