### ISSUE TITLE
Death Marker doesn't dissappear if logged out and back in after the allotted time.

### ISSUE THREAD

**Issue by nmq12** [runelite/runelite#3743]
Died at GE W355 yesterday. Played on a different world for longer than an hour. Logged back into the same world today and death marker still present.

![image](https://user-images.githubusercontent.com/5819477/41243591-89509942-6d70-11e8-8456-aa3855fe100d.png)

Marker also shows up on world map.

**Comment by DannysPVM** [comment]
I'm not entirely sure why the arrow remained there after the 1 hour reclaim time. If the player has died and is on the world that they died on, it should have been cleared on the very first tick upon log in. Was it only the arrow that was still there? Did you check to see if the world map marker was still there? I've done some work on the plugin recently to remove the arrow altogether due to a different reported issue, instead the plugin will now use a tile highlight (the arrow interferes with BH arrow and the clue scroll plugin arrow, which is not ideal). If the arrow is the only remaining marker in the plugin that was an issue, my PR #3715 should fix that, but if it doesn't I'll look into it again. Thank you for taking the time to report the issue!

As a side note, If that ever happens again, you can also clear all of the death indicator markers with the 'reset' button in the config panel.

**Comment by nmq12** [comment]
There was a map marker along with the arrow. It went away after I reset the client again.

**Comment by DannysPVM** [comment]
I'll take another look into this, thank you for the information man.

**Comment by DannysPVM** [comment]
I've been able to recreate your issue and found a different issue in the process. Thank you for reporting it @nmq12. I'll see what I can do.

**Comment by LateNightCasuals** [comment]
I think this is possibly a related issue - I sui-d while training prayer days/weeks ago and the marker is still on the world map.

![image](https://user-images.githubusercontent.com/36332753/81729665-3ee4d700-9484-11ea-9140-d3eb96bb117e.png)

**Comment by makingcomment** [comment]
The Death Indicator plugin no longer exists.
