### ISSUE TITLE
DPS Meter (Similar to WoW's Recount)

### ISSUE THREAD

**Issue by shermaza** [runelite/runelite#3894]
**Describe the solution you'd like**
Add a plugin panel similar to WoW's _recount_ to track damage done per player in your clan chat. This can be reset via a plugin-panel.

**Describe alternatives you've considered**
Instead of clan chat, it could be by raid group as that's most likely where it would be used. However, with the clan chat, other group PvM like GWD or corp could be included.

**Additional context**
 Image examples from Recount's web page https://www.wowace.com/projects/recount/images - the latter screens are WoW specific, but the first one shows each player where their "bar" is a % full based on DPS, and their info is displayed as "username totalDamage (damagePerSecond %percentDamageDone)"

**Comment by Jalopyy** [comment]
Only if we can add gearscore too

**Comment by kulershk** [comment]
I dont think so it's possible, do jagex say who did how much damage? I think we only have hitsplat event who took damage not who dealt.

**Comment by DeadeyeOo** [comment]
I start this already and used the constitution EXP drop to determine the damage of your next attack. Then calculate DPS based on how long your have been in combat. If you want I could clean it up and submit for review. 
![untitled](https://user-images.githubusercontent.com/37055804/41640262-f753410a-7415-11e8-9228-932f5b4e35ae.png)

**Comment by shermaza** [comment]
I was watching @WooxSolo's stream today, it seems like he has a prototype for this on his client. He may have more input about how feasible it is for a full plugin.

**Comment by CustardGod** [comment]
I believe Woox's version is a total damage plugin, not DPS. Granted I doubt it would be hard to change it to a DPS plugin

**Comment by DeadeyeOo** [comment]
Oh yea I just checked it out in his stream, I do not know how he is calculating dmg for nearby players. Pretty awesome actually.
![capture](https://user-images.githubusercontent.com/37055804/41685161-77270f82-7494-11e8-9644-9b6a26a7d821.PNG)

**Comment by CustardGod** [comment]
I believe he's re-written the animation api to allow him to find who does what damaged based on when their animation goes off and when the hitsplat shows up. Decimals because multiple hitsplats can show at the same time so the damage is averaged out between the players who did the damage

**Comment by WooxSolo** [comment]
I do have a prototype for this yes. It works on all players nearby by waiting for the attack animation and then calculating the amount of ticks until the damage should appear and then counting the damage from the hitsplat. It is only an estimator for now though, since there is a problem with this approach.

When multiple people attack on the same tick, and the hitsplat appears on the same tick, there doesn't seem to be a convenient way to find out which hitsplat was done by which player. The position of the hitsplat seems to be determined by server pid. I have found out that server pid can be determined by the projectiles created by ranged and magic attacks (except ice blitz and blood barrage as they do not create projectiles), so it may be feasible to solve the problem for ranged and mage, but I have not found a fully working solution for melee.

It would be possible to calculate your own dps though, by looking at xp drops, which would also mean you can calculate dps of someone else in a duo. But it worldn't be 100% accurate on other people when there's more than 2 of you.

**Comment by Pashweetie** [comment]
If you know what your damage you hit was, you can then at least reduce the number of options of what player did what hit splat, in other words if two players attack on the same tick you can at least then determine who dealt which damage. Not a great solution but a quick one.

**Comment by Pashweetie** [comment]
However the hitsplats can be inaccurate as well in cases where blowpipes or the sycthe is used since some hitsplats are hidden from view (not sure if you can grab those with the API)

**Comment by extermistmonk** [comment]
@DeadeyeOo Ive been trying to implement this myself but I cant figure out how to accurately calculate damage from HP exp drops. Wouldn't you have to know your exact decimal HP exp for it to be accurate, given than each damage you do gives 1.33 exp?

**Comment by Pashweetie** [comment]
Maybe you should instead base it off of the style being used

**Comment by DeadeyeOo** [comment]
I used (int)Math.Round(HPExpDrop / 1.33) since runescape rounds based on 0.5. Attack style introduces alot of complexity I didn't feel like dealing with.

**Comment by Pashweetie** [comment]
We already have a plugin that determines your current attack-style you could use that code to send info to your code

**Comment by shermaza** [comment]
The personal hitsplat re-color was released today - maybe the update that makes this feasible?

**Comment by Adam-** [comment]
Yes, this becomes fairly easy to do now.

**Comment by abextm** [comment]
Added in 023860f928bac02a9b6006bffdd147aca1f9d9b8
