### ISSUE TITLE
Add shift-click menu swapping to spellbook

### ISSUE THREAD

**Issue by Jalopyy** [runelite/runelite#3974]
IE click = tele to GE, shift-click = varrock center

**Comment by deathbeam** [comment]
https://github.com/runelite/runelite/wiki/Rejected-or-Rolled-Back-Features

**Comment by honeyhoney** [comment]
Is this really the same as below? (I assume this is why you closed this request)
```Spellbook Re-ordering: Other 3rd party clients do not have this feature and it failed a Jagex poll (see #1038)```

As far as I know this is regarding the menu options such as:
![image](https://user-images.githubusercontent.com/11140337/41810307-51821580-76f4-11e8-9cf0-b2fbdbc08e55.png)
Instead of having to configure which one is left click (i.e. Varrock or Grand Exchange) you would simply be able to have left click Varrock and shift+left click Grand Exchange.

**Comment by Adam-** [comment]
Added in #10039
