### ISSUE TITLE
ConfigPlugin sometimes doesn't update to add buttons for new live-loaded plugins

### ISSUE THREAD

**Issue by SomeoneWithAnInternetConnection** [runelite/runelite#414]
I'm developing a plugin, and after rebuilding and reloading it, there's no more button in the config panel for it. Restarting runelite causes a button to show up again, at least until I rebuild the plugin

**Comment by SomeoneWithAnInternetConnection** [comment]
Just noticed that the button reappeared, so there's probably something more complicated going on :/

**Comment by SomeoneWithAnInternetConnection** [comment]
Adding this as a comment here since it seems like it's probably part of the same problem: I've just *unloaded* an external plugin (by removing it from `~/.runelite/plugins`) but the config panel still has a button for now-unloaded plugin

**Comment by Abextm** [comment]
This was probably introduced in #386.

**Comment by Abextm** [comment]
@deathbeam You are a lot more familiar with this code than I am.

The PluginWatcher/PluginManager racing with the Swing Thread because `startPlugin` (which posts the `PluginChanged` event) runs before the plugin is added to the `PluginManager`. Is there any reason the call to `add` can't be moved to before the event being posted in `startPlugin`?

**Comment by deathbeam** [comment]
As the support for external plugins was removed, this issue is no longer relevant.
