### ISSUE TITLE
dodgy necklace issue

### ISSUE THREAD

**Issue by digdoge69** [runelite/runelite#4273]
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/issues)

| Question    | Answer
| ------------| ---------------
| Java Version | x.y.z
| Operating System | e.g. Ubuntu/Windows/MacOS

if wearing a dodgy necklace while having multiple in your inventory, runelite displays that they all have the same number of charges as the one equipped

**Comment by colindjk** [comment]
That is because they all have the same number of charges as the one equipped, so to speak.

The way the Dodgy necklace and other enchanted jewelry works (i.e. ring of forging) is that there's a global variable to determine the total charges remaining that's based on the _player_ rather than the actual piece of jewelry.

You'll notice you can break the jewelry to reset your charges for your next piece; this can be helpful when you're on your last charge of a dodgy necklace and want to AFK for a bit without worry about the necklace inconveniently turning to dust. More info can be found [here](http://oldschoolrunescape.wikia.com/wiki/Dodgy_necklace).

**Comment by colindjk** [comment]
@digdoge69 Also, could you close this issue, please?
