### ISSUE TITLE
Xp Tracker: xp/hr is wrong

### ISSUE THREAD

**Issue by MagicfTail** [runelite/runelite#4452]
As of the latest release (1.4.8.0/1) the xp/hr of each individual skill is calculated from when xp was gained in any skill, instead of from when xp was gained in that particular skill.

Example: I log in and train hunter for 2 hours. I then stop and train herblore for 1 hours, gaining 300k xp. My herblore xp/hr should now be 300k/hr, but is instead 100k/hr

**Comment by LeviSchuck** [comment]
As discussed in discord, the problem is that skills that are NOT being trained are counting time.
The previous behavior was that time only got counted after the first XP event per that skill.
This was in fact introduced in the pausing pr #4114 

I believe I have a fix and I'm going to test this with an hour of play before I make a PR. 

```
if (xpGained <= 0)
{
	return;
}
```
is pretty much my fix inside the tick function on `XpStateSingle`
