### ISSUE TITLE
Add 2006 and 2010/2011 Game sprites

### ISSUE THREAD

**Issue by alex-vincent** [runelite/runelite#457]
I know OSB has these as well as konduit. But I don't think they have it in resizable at least the way I remember it back in 2011
Here is a screenshot example of what I mean:
![https://i.imgur.com/1WVPdgo.jpg](https://i.imgur.com/1WVPdgo.jpg)

**Comment by Viizva** [comment]
I was told to post here didn't realize it was already open!

Can we please get a 2006 interface? I am sure a lot of people would love it and its one thing that I enjoy using that Runelite doesn't have yet.

A lot of the assets were made by a reddit user and posted here - https://www.reddit.com/r/2007scape/comments/54kbbw/2005_era_interface_for_old_school_assets_made/

**Comment by devLotto** [comment]
The assets he made cannot be used, because they are not adapted to the OSRS gameframe. 

For instance, for some reason he made the margin from the right-hand side of the gameframe to the start of the inventory bigger:

His reference: https://i.imgur.com/dOo2xpp.png
His rework: https://i.imgur.com/RmXKjCR.png

Additionally, he did not supply the raw sprites for the interfaces, but rather slammed them together into one image, which makes it annoying to sit and extract all sprites from his images.

**Comment by raqes** [comment]
Finished the widget moving for the 2006 gameframe and added a 2010 skin aswell to Lotto's plugin. Current progress: https://imgur.com/a/y9qJ0BH
https://github.com/raqes/runelite/tree/uicustomizer

**Comment by Adam-** [comment]
Added in #2991
