### ISSUE TITLE
Different Target color for superior slayer monsters

### ISSUE THREAD

**Issue by CrossBowKill** [runelite/runelite#4756]
Would be a nice addition to the slayer plugin especially for abyssal demons where its sometimes difficult to spot the superior in the slayer tower.

**Comment by forsco** [comment]
I personally don't use notifications so I can also understand why it would be useful if utilizing the slayer plugin overlays on NPC's.

**Comment by Gamer1120** [comment]
This is 100% necessary IMO. I just nearly lost my Hardcore status (12 hp before I panic ectophiald) due to not being able to distinguish a Greater Abyssal Demon from a regular one and not putting Protect from Melee up. For now, I'll manually highlight all superiors with NPC Indicators, but I think this should be added as a default.

**Comment by Nightfirecat** [comment]
Duplicate of #1960
