### ISSUE TITLE
Mouse Highlighting: Tooltips don't display for widget actions

### ISSUE THREAD

**Issue by SomeoneWithAnInternetConnection** [runelite/runelite#490]
Pointed out by `@Tyler#5378` in the discord:
Aside from the item stack widget, we don't show a tooltip when some widget has a left click action. The panel switch buttons are the most prominent and easily-accessible example of this, but it'd be nice to show a tooltip for widget-triggered actions in general. 

For comparison's sake hovering over one of the panel-change buttons in Konduit looks like this
![Konduit panel tooltip](https://user-images.githubusercontent.com/34518321/35523638-4dc10ad8-04ed-11e8-8809-c0527c30c16e.png)

**Comment by Sethtroll** [comment]
So this happens because those menu options have no target

https://github.com/runelite/runelite/blob/6239baaa9eeac8924cb07e24ef3ca1453f613076/runelite-client/src/main/java/net/runelite/client/plugins/mousehighlight/MouseHighlightOverlay.java#L72-L75

Not sure what the repercussions of removing that empty check would bring though.

**Comment by deathbeam** [comment]
Probably doing something like this:
```diff
-if (target.isEmpty()) {
+if (Strings.isNullOrEmpty(option)) {
  return null;
}
```

and

```diff
-tooltipManager.add(new Tooltip(option + " " + target));
+tooltipManager.add(new Tooltip(option + Strings.isNullOrEmpty(target) ? "" : " " + target));
```

should work ™️
