### ISSUE TITLE
Fishing, MLM and woodcutting overlays showing duplicate informations

### ISSUE THREAD

**Issue by deathbeam** [runelite/runelite#501]
Currently, fishing, woodcutting and motherlode mine plugin overlays track logs/fish/pay-dirt cut/fished/mined and also the actions/hr. These informations are now obsolete, because exactly same informations are now present in the XP tracker.

**Comment by SomeoneWithAnInternetConnection** [comment]
I just mentioned this on #569, but figured I ought to leave a comment here as well, just in case: the MLM info isn't (and shouldn't be) duplicated by the XP tracker, since the tracker is tracking "XP Drops(/hr)" while the MLM overlay is showing "**paydirt**(/hr)". These two things aren't the same, because there's an xp drop from washing the dirt as well as from mining it.

**Comment by deathbeam** [comment]
Fixed in #569

**Comment by zeruth** [comment]
This isn't an "issue" much as it is personal preference. and it wasn't "fixed". This need to be reopened until a proper toggle is implemented  Or only show it while the sidebar is closed.

**Comment by deathbeam** [comment]
1st: It was enhancement
2nd: The merge made this issue "solved" because it was talking about removing obsolete informations that are no longer present

If the merge would be reverted, this issue can be reopened. If not, making new issue to display the informations while panel is closed would be correct follow-up. Or, I guess, you can open it also right now, and then we can track possible solutions, including the possible revert there.
