### ISSUE TITLE
Extend draw distance in zoom plugin

### ISSUE THREAD

**Issue by Adam-** [runelite/runelite#513]
```
[3:24 PM] Winnetou: @Adam ee.bf
[3:24 PM] Winnetou: set all to true
[3:24 PM] Winnetou: max render distance
```
Rev 162.

**Comment by deathbeam** [comment]
Make it toggle if added as well please, for low end PC users

**Comment by deathbeam** [comment]
For anyone planning to mess with this, I tried doing it (unsuccesfully) based on the discord message, here are the results:

* ee in current deobed code can only mean method class33#method340 that returns RenderOverview
* RenderOverview#bf will be then RenderOverview#method5859
* method5859 is modifying HashSet field3949

What I did is that I added hook to end of the method5859 and iterated through it in subscriber and replaced all values with "int 1". This did nothing, because method5859 is never called. So I tried running the same logic for replacing the RenderOverview.field3949 with all 1s in GameTIck hook, do not worked, because field3949 size is always 0, so it is never populated.

I gave up after this and deleted all of my changed code, so gl to anyone who tries to do this, hopefully this comment will be helpful :smile:

**Comment by Abextm** [comment]
So I was looking into this, `ee.bf` is `renderArea`, which is set by `visibilityMaps`. When I set all values of these to true it just makes the are typically under the camera's viewport render. Unless the zoom plugin is making these tiles significantly more visible, changing this won't do much other than drop your framerate.

**Comment by Yoone** [comment]
Is this issue still live? That'd be an awesome contribution.

**Comment by Adam-** [comment]
Superseded by #1165
