### ISSUE TITLE
Bondfunding

### ISSUE THREAD

**Issue by Assadhere** [runelite/runelite#5195]
Hey

Something nice to add to the client would be a "Bondfunds calculator". A list where u can type add items you looted, calculating how much % you still need to get in order to get a full 100% bond. (Prices set by GE value/Osbuddy value)

It's a little help for the f2p players that need a bond and are saving up for a bond.

**Comment by deathbeam** [comment]
We have multiple ways already to achieve this:
1. Bank value plugin
2. Simple examine of your coin stack then typing !price old school bond/search it in GE sidebar/in-game interface

So mostly bank value plugin together with one of the ways to check bond price should do the job.

Otherwise duplicate of https://github.com/runelite/runelite/issues/821
