### ISSUE TITLE
Clue plugin indicates wrong npc with identical name

### ISSUE THREAD

**Issue by merlindima** [runelite/runelite#5231]
Elite clue "Stop Crying!. Talk to the head"
Wrong head mourner highlighted in client.
This is correct hear mourner: http://oldschoolrunescape.wikia.com/wiki/Head_mourner
Highlighted one is currently: http://oldschoolrunescape.wikia.com/wiki/Head_mourner_(West_Ardougne)

In the npc id they are slightly different HEAD_MOURNER_5310 and HEAD_MOURNER_4258

Windows 10
RuneLite 1.4.15

**Comment by zephyrdark** [comment]
Location of issue:

https://github.com/runelite/runelite/blob/d3f24e4621d7effcc116bea875d384d427660f86/runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/CrypticClue.java#L78

**Comment by geeksmarter** [comment]
Confirming that this is still an issue. This will place an indicator over the NPC in West Ardougne church when it's looking for the one in the basement of the headquarters.

**Comment by microtavor5** [comment]
I just encountered this issue as well.

![image](https://user-images.githubusercontent.com/7853505/145893643-609dc6da-0057-4dfb-84b8-c571a6a8e270.png)

The issue appears to be cause by multiple NPCs having the same name. A possible solution would be to change the clues to use an array of valid NPC IDs instead of the name. That's a whole lot of work, and even more testing to make sure that it all got converted correctly.. If there no objections to that line of changes I might add it to my backburner, not that I have time in general

**Comment by Gamer1120** [comment]
Also happens with Bartender clues:
![image](https://user-images.githubusercontent.com/9074448/168415323-cf0cfe0c-0e4e-4cdb-b799-047d7047c7ea.png)

**Comment by Adam-** [comment]
fixed in 3084c56929b0f0e19e66366c2a6242d2157ec6e6
