### ISSUE TITLE
Entity hider for nechryaels "Death spawn"

### ISSUE THREAD

**Issue by S7venlives** [runelite/runelite#5238]
Always frustrated when I attack them 5 times before I manage to loot something or mouse doubeclicks on loot and attacks them instead

Able to hide them in entity hider. Alternative solution would be making their right click option.

Alternative solution would be making their right click option.

Good QOL cause nobody wants to attack them.

Kind regards,
Nech killer
![image](https://user-images.githubusercontent.com/39206427/44928154-3d7a8600-ad57-11e8-83e9-89390e9a9313.png)

**Comment by S7venlives** [comment]
![image](https://user-images.githubusercontent.com/39206427/44928420-22f4dc80-ad58-11e8-80b1-020f56d020b1.png)
Bloody hate them

**Comment by S7venlives** [comment]
![image](https://user-images.githubusercontent.com/39206427/44928774-30f72d00-ad59-11e8-88f9-1a2a912ab449.png)
Cant even see the Nechryael

**Comment by 8bitslacker** [comment]
any update on this

**Comment by Felanbird** [comment]
At some point the `Menu Entry Swapper` plugin got the ability to switch the left-click option to walk-here instead of attack, so the wanted functionality of this issue, which is being unable to misclick death spawns, is possible.
![image](https://github.com/runelite/runelite/assets/41973452/59d59413-ba44-441e-a699-4d355f8fb715)
