### ISSUE TITLE
Player indicator drawing way above player

### ISSUE THREAD

**Issue by Kamielvf** [runelite/runelite#524]
Sometimes (during some animations?) the player indicator gets drawn way above the player. Possibly setting a max height would fix this easily.

![image](https://user-images.githubusercontent.com/35824069/35766657-644a3192-08dc-11e8-9c72-4b2412a196dc.png)

**Comment by SomeoneWithAnInternetConnection** [comment]
This shows up with NPCs as well. I've seen it happening with someone who was splashing a seagull in port sarim (both the seagull, and the person's height were jumping way up) and I believe deathbeam's mentioned it happening during some fletching animations. Others have spotted it happening with fishing spots (which are actually NPCs) when two on the same tile.

**Comment by SomeoneWithAnInternetConnection** [comment]
That'd probably make it less bad at least (except maybe for really tall creatures? How many of those exist?), but it'd be kind of nice to figure out the actual reason for it happening.

**Comment by UniquePassive** [comment]
I would like to believe that this happens when your friend is not being rendered, as they are inside a pile of people. My theory is that the modelHeight of your friend will be the default of 1000 in that case, which makes it so the text is rendered way above where it should be.

I expect a similar "bug" to happen when the artists have added an invisible vertex as to extend the clickbox, as that still has the potential to change the modelHeight.

A potential solution might be to assume the model height for players as a constant, and this would be the easiest solution. A harder solution could be to establish when an entity is obscured/invisible, and in that case calculate the model height ourselves.

**Comment by SomeoneWithAnInternetConnection** [comment]
If there's only a single vertex causing the animation weirdness, then a not-so-hard variation on the harder solution might be to use the highest triangle in the model
