### ISSUE TITLE
XP/H sample time too short

### ISSUE THREAD

**Issue by sstara** [runelite/runelite#5255]
**Is your feature request related to a problem? Please describe.**
It is frustrating when let's say my XP/H while cooking is 200k, then I bank and it drops to 198k for example and when I continue cooking it hops back to 200k.

**Describe the solution you'd like**
An option to choose the average XP/H from a certain period of time (e.g. a full inv of cooking, banking and runnin back to the range) and count the XP/H from that. Meaning you could choose e.g. 2 minute samples at a time and after said 2 minutes the XP/H counter would update.

**Describe alternatives you've considered**
Make it an option to round the avg. XP/H rates to .5k, 1k, 5k, etc.

Love what you're doing here though, keep up the good work! Thanks

**Comment by deathbeam** [comment]
You can already auto-pause after in XP tracker settings, use that

**Comment by forsco** [comment]
Running to the bank is suppose to count towards active time, after all you're not logged out and it reflects true xp/h for methods where you do need to bank.

I see no benefit in adding what you've suggested as it wouldn't provide true experience rates for the situation you've just stated.

**Comment by sstara** [comment]
Exactly, forsco. I agree with your first paragraph. I don't know who you were talking to in your second, though, as that wasn't at all what I meant.

I don't want the counter to pause when banking because of reasons you yourself stated, but rather for the counter to just take longer sample times during actions to prevent the numbers from going back and forth when banking and when gaining XP, but that still always rounds to the same XP/H reading.

**Comment by deathbeam** [comment]
I mean just dont look at the XP/hr then, idk.

**Comment by Abextm** [comment]
So you want the displayed XP rate to be averaged over a longer period of time?

**Comment by osrsexo** [comment]
the exp / hr tracker is easily influenceable if there is only a short period of time to track over.

As you grind for hours, the tracker will be much more stable and will also change less often because it is harder to influence the hours of data with the present.

What I could understand, is that you would want a tracker that only tracks lets say the past 1 or 2 hours so that you have a more reliable exp/hr over shorter periods of time rather than the whole session/day.
This would also be more effective than restarting the client and start over from 0 again. (this would actually be a feature i'd like myself aswell)

**Comment by sstara** [comment]
Could the other "solution", reading rounding, also be implemented? Would make it look prettier and less flashy especially when training for shorter periods of time.
