### ISSUE TITLE
Make Metronome work while game sounds are muted.

### ISSUE THREAD

**Issue by ShaunDreclin** [runelite/runelite#530]
The metronome isn't very helpful for prayer flicking when it's completely drowned out by the sounds of all your prayers turning on and off!

Possible solutions:
Add a system for playing external wav/mp3 files
Add a 4th audio category to put RuneLite sounds in
Change the Metronome to use area sounds to allow sound effects to be muted.

**Comment by Kamielvf** [comment]
When using area sounds you enable some other souns you definitely don't wanna hear (bandos pet lmao)

**Comment by ShaunDreclin** [comment]
Haha yeah it's definitely not ideal.

**Comment by UniquePassive** [comment]
Maybe it's possible to force the audio engine to play sounds queued by us even when audio is muted.

**Comment by SomeoneWithAnInternetConnection** [comment]
It's very likely that I missed something while I was digging through that code, but it seemed as though there were 2.5 kinds of audio:
* Music -- The first slider, and almost completely separate from the sfx stuff
 * Local SFX -- The second slider, and how the metronome currently plays sounds
 * Ambient SFX -- The third slider. These seem to just be sfx that have a position, rather than happening at (0,0) with range 0

The way we're currently queuing up SFX supports local and ambient (I think. We're able to play sounds as though they happened on a different tile at the very least), but doesn't really offer any way to bypass the built-in volume control stuff, since we're just putting another sound in the queue to be played. I think there may have been some mixer/volume control stuff in the client, but currently, we're upstream from that, and only get to pass in an ID, an (x,y), and a range

**Comment by 14016036** [comment]
as a guy trying to learn to prayer flick, and seeing as this is a pretty old topic, i'd like to spring some life into this and ask if a talented developer for runelite could take a look at implementing a change for this plugin <3

**Comment by RiskAGS** [comment]
what is even the solution to this? i'm confused...

**Comment by DecemAdUnum** [comment]
Has any progress been made to this? I might try my hand at it but it will be difficult with my minimal to no knowledge of the code base.
