### ISSUE TITLE
XP Globe tooltips are covered up by the interface when snapped to the right corner

### ISSUE THREAD

**Issue by brewsky93** [runelite/runelite#5419]
**Describe the bug**
When the XP globes are snapped to the right corner, the tooltips are covered by the interface in both fixed and resizable modes. See screenshots below:

![2018-09-09_21-35-24](https://user-images.githubusercontent.com/43124636/45273570-f25c2380-b478-11e8-81cf-780e6fb8daff.png)
![2018-09-09_21-35-43](https://user-images.githubusercontent.com/43124636/45273574-f5571400-b478-11e8-831d-601f820a56cd.png)

**To Reproduce**
Refer to screenshots above.

**Expected behavior**
It would be preferred if the tooltips displayed over the interface.

**Comment by deathbeam** [comment]
Well the problem is that XP globes tooltips are not real tooltips and so are tied to same layer as XP globes are. Moving XP globes to different layer is not acceptable, so maybe ugly solution would be to crewate another overlay that will just draw tooltips and calculate dimensions for XP globes to show the tooltips but draw nothing for them

**Comment by FearrMe** [comment]
Same thing happens on the edge of the screen in resizable.

**Comment by Adam-** [comment]
This seems to no longer happen for unknown reasons.
