### ISSUE TITLE
Runecrafting pouch essence counter is not working anymore

### ISSUE THREAD

**Issue by deathbeam** [runelite/runelite#5667]
Based on discussion in Discord, the varbits that held the data for stored essence are either gone or changed.

**Comment by Adam-** [comment]
It sounds like they are gone. I would probably rather remove this feature then than trying to track it based on inventory changes.

**Comment by distillateking** [comment]
Yeah I hope not also. This is probably my most favorite thing to use on runelite. Its very helpful makes runecrafting a lot easier for me :)

**Comment by CakeWizard** [comment]
> It sounds like they are gone. I would probably rather remove this feature then than trying to track it based on inventory changes.

I'm not a programmer by any means, but rather than track it by inventory changes could you not just hard code it to display the standard amount of essence each pouch holds when the fill option is clicked, and then reset that when the empty option is clicked? I foresee two issues with this approach, but removing the feature entirely will be sad.

What do you believe would be the most challenging part of tracking it by inventory changes by the way? From someone with a little bit of programming knowledge it sounds like an annoying problem to handle.

**Comment by bigmemes420** [comment]
Instead of showing the number of essence in the pouch, perhaps just show whether or not it has essence in it.
