### ISSUE TITLE
HQX Graphics Filtering.

### ISSUE THREAD

**Issue by talestyrone** [runelite/runelite#5781]
Sometimes, due to OSRS having a small resolution it hurts to look at. (Maybe just me because I have sight problems)

**Describe the solution you'd like**
HQX Graphics Filtering upscales pixels creating smooth edges.

**Describe alternatives you've considered**
I only know of HQX filters, but anything else that smoothens pixels would be great.

https://i.redd.it/64ao8l1vrzp11.png

This screenshot was taken when using the magnifier tool in Win10 that upscales pixels to not create distorted images/stretched pixels.

**Comment by raiyni** [comment]
You can used fixed integer scaling in fixed mode.

**Comment by devLotto** [comment]
I think HQX is too slow to maintain a good framerate.

**Comment by deathbeam** [comment]
As @devLotto said, it would most likely be unusable on bigger screens, and so closing

**Comment by logarrhythmic** [comment]
Bicubic might be okay to add too, since it's noticeably sharper than bilinear (I tested by setting non-GPU stretched mode to use bicubic filtering (it lagged a lot)). Currently the scaling is just done using a texture parameter with two options, nearest or linear, but changing the logic to support adding this upscaling shader would make bicubic pretty easy to implement too, or vice versa.

**Comment by chiragbharadwaj** [comment]
Was wondering if anyone has taken a look at this since last November.  If not, I was wondering if I could take a crack at implementing HQX/XBR or even a bicubic upscaling filter as mentioned above.  I would really like to see this in the game because currently the Stretched Mode seems to use a nearest neighbors sampling to upscale, and as a consequence it looks very jagged when played with 2x Integer Scaling. I think HQX or XBR will do a better job of rounding out corners.

**Comment by deathbeam** [comment]
@chiragbharadwaj nope, I dont think anyone was looking at this, so if you want to, feel free to try and implement it

**Comment by devLotto** [comment]
xBR was added in 66fac018eb2ddec2d0e9c30ac38b2780c040a2a6, closing.
