### ISSUE TITLE
Opponent info health off by 1

### ISSUE THREAD

**Issue by ar1a** [runelite/runelite#58]
When an opponent is damaged, the health will be 1 lower than it actually is. This results in the opponent info showing 0/maxhp when in reality the opponent is 1hp. I have tested this on cows, but I had noticed it before.

**Comment by Snorflake** [comment]
Can experience this with cows but not minotaurs. Wolves seem to just be wrong entirely.

**Comment by riukuzaki** [comment]
The health isn't necessarily off by 1. The data used to populate health values is wrong at times in npc_health.json.

The current way health is obtained is by doing a lookup by name + level in npc_health.json and then taking the ratio of the the NPC health bar's pixel width to the max health bar pixel width. Since this is only 30 pixels wide, there are bound to be off-by-a-few issues.

**Comment by Noremac201** [comment]
To add to this, this was changed by JaGeX for the Last Man Standing so clients couldn't have an unfair advantage.

**Comment by deathbeam** [comment]
So is this issue or this can be closed as won't fix?

**Comment by zeruth** [comment]
Probably won't ever be fixed. As far as accuracy goes there will always be a margin of error in converting  x/30 into real health values.

It could be pretty accurate if it assumed all creatures were attacked at full health. and then count the damage you do and account for the health tick. but too many variables like other players attacking the same creature, or attacking creatures that were already damaged. This is probably as good as it will get.

**Comment by IanWONeill** [comment]
https://github.com/runelite/runelite/issues/1621 this suggestion could help with this.
