### ISSUE TITLE
Loot Tracker: Add toggle to show High Alch price instead of GE

### ISSUE THREAD

**Issue by raiyni** [runelite/runelite#5813]
**Is your feature request related to a problem? Please describe.**
Some players don't particularly care about GE price (ie. ironmen).

**Comment by forsco** [comment]
Well I mean, it would be a toggle. Just default to false?

**Comment by Brodan** [comment]
> Well I mean, it would be a toggle. Just default to false?

it's a _little_ bit more than that, theres no config for the loottracker plugin right, so that would need to be added, and then look tracker just needs to get the high alc price instead of GE price which im not sure how to do but can't be hard.

all in all, probably pretty trivial for someone who's worked with runelite a lot, but for someone new to the project (like myself) seems like a good PR to work on. i'd love to keep working on it unless someone sneaks in and does it in like 5 minutes before i get around to finishing it :(

**Comment by psikoi** [comment]
I'm already working on it..

**Comment by cohen990** [comment]
what happened with this?
