### ISSUE TITLE
Loot Tracker: Track Wintertodt supply crates

### ISSUE THREAD

**Issue by AverageHumanoid** [runelite/runelite#5824]
Title

**Comment by TylerNichols** [comment]
I am working on this and should be submitting a PR today

**Comment by StudlySpud** [comment]
This never got merged, did it?

**Comment by TylerNichols** [comment]
@StudlySpud Nope, it was fully functional but there were some concerns about the loot tracker not being used for this kind of stuff (but I think it's a boss...) and also some people hated the code or something like that. Feel free to use/take/fix/etc and create your own PR!

**Comment by Adam-** [comment]
We can probably revisit this. We have a lot of non-boss wt-crate type things now such as all of the loot chests (brimstone/larrans etc).

**Comment by Adam-** [comment]
I've just been told that the reason we didn't add this originally was because you can open multiple crates per tick and we don't have a way to reliably track that.

**Comment by TylerNichols** [comment]
Yeah, unfortunately I don't think there really is a way to correlate a specific crate with a specific set of loot if you do multiple in a single tick, but you can correlate them all with 'loot boxes'. Not sure if loot tracker supports a single record that can be tagged with a number and the loot from that, but AFAIK that is a pervasive problem with most plugin features (such as slayer monsters left, etc).

**Comment by Nightfirecat** [comment]
This problem could be resolved in the same way we resolve loot from multiple monsters dying on the same tile at the same time. I believe that is handled by creating two loot entries where one has all the loot and the other has none? Given the chat text which tells you what loot you got, we could even be more intelligent in this case by splitting that loot to one crate and assigning any leftover loot (by tracking an InventoryChanged event) to another.

**Comment by TheStonedTurtle** [comment]
>  I believe that is handled by creating two loot entries where one has all the loot and the other has none?

The LootManager ignores all subsequent deaths if they are on the same tile on the same tick. (see https://github.com/runelite/runelite/commit/549150a74930146296fd793aaa17270a2163653b)

I believe this was done as there could be multiple types of npcs on the same tile (barraging nechryaels) and having the db store empty entries didn't make much sense.

This problem would be common with the WT crates but IMO since its already accepted behavior for almost all barrage/chinning methods we might as well track the WT crate loot. I think people care more about knowing what loot they received than having the correct amount of kills shown in the tracker.

**Comment by NymphoSuccubus** [comment]
I really wish that this gets added.
I'm currently going for 200m on my UIM with max amount of points (13500) and I'm tracking manually, where I take a SS every time I open a crate and at the end of the day I just update my notepad with the drops.
It's kinda inconvenient since there's so much and I don't know how to setup in a excel or something so I just do the hard and inconvenient way.
It would be a huge help to have the crates added to the loot tracker >.<

**Comment by hessrs** [comment]
> I've just been told that the reason we didn't add this originally was because you can open multiple crates per tick and we don't have a way to reliably track that.

This behavior (being unable to track multiple opens that occur on the same tick) currently exists for the Tempoross caskets (`Casket (Tempoross)`) and therefore it's inconsistent. Might as well merge it - as @TheStonedTurtle mentioned I think people care more about just seeing the loot rather than the open counter being flawless.
