### ISSUE TITLE
XP Orb (and XP tracker?) displaying wrong value for prayer after burying bone

### ISSUE THREAD

**Issue by Nightfirecat** [runelite/runelite#6262]
Reported in Discord by Corzappy#5592:

> i burried a bone in NMZ and my xp to level became like -2.4 million
> https://gyazo.com/608ff931de023969ccc55e3c3a847d66

**Comment by deathbeam** [comment]
Based on reports on GitHub this is simply because the person had XP tracker plugin disabled.

**Comment by deathbeam** [comment]
So I guess I can close this because globes require that plugin to be enabled

**Comment by daviscook477** [comment]
Hey could this issue be reopened? It seems like xp globes requiring xp tracker (although pretty obvious) doesn't seem super clear to users within the client. Perhaps having an enhancement that allows for plugins to specify dependencies that are automatically enabled when it is flicked on (and allow for those plugins to be disabled automatically when their dependencies are disabled) would be useful in order to not see multiple similar bug reports surrounding this issue.

For example, right now even the wiki (https://github.com/runelite/runelite/wiki/XP-Globes) doe snot mention that globes requires the xp tracker to be enabled.

**Comment by deathbeam** [comment]
We have already bunch of plugins that depend on XP tracker and I dont think making one plugin enable other is good solution.

**Comment by daviscook477** [comment]
What about some kind of warning when a plugin's dependency is disabled. i.e. if I had globes on and then went to disable xp tracker we could fire a Java alert that the player would have to click through that would explain the dependency

**Comment by deathbeam** [comment]
Imo just updating wiki page for XP globes should be enough

**Comment by daviscook477** [comment]
@deathbeam do you know which plugins depend on the XP tracker? I updated the wiki to include that information for xp globes but it might be good to do the same for the others.

**Comment by deathbeam** [comment]
ctrl+click on XpTrackerService should tell you
