### ISSUE TITLE
Performance hit when resizing window, fixed by enabling and disabling Stretched Mode plugin

### ISSUE THREAD

**Issue by Nightfirecat** [runelite/runelite#6307]
https://www.youtube.com/watch?v=5qAhm68oOFM

Reported by BeefaloKing#5787 in Discord

**Comment by devLotto** [comment]
I can't reproduce this.

**Comment by Rion1337** [comment]
I've noticed this happening randomly for awhile but could never consistently reproduce. It seems to only happen when the cursor is inside the text box when you resize the window, and fixed by clicking on anything that moves your cursor out.

Probably doesn't need to be a high priority fix (stop afking yews and you wouldn't notice the problem!) but may be symptomatic of some other more serious performance issue.

**Comment by bigdrizzle13** [comment]
I can reproduce this reliably on 1.6.1 on macOS.

**Comment by Nightfirecat** [comment]
@BeefaloKing @bigdrizzle13 Are you still able to reproduce this?

**Comment by BeefaloKing** [comment]
At least following the exact repro steps above I can no longer reproduce it. Unless anyone else chimes in it's probably safe to close this.

**Comment by Nightfirecat** [comment]
Haven't heard of any repro since my comment, so I'll close this for now. If we hear of this issue again we can re-open later.
