### ISSUE TITLE
Mark of grace examine giving the price of 10 amylase crystals

### ISSUE THREAD

**Issue by Roberts96** [runelite/runelite#6418]
I would like to see a feature added that when you examine a stack of marks of grace it will show you the price of 10 amylase crystals instead of showing just the alch price of a mark.

https://i.gyazo.com/38d9db78ed81df48df15b4bc04e596fe.png

**Comment by Roberts96** [comment]
So, for example, that stack of 345 Marks of grace would display as GE average 4,547,100 HA value 345 as that would be their value if you traded them in.

**Comment by critzd** [comment]
I don't think that would be in line with any of the other items, and since you're able to actually High Alch the item, it really wouldn't make sense. It would also be a clarity thing, you shouldn't get a value of something it isn't actually worth in that form (as the Mark of Grace).

**Comment by Roberts96** [comment]
> I don't think that would be in line with any of the other items, and since you're able to actually High Alch the item, it really wouldn't make sense. It would also be a clarity thing, you shouldn't get a value of something it isn't actually worth in that form (as the Mark of Grace).

There is no reason not to, it's just food for thought considering those stacks are easily equal to 40-50m if you keep them on the way to 99.

**Comment by mckayze** [comment]
Maybe not an examine but simply a toggleable option (Off by default for the people who aren't interested in this) that allows adds marks of graces value to our bank value or something of the sort. I am a level 3 with 99 agility as my only 99, but my bank shows 16m from other items, It would be nice to see my full bank value.

The value of the marks can simply correspond to the value of amylase crystals at the time with 1 Mark = 10 amylase crystals (Because 10 marks gets you a 100 crystals). So the price of 1 mark of grace would be whatever 10 amylase crystals would sell for at the time.

Really hope this gets added in at some point!

**Comment by Roberts96** [comment]
> I don't think that would be in line with any of the other items, and since you're able to actually High Alch the item, it really wouldn't make sense. It would also be a clarity thing, you shouldn't get a value of something it isn't actually worth in that form (as the Mark of Grace).
Well, it was added so get it up ye
