### ISSUE TITLE
FPS drops after opening world map

### ISSUE THREAD

**Issue by Adam-** [runelite/runelite#662]
After opening the ingame world map, even after closing it, there is a lot of GC presssure which causes noticeable pauses. The only way to fix it seems to be to restart the client.

**Comment by deathbeam** [comment]
The solution will definitely be fixing the world map code for Jagex. That can be pretty hard to do.

Also my suggestion is to switch to G1 in client params to default, because it is doing most of the garbage colletion in parallel so it is not causing immediate pauses, tho reduces the collection pausing to minimum.
Here is description of G1: http://www.oracle.com/technetwork/articles/java/g1gc-1984535.html
It is enabled by default in Java 9 and optional in Java 8 (can be enabled with `-XX:+UseG1GC` param).

**Comment by Adam-** [comment]
Addressed in e01cd0378aac396ce85aaf5eedef787ffa54e6af by releasing all of the world map memory when it is closed.
