### ISSUE TITLE
Centralized crowdsourced data collection for OSRS Wiki

### ISSUE THREAD

**Issue by leejt** [runelite/runelite#6688]
We want a way to log data from ingame events to a centralized location, that will be used to "crowdsource" rates so they can be surfaced on the OSRS Wiki and other places. Some examples of this:

- Logging monster drops, to surface exact drop rates (similar to a [project](https://www.reddit.com/r/runescape/comments/9q7txz/accurate_drop_rates_are_coming_to_the_new_rswiki/) on the RS3 wiki using RuneMetrics)
- Logging teleports and other large movements, to make future transportation-based tools more complete
- Logging successes and failures for Cooking, Woodcutting, Mining, Fishing, Thieving, etc, in order to determine how these scale with level and equipment
- Logging NPC spawn locations, to semi-automate the creation of better location maps
- Logging anything else where randomness is a core factor, such as Treasure Trails, bird's nests, various minigames

Technically, what's going to happen is we will set up an API server (for scaling reasons, separate from the existing RuneLite API server) that will simply use nginx to log the payload of any POST requests made to it. This data will be processed after-the-fact (outside of the RuneLite stack) to get aggregated data.

Adam and I will handle the server setup. This feature request is mainly to create the library that will log the events to this API. 

My proposal: insert logging statements in various parts of the client code, that will build up a list of logs in memory.

At a bare minimum, each log event will contain:
- The current time
- The x/y/z coordinate where the event took place [subject to discussion]
- Additional structured data depending on the event type (for example, Cooking logs might include Cooking level, the type of food being cooked, whether the attempt was successful, and whether Cooking gauntlets were worn)

Every N minutes (5? 15? depends on utilization), the logs will be flushed as JSON to this API with a simple HTTP request.

**Comment by daviscook477** [comment]
Likely we will want to maintain an in-memory queue of events that we care about and flush it to the API in a single http POST request when it gets full (say 50 events) or on some timer or program exit/user logout. This will require some set of code to maintain and flush the queue in addition to the necessary code to represent each event we are interested in (itemdropevent, npcdiedevent, xpdropevent, etc...) where each of those events has some simple way to be converted into a json string (either it could have a toString representation or we could use like gson.toJson). Finally we would need to put hooks into the runelite client to recognize when these events occur so we can post them to the in-memory queue.

Additionally we should probably be conscious of users not wanting their metrics logged which would require the addition of a setting to the main runelite config that allows them to opt-out of having metrics sent. (we would want to use opt-out rather than opt-in, right?)

**Comment by Nightfirecat** [comment]
Fixed in runelite/plugin-hub/pull#57
