### ISSUE TITLE
Fight Cave Prayer 

### ISSUE THREAD

**Issue by mdbx** [runelite/runelite#6866]
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)

**Describe the bug**
The Fight Cave Jad Fight prayer switch plugin is not on the list of available plugins as of 1.5.3

**To Reproduce**
Re installed client 
Looked for the plugin

**Expected behavior**
Fight cave prayer plugin to be available

**Environment (please complete the following information):**
 - OS: Windows
 - RuneLite version: 1.5.3
 - Launcher version:1.6.0

**Comment by deathbeam** [comment]
It was removed, read the blog post: https://runelite.net/blog/show/2018-12-06-1.5.3-Release

**Comment by Mycrawsbow** [comment]
yeah the removed something useful because to many people wanted to whine about it and think this script is bad even though to me it was super useful for slayer i had my fire cape but i have to go to a public internet source to do it because i live out in the mountains with bad inet this script allowed me to do jad for slayer incase i had lag spikes but not any more....thats why i dont donate to scripts that was the only reason i used runelite lol
