### ISSUE TITLE
Adjust colour/content of GE prices chat price that shows after examining item

### ISSUE THREAD

**Issue by 0xPaige** [runelite/runelite#6932]
**Is your feature request related to a problem? Please describe.**
The ability to change the colour of the blue text that shows up after examining an item and also the ability to show/hide either GE Average price or High Alch price. The text in question is below:

"Price of **Manta Ray**: GE average **1,170** HA value **120**"

**Describe the solution you'd like**
A menu in the settings that would contain hex colour picker to change the colour of the text, and 2 checkboxes to show/hide High Alch or GE prices

**Describe alternatives you've considered**
Hard coding the colour to a colour that's easier to read

**Additional context**
Screenshot: (Text in blue)
https://i.imgur.com/JpNTknN.png

**Comment by Nightfirecat** [comment]
You can configure the color already [using the "Examine highlight (transparent)" option in your chat colors config.](https://github.com/runelite/runelite/blob/master/runelite-client/src/main/java/net/runelite/client/config/ChatColorConfig.java#L446-L455)

As for showing only one of the two prices, is there a reason we wouldn't want to show both? Making the chat line shorter wouldn't reduce the space it takes since it'll always consume one chat line anyway.

**Comment by 0xPaige** [comment]
Oh cool, thanks!

It's just not relevant for me, being under the level to be able to HA, it's just extra irrelevant information

**Comment by Adam-** [comment]
What is your GPU and driver version?

**Comment by deathbeam** [comment]
Showing both is fine its not like you look at it often, and rest of the issue is already feature
