### ISSUE TITLE
RC Calculator isnt 100% accurate

### ISSUE THREAD

**Issue by GobbleMe** [runelite/runelite#6953]
Currently the rc calculator for bloods/souls doesn't include the xp from making the dark essence blocks.

**Comment by deathbeam** [comment]
Well, you are not rcing so, its correct

**Comment by GobbleMe** [comment]
I mean, good luck making blood and soul runes without making dark essence blocks.

**Comment by GobbleMe** [comment]
To be a bit more specific, you MUST use dark essence blocks to make any blood/soul runes.  Each dark essence block gives 2.5xp when converting and it allows to you create 4 blood/soul runes, so 0.625xp should be added to the values of blood/soul runes for more accurate calculations.

**Comment by daviscook477** [comment]
According to the wiki (https://oldschool.runescape.wiki/w/Dark_essence_block) these blocks are untradeable so each blood/soul rune really does *require* gaining the bit of rc xp for making the dark essence blocks. There is the theoretical situation in which someone just mines and makes dark essence without turning it directly into runes (maybe banking it?) but this seems pretty damn unlikely since that would just be so inefficient compared to turning it into runes directly.

**Comment by xDemoN** [comment]
Following up on this, I can add 0.625 xp to the blood and soul runes in skill_runecraft.json if that's deemed the acceptable solution.

**Comment by deathbeam** [comment]
Sure
