### ISSUE TITLE
item-stats: Stats shown for certain non-equippable items

### ISSUE THREAD

**Issue by logarrhythmic** [runelite/runelite#6966]
**Describe the bug**
The Item Stats plugin shows the stats of [Holy symbol](https://oldschool.runescape.wiki/w/Holy_symbol) when mousing over [Holy symbol (Icthlarin's Little Helper)](https://oldschool.runescape.wiki/w/Holy_symbol_(Icthlarin%27s_Little_Helper)). This also applies to the unholy symbol in the same quest, and probably any other item with an identical name to a different, equippable item.

**To Reproduce**
1. Enable equipment stats in the Item Stats plugin
2. Mouse over any non-equippable item with the same name as a supported equippable item

**Expected behavior**
No stats should be shown.

**Screenshots**
![image](https://user-images.githubusercontent.com/1952758/50045347-f9a75480-0099-11e9-9b12-d7d74168fc61.png)

**Environment:**
 - OS: Windows 10
 - RuneLite version: 1.5.4
 - Launcher version: 1.6.0

**Comment by Demonslay335** [comment]
Also kinda related, noted items display stats as well.

![image](https://user-images.githubusercontent.com/5551512/50050584-0ee5a880-00c5-11e9-9dd5-e19e25ef27d6.png)

**Comment by jakebellotti** [comment]
Item stats are retrieved by the item name, not the item id, which is why the same stats are being displayed for two different items.
The second Holy Symbol (Quest Icthlarin's Little Helper) isn't even equipable, so the stats shouldn't be displayed in the first place.
As for noted items, perhaps that could be toggled on and off with a config?
