### ISSUE TITLE
Add Set Target Level to EXP tracker.

### ISSUE THREAD

**Issue by Derek-Baum** [runelite/runelite#6998]
I am frustrated at the time it takes for me to currently set target levels with runelite.

There are currently two ways to do this,

1.  Use the runelite calculator and do the math on how much EXP is left

2. Use the vanilla client and configure your exp drops and set a target level that way.

I dislike having to interrupt my game by pulling up a vanilla client interface, and taking a long time to set exp trackers.

**Describe the solution you'd like**

I'd like to be able to right click any of the runelite exp trackers and click 'set target level' type in a level, and press enter in order to see my remaining exp for a higher level.

This is much easier when doing something like say, early crafting, when I want to set a target at multiple increments, to keep track of when I'm able to make new items.

Currently using the vanilla client feature it is too clunky and interrupts the game which makes me able to only set an end goal, instead of multiple intermediate goals.

**Comment by deathbeam** [comment]
The way it works is intentional, and its not like you are changing your goals every minute. It is integrated with vanilla in nice way, and it will stay like that. If you want to improve how the vanilla goal interface works, that is not really something we shoudlt ake care of. Also, the vanilla goals are persistent, while our re-implementation of them would not be, and would be generally worse and not integrated into the game (e.g into the in-game xp tracker as well).

**Comment by Derek-Baum** [comment]
I am changing my goals literally every minute, especially in DMM. It's pretty much useless to use the ingame interface, because its not worth the time it takes to set up a target level.
