### ISSUE TITLE
Add CML EHP lookup to Hiscore plugin

### ISSUE THREAD

**Issue by deathbeam** [runelite/runelite#720]
As requested on Discord, this would be nice to have, but that would require us depending on the CML api.

**Comment by Abextm** [comment]
For whoever implements this: The CML API will occasionally give blank 200 responses, timeout, or give html, or otherwise act unexpectedly. Ensure you fail gracefully when given weird input.

**Comment by Unmoon** [comment]
Bonus points: F2P rates (especially ironman): http://www.f2p.wiki/ehp

**Comment by Adam-** [comment]
Additionally !eph also perhaps.

Last month I started tracking xp gains automatically at logout within the client. They are not displayed anywhere currently. I thought it would be neat to work the stats for it into the xptracker plugin, but it could also be used for this.

**Comment by deathbeam** [comment]
It could, but we would need to steal the formula from CML then, or write our own, but I guess copying it from CML if it's public would work? But they regullary update it I think.

**Comment by Lalonde33** [comment]
Would love to see this implemented. The exp rates are public on crystalmathlabs.

**Comment by Nithe** [comment]
Would it be possible to upon logout, refresh/update the cml page of the user? So that it would create a datapoint every time you log out and give a more consistant look at your exp gains?

**Comment by Lalonde33** [comment]
@nitthe. There is a program on cml that doesn't this. Auto updates u every hour. U have to download it

**Comment by psikoi** [comment]
I think this can be closed, unless CML does a proper comeback with a quality API, right?

**Comment by Nightfirecat** [comment]
I'm inclined to agree. Since this request was opened, we've launched the Plugin Hub, which [already has one such plugin for player lookup](https://github.com/dekvall/runelite-external-plugins/tree/wom-utils) which supports EHP lookup. If other sites want to have similar plugins, they need only [follow the contribution flow for contributing a new plugin to the hub](https://github.com/runelite/plugin-hub#creating-new-plugins).
