### ISSUE TITLE
Game instantly crashes when turning on GPU plugin 

### ISSUE THREAD

**Issue by kevankas** [runelite/runelite#7245]
i7 3700k
radeon 7970 ghz

As of like a month ago every time I turn on the GPU plugin my game just crashes within the next 30 seconds if not instantly. Every time. I've already thoroughly browsed the forums for previous answers but most are geared towards nvidia cards and nothing I've tried so far has worked. I've tried disabling hardware acceleration through a .bat file as well as already having comp ability mode offline.

**Comment by kevankas** [comment]
Any suggestions?

**Comment by Nachtmerrie** [comment]
I am facing a similar issue. I cannot log into the client on my laptop because then it will sync my settings, (means turning on the GPU plugin) and that instantly crashes my game.

It does not leave any log entries in .runelite/logs/launcher.log or client.log, so no help there.

OS: Ubuntu 18.10
Exec=java -jar /home/derp/Downloads/RuneLite.jar --mode=OFF

I cleaned my settings again (rm -rf ~/.runelite) and tried starting the game without turning off hardware acceleration. This also results in a crash because my laptop does not do graphical hardware acc.



My conclusion: 

If hardware acceleration is OFF, it should not be able to turn on the GPU plugin.

**Comment by Nightfirecat** [comment]
For anyone experiencing this issue, can you post the contents of your `jvm_crash_pid` file?

**Comment by deltarod** [comment]
Where would this file be located?

**Comment by Nightfirecat** [comment]
It would be in the same directory as your `client.log` and `launcher.log` files: `%userprofile%\.runelite\logs` on Windows, and `$HOME/.runelite/logs` on Linux and MacOS.

**Comment by deltarod** [comment]
There is no jvm_crash_pid. I enable GPU and immediately crash. I can also try building/running this manually if need be.
[client.log](https://github.com/runelite/runelite/files/4277814/client.log)
[launcher.log](https://github.com/runelite/runelite/files/4277815/launcher.log)
