### ISSUE TITLE
Menu Entry Swapper no longer properly swapping Chase option (and possibly others?)

### ISSUE THREAD

**Issue by DiskImage** [runelite/runelite#7255]
It looks like this was previously addressed for cats in #1547. 

**Describe the bug**
Some Menu Swapper settings aren't being properly respected. (ex. Chase isn't the proper left-click option for cats despite being selected. I have a hellcat if it matters.) Some items with teleport options may lack a strategy for dealing with which of multiple teleport options to switch to the left click (Ardy cape 2)

**To Reproduce**
1. Have a cat follower and ensure Menu Swapper is enabled, along with the Chase checkbox.
2. Hover the cat while it's following you, "Walk Here" will be taking priority over Chase

**Expected behavior**
I expect that if I select a Menu Swapper option that that option becomes the left click option for that menu. For cats this means that if Chase is selected then I should be able to left click to chase rats. (This worked a few months ago when I did RFD)

**Screenshots**
![image](https://user-images.githubusercontent.com/1789383/50939232-9b278900-1441-11e9-9b6a-5cccc842d9ff.png)
.

**Environment (please complete the following information):**
 - OS: Windows 10 Pro
 - RuneLite version: 1.5.6.1
 - Launcher version: 1.5.2

**Comment by Nightfirecat** [comment]
This is expected behavior. Because your pet options are set to be on right-click only, it is swapped with the "Pick-up" option, but both of those are lower in the menu than the "Walk here" option. I believe you need to disable the ingame option which forces pet options to be right-click only.

https://github.com/runelite/runelite/blob/master/runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper/MenuEntrySwapperPlugin.java#L482-L485

**Comment by DiskImage** [comment]
Huh, I definitely didn't change that in-game setting for myself, so that's lame. My mistake I suppose!
