### ISSUE TITLE
Allow the fog to be calculated based on the player's location

### ISSUE THREAD

**Issue by Frunkh** [runelite/runelite#7273]
Similar to this video:

https://www.youtube.com/watch?v=8nCxvM3Ak4U

Currently the fog is a set dinstance from the edge of the region. This looks and feels weird when walking towards to edge. Instead an option to have it be based on the location of the player would feel more like an actual fog (Just like RS had back in the HD days). Sure the edge of the region might be visible sometimes but I feel like it would feel worlds better than how it is now. 

Image as reference:

https://i.imgur.com/60FCGZf.png

**Comment by Jilms** [comment]
Doesn't the fog in the gpu plugin do this already?

**Comment by Nightfirecat** [comment]
That's correct. When the draw distance is low enough such that the current scene is not fully rendered--such as if your draw distance is at 25 rather than the maximum of 90--the fog will move with you. The left image in your reference is only the case when playing with maximum draw distance, and is expected behavior.
