### ISSUE TITLE
Monkey Madness is not requirement for creating "Ape Toll" teleport for Diary

### ISSUE THREAD

**Issue by deathbeam** [runelite/runelite#7309]
As reported on Discord

**Comment by forsco** [comment]
In order to make the teleport tablets you need to cast the spell related to the tab you want to make. This would mean that it does have a requirement.

```
In order to cast this spell, players must have earned at least 60% Arceuus favour to unlock the Arceuus spellbook.

Completion of the Monkey Madness I quest and the post-quest 10th squad training from Daero is required to cast this spell.
```

Taken from: https://oldschool.runescape.wiki/w/Ape_Atoll_Teleport

**Comment by forsco** [comment]
If that's the case it wouldn't be intended by Jagex, as you need to be able to cast the spell to make a teleport tab.

**Comment by chivesrs** [comment]
Sounds like a bug on Jagex's end, because the behavior with Bones to peaches (as listed on https://oldschool.runescape.wiki/w/Bones_to_peaches) is that to create the tablet, you must be able to cast the spell.

But, the current state of the game sounds like you only require the skill level and favor levels. So from this list https://i.imgur.com/7uQbX1I.png, the "Monkey Madness I" requirement should be dropped.
