### ISSUE TITLE
Adding OSBuddy price data

### ISSUE THREAD

**Issue by extermistmonk** [runelite/runelite#733]
OSBuddy exposes their GE price data (what's shown in the GE window along the guide price) publicly through an online API. Would this be something that people would be interested in having in runelite, either as part of the API or as a plugin? I wanted to start coding up support for accessing OSB price data but wanted to make sure that there isn't any opposition to this idea, for legal or ethical reasons, or otherwise.

**Comment by Adam-** [comment]
I would prefer to not have a dependency on any closed source, proprietary, and undocumented third-party APIs. I think if the only added benefit is slightly more accurate price data, then it is not worth it.

**Comment by extermistmonk** [comment]
That's fair, although OSBuddy's price APIs are quite widely used and I imagine that they're likely to remain stable. I can understand if the fact that they're proprietary makes their use unappealing.

How about implementing something similar for runelite users? I still think live price updating is quite important because actively traded price is often significantly different from the GE guide price. The only issues I can forsee are that it would require a centralized server, and it might be vulnerable to price manipulation if the code for sending buy/sell data is open-source.

**Comment by Adam-** [comment]
Yes. It is not possible to prove clients have bought or sold anything so it would be open to abuse if we made it. The same problem exists for !kc and is why we don't have it.

**Comment by xaviergmail** [comment]
Considering a service as big as  ge-tracker.com relies solely on the rsbuddy api, I don't see why we shouldn't! I wouldn't mind seeing it as an off-by-default option.

AFAIK, Aside from public awareness, the accuracy of rsbuddy's prices are were deciding factor when it comes to client selection among my friends.

**Comment by Kyle-Newton** [comment]
I'm very for having a more accurate pricing schema, preferably from a very well updates source like GE-Tracker. I think they may crawl from a few different sources and it's a dependency but it could always default to the in-game GE pricing or switch to it if ge-tracker services go down.

**Comment by Kamielvf** [comment]
GE Tracker uses the OSB api to gather their data, so there's no point in using them as source.

#1277 is also relevant to this discussion.

**Comment by Cwade789** [comment]
I am in favor of this feature!

**Comment by richardbadman** [comment]
I'm not sure how this could be open to abuse/manipulation if there was a centralised server if we have a plan and robust service in place?
I've quickly drawn up a possible architecture drawing of how this could be achieved in a safe manner.

![image](https://user-images.githubusercontent.com/6727336/38895428-f1cbe0c6-4287-11e8-9c81-69175e37a1e6.png)

Let me go through this;

- Crawler : This would actively go through item lists and make calls to the rsbuddy API and update the DB.
- DB : A simple SQL database, _(PostgreSQL preferably due to its MVCC nature can be quite powerful, but mysql works)_, simple schema structure and create an ERD if required.
- Storage App : _(Although optional, extremely recommended)_. This acts as a middle man between the RuneLite API and the DB, you can have protection measures in place to prevent SQL injections and have more powerful search features present here _(for example, PostgreSQL v10 allows you to store JSON objects, which would allow this app to retrieve the data in the raw form to keep query times down to a minimum, and then using java _(if wanted, could be python or whatever)_ to manipulate this data to provide better data. I know mainly for the client it will be just getting a price but if you were to extend this in the future in some form of fashion. You would also use this to insert data into the database, such as tracking peoples transactions that have successfully bought or sold _(and again goes to a more secure system)_.
- RuneLite API : This can make calls to the storage app, this goes hand in hand. i.e. with the concept of the storage app inserting / updating records in the database of transaction history for a user in the GE. You could keep the table information completely private to users / developers of rune lite and just have the API communicate with this app.

The reason I added this blue line is cause effectively this would act as 1 cluster. If you use Kubernetes you can store secrets on the cluster which can contain sensitive information such as passwords for the database etc. and is hidden from people using the cluster _(I know it hashes it, which could then even make it better for being public to follow with the open source goal of RuneLite)_. My recommendation for the parts in the blue section also would be a private repo away from public eyes. I know this doesn't then necessarily make it open source, but for the better of a highly sought after feature-request it might be a compromise.

A benefit of also containerising the services in blue is you can spin up more services in times of high demand and have higher availability of the data.

I'm aware that this is quite a big project for this, and if considered I would be happy to help as its what I do as a job. 

But any questions and thoughts let me know

**Comment by LeviSchuck** [comment]
Further discussion of this is in #1277

**Comment by Adam-** [comment]
The simplest way to do it is have the api reach out to OSB and fetch data on demand with caching. This is how the existing price stuff works for pulling in the official ge prices. If you can work within the existing architecture I would not mind it (tomcat + mysql). I would not mind a separate application scraping it and inserting it into the database though I suppose. The largest factor in the existing architecture is money, I cannot just run a kubernetes cluster, and the larger cloud providers are prohibitively expensive.

**Comment by Adam-** [comment]
Added in #3810
