### ISSUE TITLE
scaling sidebar independantly

### ISSUE THREAD

**Issue by ironicalbob** [runelite/runelite#7697]
my problem is when I have my OSRS client and HUD scaled properly for full screen. the Runelite side bar is very small.
If i change windows DPI scaling both the OSRS game and Runelite scale together which effects the smoothness factor of the game.

the solution for this would be adding scaled side bar. i would say just resize text but that may cause overlapping.
![dpi issue](https://user-images.githubusercontent.com/47308009/52184986-28af8c00-27e8-11e9-83f8-ee49e0e61287.png)

this is approximately what graphics/HUD scaling i am after, but if i want to scale the side bar i have to scale everything.  which takes away from other elements.

**Comment by deathbeam** [comment]
There is no way to properly scale just sidebar. DPI scaling works good enough.

**Comment by T-Grave** [comment]
I disagree with "DPI scaling works good enough".

I don't want to turn on a 125-150% DPI scaling across my entire monitor just because I find the RuneLite UI difficult to read because of tiny font choices. All of my other applications are perfectly readable without any issues at 100%.

Windows currently doesn't allow to increase the DPI scaling for 1 single app. You can set a higher DPI for everything and then turn it off per app, but that's not a solution when it's just one single app that is hard to read.

I've tried passing in the scaling factor to the JAR, that works, technically. But it doesn't improve readability at all, if anything it makes it even worse because the font doesn't scale well.

**Comment by Moonkis** [comment]
I'll have to agree with @T-Grave  it's a bit cumbersome to have to set the DPI-scaling system-wide for practically only RuneLite. The best solution would of course be to being able to scale it independently of the game itself.

I think a good compromise is allowing us to pass jvm/scaling arguments which there exists a PR already for here https://github.com/runelite/launcher/pull/19 , although it seems forgotten or otherwise.

**Comment by Adam-** [comment]
> 
> 
> I'll have to agree with @T-Grave it's a bit cumbersome to have to set the DPI-scaling system-wide for practically only RuneLite. The best solution would of course be to being able to scale it independently of the game itself.
> 
> I think a good compromise is allowing us to pass jvm/scaling arguments which there exists a PR already for here [runelite/launcher#19](https://github.com/runelite/launcher/pull/19) , although it seems forgotten or otherwise.

The launcher has two modes of operation, one will launch the client in the same VM as the launcher is in, the other will launch a new VM.  For the former, which is the most common way it operates, we cannot adjust the JVM arguments in the launcher as the launcher runs post-VM startup.  It does this so that Discord can identify it by its process name RuneLite.exe. So it is not as simple as it seems.

**Comment by Moonkis** [comment]
@Adam- 
> The launcher has two modes of operation, one will launch the client in the same VM as the launcher is in, the other will launch a new VM. For the former, which is the most common way it operates, we cannot adjust the JVM arguments in the launcher as the launcher runs post-VM startup. It does this so that Discord can identify it by its process name RuneLite.exe. So it is not as simple as it seems.

Isn't that the point of `-jvmargs` to be able to pass jvm arguments through the chain? Or am I mistaken?

**Comment by Adam-** [comment]
The *code processing the -jvmargs* argument is *Java code*, so by then it is too late since the JVM must already be running.

**Comment by tenroseUK** [comment]
Has there been any solution for this problem that doesn't involve scaling my whole monitor? RuneLite is the only application causing eye strain trying to read the tiny text in the sidebar. @ironicalbob @deathbeam

**Comment by 0xSteap** [comment]
Almost 2 years later, is there a possibility to scale just the RuneLite UI? I know there is DPI Scaling but this is not suitable for everyone.
