### ISSUE TITLE
Allow for (an easy way) to import ground markers

### ISSUE THREAD

**Issue by YannisGH** [runelite/runelite#7853]
Would be useful to get started in raids/inferno rather than having to go in and marking everything yourself, sort of simular to bank tags

**Comment by robrichardson13** [comment]
It looks like the way ground markers are saved is by grouping by a region ID.

If you open up your `.runelite/settings.properties` file you'll see all your clients settings. Ground markers are saved as:

```
groundMarker.region_7249=[{"regionId"\:7249,"regionX"\:25,"regionY"\:45,"z"\:2}]
```

As a workaround, I think you should be able to quit out of RuneLite, edit this file and paste in the markers you want, then open the app back up and you'll have them imported.

An import tool would need the ability to check and see if you already have that region in your settings and if so, insert unique tiles into the array. Also not sure what the UI would look like, because in order for an import tool, you would probably need an export tool. And for exporting, there doesn't seem to be an easy way to group each set of tiles without knowing the region ID.
