### ISSUE TITLE
Add ability to show combined xp drop in addition to the in-game xp drops

### ISSUE THREAD

**Issue by winterdaze-rs** [runelite/runelite#796]
If you gain xp in multiple skills at once, such as HP + a combat skill, show the combined sum of xp in addition to the separate skill xp drops. Alternatively, consider adding xp drops separate from the default in-game ones so the position of them is more customizable.

**Comment by SomeoneWithAnInternetConnection** [comment]
Just to confirm: You want *both* individual, and combined XP here, right? Since the built-in drops do support combined drops, but unfortunately not at the same time as separate drops:
![combineddrops](https://user-images.githubusercontent.com/34518321/36938962-97f7a1ec-1ef7-11e8-8043-a81209267b9d.png)

**Comment by winterdaze-rs** [comment]
yes, that's correct so the combined would be listed under all the existing separate ones
