### ISSUE TITLE
Idle sounds + flashing not noticeable enough.

### ISSUE THREAD

**Issue by Gregory-FR** [runelite/runelite#8044]
Would it be possible to add a sound that loops while idle or have the window keep flashing? This would greatly help me realize when my character goes afk.

Also, have the idle sound play immediately when status changes from "Mining" to "idle"

**Comment by Dgc2002** [comment]
Have you looked at the notification settings in the RuneLite configuration(Plugins -> RuneLite)?  
  
And when you talking about the window flashing are you talking about your OS flashing the window or the game screen flashing? If you mean the former then look in the above configuration for "Enable flash notification"
  
> Also, have the idle sound play immediately when status changes from "Mining" to "idle"  
  
Isn't this what the "Idle Notification Delay" configuration setting is for? Setting this too low will cause a lot of false positives because being 'idle' is generally determined by what animation your character is doing. Sometimes there's a longer delay between action animations and you'd get incorrect notifications.

**Comment by deathbeam** [comment]
It does like 4 flashes or so. Also sends sound, and notification, idk what else would you expect. And also I believe we already have issue for that.
