### ISSUE TITLE
Feature-request / discussion: PvP performance tracking 

### ISSUE THREAD

**Issue by SaintJuniper** [runelite/runelite#8269]
**Is your feature request related to a problem? Please describe.**
Determining performance in PvP, specifically tribrid fights, is pretty hard to do accurately. Due to the nature of RNG in the combat system, you may win/lose fights that you may feel are undeserved.  

**Describe the solution you'd like**
In an ideal solution, the feature would count the following 2 stats during a fight:

1.  Number of times you hit the opponent off-prayer
- Every time you hit an enemy, it will look at your current attack-style (for example, ranged) and also your enemies overhead prayer that is active on the same tick. It will track whether or not the prayer is 'correct' or not 

2. Number of times your opponent hits you off-prayer
- On the flipside, registering whether or not you manage to get correct overhead prayer up for your opponent's attacks.

Ideally either a manual or automatic reset for these counts would be available. The end goal would be statistics for the most recent fight, an example would be as such:

**Player: [your rsn], Attack styles correct: 22/50 (44%)
Enemy: [enemies rsn], Attack styles correct: 30/50 (60%)** 

**Describe alternatives you've considered**
Recording and watching back fights and manually counting would be unfortunately very tiresome and open to lots of errors.

**Additional context**

I'm mostly wondering how feasible something like this would be to implement, if at all. If there's any additional context I can provide, or problems, let me know thanks!

**Comment by Matsyir** [comment]
I was thinking about this, and as much as I'd love to see something like this, I don't think it's accurately possible right now. Basically, if more than 1 hitsplat appears on the same tick, there is no guaranteed way of knowing who dealt the hit. You can make some approximations with HP xp but still can't really be sure since there is decimal xp we can't see, especially somewhere like edge or pvp worlds where there would constantly be loads of hitplats every tick.

See discussion on #3894 for more info.

However, since this is specifically asking about correct attack styles vs prayer and not hits, it might be possible without even involving hitsplats. But I wouldn't think so considering the limitations revealed by the DPS meter.

**Comment by SaintJuniper** [comment]
Interesting, thanks for the response

I wonder if it's possible to work around without using hitsplats and relying more on animation. Since for OSRS combat, the overhead prayer is registered  as correct  for a hit on the tick of the start of the animation of the attack (rather than when the hitsplat is dealt - which may happen multiple ticks later). The actual damage can be ignored

But I guess there is also problems trying to isolate the animations just for the current fight you're in, I'm no too knowledgeable of limitations regarding this or further ones

Thanks again

**Comment by Matsyir** [comment]
No problem, and you are correct about using the animation. That's exactly what I was thinking, and looking at Woox's explanation about how he kept track of range/mage hits in that DPS meter thread, it is definitely possible to keep track of when the animations start, but now I'm not sure about keeping track of overheads. The more I think about it though, the more it seems possible. I don't think I could do it myself without the code that detects your attack animation as well as others' but I'll look into it.

**Comment by Matsyir** [comment]
Okay, sorry to get your hopes up. While it is possible, I wouldn't expect it soon. To be able to detect when you or your opponents are attacking based on the animations, we need to look for a specific animation (AnimationID). I'm pretty sure these are different for every single weapon, since the AnimationID's for Bronze-Drag picks are all different despite having basically the same model. To find these and add them to the list of AnimationID's, it would require using each weapon once with dev tools and writing down the AnimationID for each one. I'd be willing to do this for most common pking weapons but the admins usually don't like incomplete contributions like that, understandably. There is no way I'm doing it for all weapons, I bet I don't even know half of them with all the quest/dead content out there, and just all the variations of bronze-addy weps seems like it would be so long.

Another way that seems reasonable, is just detecting if they are animating at all, and assuming that animation is an attack animation, excluding other animations seen in pking such as: consuming/eating, teleporting. However similarly to above I don't think this is robust enough as it's a hacky way to do it and there are plenty of weird animations people use in the wildy like combining dyes, reading books, diangos claws, snowballs, stuff like that, and I'd be bound to forget some of them.

It could easily be done for only your player using hp xp gains, but I'm not sure if that's very useful without being able to compare. For it to work with your opponent, it has to be based on animations, or in the future maybe hitsplats but not currently possible.

If any admins read this please let me know if an implementation using only common pking weapon animations OR excluding other common pking animations could be accepted.

**Comment by Matsyir** [comment]
@voiderman1337 
Actually, I've been working on an "LMS Performance Tracker" plugin myself for a while now. It's practically done. I will be making a pull request soon, possibly tonight. It's using hardcoded AnimationIDs to determine attack styles. I think the only ones I still need for LMS are VLS & stat hammer. It behaves just like the poster suggested, it shows off-pray hits/total hits. There is an overlay for the current fight, and a panel for previous fights. Feel free to look at my pvp-performance-tracker branch if you're curious. I would be happy to see other contributions improve it or give new stats, such as a DPS tracker.

I don't really have any experience with using hitsplats aside from their knowing about some limitations, from Woox's discussions while he was working on a DPS tracker, and yes, I think most the issues come from multi. What you're suggesting is possible in a 1v1 situation, as far as I understand. Just looked at the api, you get the hitsplats as an event, which gives you the `Actor` it was on and the `Hitsplat` which includes the type, damage, and the time it disappears. So you could determine if it was the player or the opponent from there and use the damage.

It is pretty trivial to determine who is attacking you, with the `onInteractingChanged` event.

I don't think the way you suggest detecting attack styles would be possible. You still wouldn't have a way to distinguish between range or melee weapons if used at melee distance, as far as I know. I might be wrong, I'm not exactly sure what you mean. I don't know about using PID.

Well, now that I've already hardcoded almost all animations for LMS (and many extra, for optional, imperfect use outside LMS), we can determine attack styles with those. I definitely think something involving hitsplats could be added for more stats!
