### ISSUE TITLE
Screen Markers: Text boxes and arrows

### ISSUE THREAD

**Issue by KyuubiFox** [runelite/runelite#8273]
I been using screenmarkers at the blast furnace recently for the first time but feel that a little more can be used to improve it.  
I was thinking of Text boxes and arrows for example at the blast furnace you will be doing a continuos loop and for people like me who have issues remembering what each box is for maybe have an option to also add in on screen text to where you can input for example Ore and Coal above or in the boxes or even wherever you want.
Then there will be arrows much like some paint programs have just draw a line  and boom there's an arrow for for you. which would be useful for helping staying on the path of the the loop of the grind. which can be quite be quite difficult for some people.

**Comment by deathbeam** [comment]
I dont think we want to implement anything else other than just square markers, because that is what 99% of people use. for various other stuff you can just use external software

**Comment by SynapsisMK** [comment]
I'd understand if this kept the wontfix tag, but as part of that 1%, just thought I'd chime in on why I'd find this request useful.  I'm still new to using F-keys, and have a bad habit of scrambling to click on the tab I need instead of using them in panic situations (such as when learning a new boss, or defending myself in the wilderness).  To help reinforce the usage of them, I thought I'd throw an opaque screen marker over the tab icons and label them with the corresponding keys.  I can do half of that now and will be, but I was a little disappointed I couldn't label them.  Another niche situation, and I'll hopefully learn it soon regardless, but it is what it is.  Thanks again
