### ISSUE TITLE
Custom Interface Styles

### ISSUE THREAD

**Issue by squashreel** [runelite/runelite#8303]
Is there any way I could make my own interface style instead of being limited to the 2005/2010 ones? If there isn't any plans to make this a proper feature, is there some way I could customise the existing ones by editing the image files? I tried editing the 2005 interface but runelite redownloaded the .jar when I launched it. Is there a way to stop runelite redownloading the interface styles so I can use a custom one? Thanks.

**Comment by ProTayToe** [comment]
All the images for the [Interface Styles](https://github.com/runelite/runelite/wiki/Interface-Styles) plugin are found in the resources folder of the client at `runelite-client\src\main\resources\net\runelite\client\plugins\interfacestyles`.

If you follow the guide on [Building with IntelliJ IDEA](https://github.com/runelite/runelite/wiki/Building-with-IntelliJ-IDEA), you could modify the Interface Styles plugin to support custom options!

**Comment by sadegr** [comment]
This would also serve as a good compromise for addressing #5690 as users could override the account management sprite with a custom one of their choosing.

**Comment by Mega-boy** [comment]
Would it be possible for the interface styles folder to be moved to outside of the compiled jar? So that users could create and share styles and whatnot. There could even be a portion on the website where people could upload their themes for download and others could rate them up or down, something akin to huds.tf or steamskins.org. I really think it would be cool to have a modern interface that isn't related to runescape at all, but just something different.

**Comment by melkypie** [comment]
This can be accomplished with plugin-hub plugin resource packs. More info can be found here https://github.com/melkypie/resource-packs/
