### ISSUE TITLE
The empty experience and loot tracker panels have their text at different heights

### ISSUE THREAD

**Issue by Nightfirecat** [runelite/runelite#8401]
They have the same layout, so it stands to reason they should display the text at the same height as well.

![2019-04-03_16-53-05](https://user-images.githubusercontent.com/2199511/55520767-43c63d00-566d-11e9-9ba2-45354b39472b.png) ![2019-04-03_16-53-03](https://user-images.githubusercontent.com/2199511/55520768-43c63d00-566d-11e9-9737-a21be1cb09d1.png)

**Comment by TheStonedTurtle** [comment]
I believe this issue is caused by the loot tracker panel calling `super(false);` as the loot tracker panel also has a custom border for the PluginErrorPanel component.

Default: `setBorder(new EmptyBorder(50, 10, 0, 10));`
Loot Tracker: `setBorder(new EmptyBorder(10, 25, 10, 25));`

I think the easy fix would be adjusting the Loot Tracker border so that they align but I'm not sure if that's the "correct" fix.
