### ISSUE TITLE
Wintertodt Plugin Fletching Detection Issues

### ISSUE THREAD

**Issue by Nealon01** [runelite/runelite#8412]
The status indicator for wintertodt is often showing IDLE while actively fletching.  It seems to mostly happen when you go IDLE, and then start fletching again, and the client doesn't seem to notice.  It will sometimes update after I've fletched several logs, but it's inconsistent,

**Comment by ypperlig** [comment]
I noticed this too when fletching. I think the problem lies with the plugin setting to idle as soon as the chat message appears and the player doing fletching use the knife on the logs straight after the interrupt. Because the fletching animation only resets every now and then, it will stay idle until the animation refreshes.
