### ISSUE TITLE
Highlight the song for music clues

### ISSUE THREAD

**Issue by simonvanbennekom** [runelite/runelite#8497]
**Is your feature request related to a problem? Please describe.**
Find the specific music could take sometime, with a highlight where to find it, like the emote clue's it would speed up clues

**Describe the solution you'd like**
Highlight the music that is required for the cluescroll.
Highlight the arrow (up or down) where to find the specific song in the list.

**Additional context**
Could look like this

<img width="593" alt="music_hint" src="https://user-images.githubusercontent.com/11269812/56037527-c915b580-5d2f-11e9-96bd-33d26e48979c.png">

_Maybe this is also a solution to find fairy ring codes faster.._

**Comment by Mat95** [comment]
I was literally just about to suggest something like this, Looking for the song for these clue steps is literal aids. Maybe the feature could be a filter for songs that are possible for all tier clues + a highlight. So people doing clues can spend less time looking for said song, since there are hundreds of them..

**Comment by xDemoN** [comment]
Closed by 05fdc2877d7e28b8f527bd22901c95490ece48b9
