### ISSUE TITLE
Sidebar on left

### ISSUE THREAD

**Issue by xKerbi** [runelite/runelite#8567]
I play runescape alongside other apps like chrome. Runescape is on the right side of my monitor. When I need to open the sidebar, it pushes the game to the left, to make room for itself. Additionally, when I close it, the game moves back to the right, but farther than initially, covering my taskbar
Thus, any time I interact with the sidebar at all, I end up having to reposition Runelite.

Tl;dr Can we please have an option to have the sidebar on the left? 

Other people ask but for some reason this is ignored, because it's "fine this way". Can't see why this wasn't even considered.

**Comment by raiyni** [comment]
duplicate #1641

**Comment by michaelmuzzarelli** [comment]
In what way is this a duplicate of #1641?  #1641 was marked a feature-request as it specifically mentioned wanting to move the bar to the bottom of the screen, this is more a quality-of-life request as anytime the sidebar is clicked (intentionally or accidentally), you have to reposition the client.

**Comment by Nightfirecat** [comment]
The title of 1641 is literally "Add toggle to move sidebar to left or right side", and every other linked duplicate from that issue is the same as this one. As for the repositioning issue, I've found RuneLite to not need repositioning at all if you open, then close the sidebar, so I can't reproduce it personally. Regardless, that would be a separate issue entirely and should be posted separately as such.
