### ISSUE TITLE
Idle notification while glassblowing

### ISSUE THREAD

**Issue by emerald000** [runelite/runelite#8575]
**Describe the bug**

**To Reproduce**
1. Set Idle Notification Delay to 1000ms.
2. Use a Glassblowing pipe on a full inventory of Molten glass.
3. Make Unpowered staff orbs.
4. Click out of the client.
You'll receive an idle notification after about 6 orbs crafted. 

**Expected behavior**
I would expect to receive an idle notification once the entire inventory is crafted.

**Screenshots**
N/A.

**Environment (please complete the following information):**
 - OS: Windows 10
 - RuneLite version: 1.5.20
 - Launcher version: 1.6.0

**Additional context**
N/A.

**Comment by xdesr** [comment]
The glassblowing animation is active once per molten glass, because of this there is a time period which there is no animation (idle).
The majority of the time the idle animation lasts for less than 1 tick.
Upon testing this the animation can hang on idle for 1-3 ticks (causing the player to be notified if the delay is 1000ms). 
I'm not sure why it occasionally hangs for several ticks on the idle animation, i've tested this on several different pings and haven't found any useful conclusion. 

This issue is fixed by doubling the idle notification delay to 2000ms

**Comment by Nightfirecat** [comment]
Sounds like this is not an issue then. Use a longer notification delay and the feature will work as expected.
