### ISSUE TITLE
Launcer crash before loading

### ISSUE THREAD

**Issue by ultratronger** [runelite/runelite#8646]
I know I made a similar issue some time back, but that was fixed by downloading the newest versions of runelite and java, but now I uninstalled runelite, manually deleted the folders that don't get deleted by the uninstaller, updated java to the latest version and redownloaded runelite, but the problem persists.
the normal oldschool runescape launcher works perfectly

[launcher.log](https://github.com/runelite/runelite/files/3119392/launcher.log)

**Comment by Nightfirecat** [comment]
This sounds like an exact duplicate of your earlier issue... (#8336) Have you tried reinstalling/re-updating java since re-downloading runelite?

**Comment by ultratronger** [comment]
yes, I just downloaded Version 8 Update 211 as I already said

**Comment by ultratronger** [comment]
I've uninstalled and reinstalled runelite again but it still doesn't work

**Comment by ultratronger** [comment]
Well, like last time it fixed itself, all it took was me saying "if it doesn't start now I'll play runescape 3" and it actually started lol

**Comment by typat** [comment]
Issue closed without solution? I'm running jdk 1.8u211 and have uninstalled/installed RuneLite numerous times with the same issue. Could be a corporate network issue for me.

**Comment by Nightfirecat** [comment]
@typat This issue was caused by the issue creator having had a virus on their computer which caused this problem for them, if I'm remembering correctly. I'd recommend checking through [our troubleshooting guide](https://github.com/runelite/runelite/wiki/Troubleshooting-problems-with-the-client), and joining our `#support` channel on Discord if you need further help.
