### ISSUE TITLE
Client d/c'ed unexpedly and won't launch - OSX

### ISSUE THREAD

**Issue by JacobJT** [runelite/runelite#8699]
**Describe the bug**
All of a sudden I was disconnected, and the RuneLite client will not successfully launch. I am getting an error message saying "Error loading client! Check your logs for more details." except I can't find any logs anywhere. The client has worked as expected for a long time. This I the first time anything similar has happened. I can not find anything in the options for the program, or searching my system's files for the specified directory. 

**To Reproduce**
Unknown, reoccurs any time I open RuneLite on OSX 10.14.4

**Expected behavior**
client does not kick me off while I am playing and successfully launches when I want to play

**Screenshots**
If I didn't need to insert a link instead of a file, you'd see an image of an all grey run elite screen with a pop up that has the title "Unable to load client", a little image that is a rec rice with a grey !, and the message "Error loading client! Check your logs for more details.", and an "OK" button in the bottom right corner,... if only it actually had error logs I could find.

**Environment (please complete the following information):**
 - OS: macOS 10.14.4
 - RuneLite version: 1.6.1
 - Launcher version: ??? Thanks for telling me what that is.

**Additional context**
Been happening for close to an hour. If I wasn't stoned and laughing at infomercials with my imaginary friends, I'd be way more upset.

**Comment by Nightfirecat** [comment]
If this is still an issue nearly a year later, [you can follow the steps at the top of this wiki page](https://github.com/runelite/runelite/wiki/Troubleshooting-problems-with-the-client) to find your client and launcher logs which can be posted here, or in our `#support` channel on Discord.

Given that this issue was reported quite some time ago, I would recommend downloading the latest launcher for your platform (for MacOS, that is 2.1.1 at the time of writing) and trying to launch the client again as there have been numerous changes since then.
