### ISSUE TITLE
Screenshots not uploading to Imgur

### ISSUE THREAD

**Issue by namines** [runelite/runelite#8749]
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)

**Describe the bug**
The screenshot plugin will save my screenshots to the appropriate folder, but will not upload them to Imgur. I've tried to reinstall the client, use the jar version, nothing seems to make it work.

**To Reproduce**
1. Press screenshot button
2. Nothing

**Expected behavior**
The client should create a screenshot & then upload it to Imgur

**Screenshots**
I have my settings correct: https://i.imgur.com/p4wEqGI.png

**Environment (please complete the following information):**
 - OS: Windows 10
 - RuneLite version: 1.5.22.1
 - Launcher version: 1.6.0

**Additional context**
There is nothing in the client or launcher logs that appear for this :/

**Comment by Nightfirecat** [comment]
If you have your client set to not notify you when you have it focused, that's the expected behavior. You will have a link to the imgur-uploaded screenshot in your clipboard. [Per the code for the plugin](https://github.com/runelite/runelite/blob/master/runelite-client/src/main/java/net/runelite/client/plugins/screenshot/ScreenshotPlugin.java#L687-L691), a warning will be logged if a failure occurs.

**Comment by namines** [comment]
I have my client set to notify me when focused, it's not copying a link to my clipboard either. This was working on my work computer earlier today, but seems to not work on my main computer.
I'm getting no warning or notification about a failure at all.

**Comment by abextm** [comment]
This is because our api key for imgur has been used too much today, and has hit the limit of 1250 uploads.
