### ISSUE TITLE
Account hijacking warning

### ISSUE THREAD

**Issue by yeehaa91** [runelite/runelite#8762]
I would like to suggest a plug-in that records the player’s position on log out and if the player is in a different location next time they log in, the client warns that the account may have been hijacked. Perhaps adding a few exceptions would be appropriate so it doesn’t warn if you log out at Zulrah and then log in at the boat for example.

**Comment by Pikamander2** [comment]
Seems do-able, though I'm not sure how useful it would be.

A list of false positives would be helpful. Here are a few more:

- Being teleported to your spawn point after dying to a DC
- Being teleported to Lumbridge after your membership expires
- DCing / logging out during certain minigames and bosses

**Comment by Nightfirecat** [comment]
* Being at a different location due to disconnecting while walking or doing teleport animations
* Appearing outside of house portals when logging out from within a house
* Being moved to a different location after a game update causes your previous location to be unreachable
* Playing on another device and logging out at some other location
* Playing on another client and logging out at some other location

Also, is it really that hard to remember where you were last logged in? I feel like this would not be a useful feature.

**Comment by abextm** [comment]
If your account has been hijacked its probably too late for you. Try adding an authenticator next time. Also this will trigger if you use any client that is not RuneLite, which is a good portion of the playerbase, so this would just be a constant false positive.
