### ISSUE TITLE
Convert usual emoji text to runelite format

### ISSUE THREAD

**Issue by Azebu** [runelite/runelite#8858]
When you type ": thinking :" in chat, if the option is enabled, it'll automatically be converted to ":-?", resulting in seeing ":thinking:".

**Comment by Twiglet1022** [comment]
Those weren’t included because the colon format emojis like `:thinking:` would look obnoxious to anyone with the plugin off or using the vanilla client, mobile etc.

**Comment by CustardGod** [comment]
I think what he means is if someone tries to send `:thinking:` in chat it is automatically converted to `:-?` when sent so that people can use the :: format but also not be obnoxious to normal players

**Comment by deathbeam** [comment]
The way it is done now is intentional, we will not be supporting `::` codes. we also can't modify output text because that would be autotyping, what is against jagex rules.

**Comment by justastranger** [comment]
I disagree with this decision. Nobody minded konduit's emoji implementation, which is what OP is basically asking for. Plus, it's much easier to remember the `::` codes than the old-school faces that are currently implemented. I had no idea that `:-?` was even supposed to be the `:thinking:` emoji.

**Comment by deathbeam** [comment]
Well it's either this or no emojis, and this decision is final. If you want to read why see the original emoji issue and comments on it.

**Comment by CustardGod** [comment]
> original emoji issue and comments on it.

#1464

**Comment by justastranger** [comment]
The issue seems to boil down to 1.) Don't annoy vanilla players and 2.) How do we decide which emojis to support

Like I said, nobody minded how Konduit did their emoji plugin. You seem to be the only one who cares, wanting to avoid "dumb chat". Vanilla users already have to deal with Runelite and OSB users using the !commands. At least emojis are part of actual conversation. Also, there are open source fonts that contain large selections of emojis (I believe Google has a couple). I imagine that it'd be fairly simple to ask them if you could use their assets (If you even need to, though it would be good form to do so anyways).

**Comment by abextm** [comment]
> Like I said, nobody minded how Konduit did their emoji plugin

incorrect
