### ISSUE TITLE
RE: #862

### ISSUE THREAD

**Issue by l2-** [runelite/runelite#887]
osbuddy : https://gfycat.com/ArcticAngelicFallowdeer
runelite : https://gfycat.com/ClearcutHeavyAuklet
it's actually really annoying for any sort of pvm besides it doesn't matter if interacting or not should show target info until interacting with another npc or not interacting for x amount of time...

**Comment by Kamielvf** [comment]
so the issue here isn't the oppenent HP updating, but the whole opponent overlay not popping up. Because i know for about 99% sure that osb doesn't update their HP if you attack them with either range/mage and click away (losing target) while the projectile is in the air.

That being said, it's still possible to update your opponents hp when not targeted, and I think that would be correct to do.

**Comment by deathbeam** [comment]
#882 should be reopened if this is problem, this is not good way to use GitHub issues

**Comment by Adam-** [comment]
Duplicate of #862
