### ISSUE TITLE
Menu entry swapper - Swap Talk-to with pickpocket

### ISSUE THREAD

**Issue by Mapuut** [runelite/runelite#8872]
There is currently no way to swap pickpocket with talk to for some NPC-s in menu entry swapper. Good example is Master Gardener.

![image](https://user-images.githubusercontent.com/35892391/57985993-f0227e00-7a77-11e9-8457-891e54c9afa1.png)

Would be nice to have option for swapping pickpocket with talk-to or just prioritizing pickpocket over every other option (currently only specific option for swapping it for H.A.M NPC-s). This option should be off by default of course.

![image](https://user-images.githubusercontent.com/35892391/57986069-b56d1580-7a78-11e9-8595-f8d3e6aba976.png)

**Comment by Hydrox6** [comment]
This is [Rejected](https://github.com/runelite/runelite/wiki/Rejected-or-Rolled-Back-Features) for being absurdly powerful for blackjacking. 
Side Note: Martin is an outlier for master farmers since he sells the Farming cape; any other Master Farmer can be left-click pickpocketed without modification.
