### ISSUE TITLE
GPU Plugin occasionally crashes Windows

### ISSUE THREAD

**Issue by Yelnats321** [runelite/runelite#8939]
**Describe the bug**
Occasionally, my computer will freeze up and have a grey screen, becoming unresponsive and looping currently playing audio, indicative of some sort of crash

**To Reproduce**
Unable to reproduce, happens seemingly randomly
Has occurred in these locations recently:
Evil Dave's lair while fighting a Behemoth
Barbarian Assault staging area

**Expected behavior**
My computer does not crash

**Screenshots**
N/A

**Environment (please complete the following information):**
 - OS: Windows 10
 - RuneLite version: 1.5.24.1
 - Launcher version: 1.6.0

**Additional context**
Logs do not have any relevant information, neither does event viewer

Running a Vega 64 on version 19.5.1 drivers

Is there a way to launch with OpenGL debug context and log messages? It's a relatively new feature but since a compute shader is used I assume it is also supported (as both are core in 4.3). RenderDoc did not report any obvious errors but I am no expert

**Comment by Yelnats321** [comment]
Had a crash again, this time in GE. Running 19.6.2 AMD drivers and RuneLite version 1.5.27. Not sure what other info I can provide, is there a way to enable a GPU debug mode?

**Comment by Nightfirecat** [comment]
You can add `--clientargs="--debug"` to a RuneLite shortcut's target, similar to how [the guide for disabling Hardware Acceleration says to add `--mode=OFF` to it](https://github.com/runelite/runelite/wiki/Disable-Hardware-Acceleration) to change the client's log level to DEBUG, which may output more information. That aside, I would still recommend posting your client logs on this issue regardless of whether that uncovers any new information.

**Comment by Yelnats321** [comment]
Will do, and here are the logs, but nothing is out of the ordinary:
[client.log](https://github.com/runelite/runelite/files/3337722/client.log)
[launcher.log](https://github.com/runelite/runelite/files/3337723/launcher.log)

**Comment by Yelnats321** [comment]
I believe it may be related to memory leak and issue #7390. I have monitored increased GPU memory utilization the longer the client ran. I will see how large the GPU footprint gets after a few hours.

**Comment by Toshis-LTD** [comment]
Started using runelite again and the crashes described above have returned. Using vega 56 too

**Comment by cyellowan** [comment]
Hi. I will add a lot of information. I know it's useful, but exactly what part is up for a debugger person to... understand. OK.
Since 2019, i have had over 150 PC crashes. They tend to happen after around 1.5 days. Every time. I just had one right now.
However. When i played using 2 accounts early summer 2020 (thus 2 clients open on 1 pc), i got the crashes around 2X as fast. I got tons of grey-screen crashes in matter of days, which made playing fairly impossible with GPU plugin enabled. I have tried EVERYTHING to fix it. The only "solution" is to use the recommended driver in the github doc, referring to a late 2018 driver (3 years old ancient driver). I don't think anyone want to ruin all their other games/loose features just to make osrs RL gpu plugin work flawlessly.

I suspect some memory leak too, for now i'll have to simply not use the gpu plugin anymore. A shame since everything else looks and works out really great.

**Comment by MESLewis** [comment]
> Hi. I will add a lot of information. I know it's useful, but exactly what part is up for a debugger person to... understand. OK.
> Since 2019, i have had over 150 PC crashes. They tend to happen after around 1.5 days. Every time. I just had one right now.
> However. When i played using 2 accounts early summer 2020 (thus 2 clients open on 1 pc), i got the crashes around 2X as fast. I got tons of grey-screen crashes in matter of days, which made playing fairly impossible with GPU plugin enabled. I have tried EVERYTHING to fix it. The only "solution" is to use the recommended driver in the github doc, referring to a late 2018 driver (3 years old ancient driver). I don't think anyone want to ruin all their other games/loose features just to make osrs RL gpu plugin work flawlessly.
> 
> I suspect some memory leak too, for now i'll have to simply not use the gpu plugin anymore. A shame since everything else looks and works out really great.

Please join us in https://runelite.net/discord #support channel to fix your gpu issue.
