### ISSUE TITLE
Degraded barrows gear does not show item stats when hovered

### ISSUE THREAD

**Issue by slyther184** [runelite/runelite#9253]
Wondering if it'd be at all possible to get the stats of barrows gear that is degraded when I hover over with my mouse, it currently shows nothing.

**Comment by Nightfirecat** [comment]
For future requests, please separate your requests into one ticket per request. That helps us keep track of them better.

1. Do you mean broken barrows gear, or barrows gear of the 100/75/50/25 variants?
2. This is a feature we've chosen not to add, and [is listed on our Rejected features page, under the "Menu Entry Swapping" section](https://github.com/runelite/runelite/wiki/Rejected-or-Rolled-Back-Features#menu-entry-swapping)
3. This failed a Jagex poll, and no other major client implements this, so we are not planning on offering spellbook reorganizing at this time

**Comment by slyther184** [comment]
I meant 100/75/50/25 thanks for your time.

**Comment by dekvall** [comment]
This has to do with the resource file used for item stat lookups. While reproducing the bug i noticed that there were no stats shown for a multitude of other items, items like green d'hide chaps, bob's black shirt etc.

I think this plugin has been a bit broken since [this change](https://github.com/runelite/runelite/commit/14fe12e7d6b56e469232ec5e322ef418d6e27750#diff-db277b4c6c79ed68d4ef201ec33b8e2cL211) where the item lookup changed to use itemIDs instead of names. The stats for degraded barrow items and the the other items mentioned exist in the [stats.json](https://github.com/runelite/static.runelite.net/blob/gh-pages/item/stats.json) preceding this change, so my best guess is that something went wrong during the conversion.

I unfortunately don't know where to find the tools required to fix this. So I guess i will hand it over to someone else until i figure it out.
