### ISSUE TITLE
Grubby key price not registering in loot tab

### ISSUE THREAD

**Issue by dappersnapper456** [runelite/runelite#9292]
As you can see from screenshot. The total loot value should be closer to 60k
![Screenshot 2019-07-06 at 15 51 42](https://user-images.githubusercontent.com/39419158/60757724-04114780-a006-11e9-9915-4d022af2a706.png)

**Comment by lewez** [comment]
As far as I'm aware, this is due to a delay in the item prices updating which is pulled from the API, not an issue with the client itself. http://api.runelite.net/runelite-1.5.28/item/price?id=991
The muddy key price spiked but it has since dropped back down to it's original price (as of writing this).

**Comment by Pineapplezz** [comment]
https://cdn.discordapp.com/attachments/379106621290446849/598215254689710080/tada.png

Issue has since been fixed. It most likely wasn't showing it yet since it was just released. Either way it now shows the correct amount. ALTHOUGH the pages do not display 1k each like they should. (This is due to them being untradeable with 0gp high alch value) The pages are a set 1k each though so I am guessing that it would be ok to change

**Comment by Nightfirecat** [comment]
Please go ahead and open a separate issue for the pages.
