### ISSUE TITLE
Live poll results

### ISSUE THREAD

**Issue by runelitefandab** [runelite/runelite#9299]
Jagex might in the future decide to fake poll results since players have no way to audit or otherwise track poll results as players vote.  Since runelite is used by a large percentage of players, it may work for Runelite devs to track polls as players vote.  

I think it would be important not to default to results being shown and it may be best if the results are only posted on runelite's website.  Even though not everyone uses it, we can find the typical difference runelite's results vary from the real results posted by jagex (under the assumption every poll isn't boosted by jagex) and then we would see outliers if jagex tried to fake polls.

**Comment by Abi1024** [comment]
Not everyone uses Runelite though, so the votes cast by non-Runelite users would be unaccounted for.

**Comment by Adam-** [comment]
Even if I wanted to do this (and I don't) it is a bad idea due to:

1) it is impossible to show the results from RL aren't being skewed too
2) it is impossible to verify the reported results from the clients are not spoofed, so we couldn't use the system to conclude whether or not Jagex was messing with the results, anyway
