### ISSUE TITLE
Zoom with keyboard / Zoom slider

### ISSUE THREAD

**Issue by Axantor** [runelite/runelite#9321]
Well, here's the thing. I know this is gonna sound really stupid but my mouse wheel broke and now the only way to zoom in and out is going to the settings tab and move the slider.

My request is to add an option to the camera zoom plugin to be able to control zoom with the keyboard, maybe using the "Page up" and "Page down" keys, or maybe adding a slider, like in the screenshot below.

![Zoom slider request](https://user-images.githubusercontent.com/43286203/60860899-645edf80-a1e6-11e9-8d30-b2ad68e81488.png)

Thanks for taking your time reading and I'm sorry for this dumb and super specific request lol.

**Comment by jdkleuver** [comment]
Have you considered using AHK to remap keys to scroll wheel? AHK is considered acceptable for remapping keys and is probably a lot simpler to implement instead of doing it through runelite.
AHK has commands ButtonWheelUp and ButtonWheelDown

On linux set up a shortcut to use:
`xdotool click 4 //scroll up`
`xdotool click 5 //scroll down`
I tested the above and can confirm it works with runescape

**Comment by Axantor** [comment]
@jdkleuver I struggled for a while because my coding skills are potato, but after a brief search I found out how to do it.
Thanks a lot! This is exactly what I needed :)
