### ISSUE TITLE
Stuttering Demonic Gorilla Room

### ISSUE THREAD

**Issue by dominio50** [runelite/runelite#9329]
The Demonic Gorilla single area seems to have a stutter lag. I tried turning off gpu, animation smoothing, and the demonic program itself but the problem still persists. I know it has to be runelite because I tried on the vanilla client as well.

The only way I can tell you to reproduce is going towards the west side of the single area cave and just fighting demonics, the stutter happens about every 10 seconds. 

The demonic area is the only place where this stutter happens and I have multiple friends who also say they have the same issue.

**Comment by Nightfirecat** [comment]
I remember having this issue on any client I played with--vanilla, osbuddy, or runelite. I don't think this an issue specific to, or caused by, runelite.

**Comment by Joeyrsd95** [comment]
I started the demonic gorilla grind today, and I can also confirm that there is a stutter happening every 10 seconds. This stutter does not happen on the original osrs client.

I also tried turning off some plug-ins without any result. ( Including the demonic gorilla plug-in)

**Comment by NeilTheSeal** [comment]
I've been looking for various ways to find a fix to this, as well. I've tried adjusting my GPU settings, turning off hardware acceleration, etc. but it doesn't seem to help much. It might be a server-side issue (something on Jagex's part), which would warrant submitting a bug report.

Can anybody confirm that this happens on the vanilla client, as well?

**Comment by jorgeluiscarrillo** [comment]
I've done gorillas a few weeks ago and had stuttering issues, but at least it was playable on Runelite. Today when I tried it was completely unplayable (stuttering every 3 seconds). I switched to the vanilla client and the issue went away. The vanilla client does have minor stuttering so I do believe there is a problem on Jagex side. However, I am unable to do demonic gorillas on Runelite as of now.

**Comment by matcpn** [comment]
Also able to reproduce this. Is there some kind of profiling or debug logging I can turn on to help debug?

**Comment by Adam-** [comment]
This is probably is due to all of the animated objects on the scene (they have to be animated and/or shaded per frame). I'm not sure there is much we can do about it easily.

**Comment by NeoProfessorWillow** [comment]
Just to add my two cents. This issue has only recently started happening, within the last 2-3 weeks. Before that there were minor stutters but not conistent ones like there are now. It almost seems like a chunk load thats happening constantly but theres nothing to load. Please have a deeper look into this issue.

**Comment by Alexsuperfly** [comment]
The underlying problem was supposedly unearthed as the garbage collector running much more often than it should because of some of the methods used in RL.  The gc was changed in java 9+ so if you experience this problem try and download the jar launcher from the website (all platforms version) and run it with one of those java versions, suggest 11 or 12.

**Comment by Adam-** [comment]
I've been trying to figure this out today. The pauses are from the CMS GC running. For me, using the Parallel collector fixes the issue completely, and I can't explain it because everything I've read through seems to suggest that CMS has much lower STW times.

We currently are using `-XX:CompileThreshold=1500 -Xincgc -XX:+UseConcMarkSweepGC -XX:+UseParNewGC` which are the Jagex GC args (evidently running GC on non compiled methods is more expensive due to hotspot having to generate oop maps). This is actually two separate GCs, and uses the parallel GC for new generation objects. Under normal operation it seems that this is actually what runs the most. If you enable `-XX:+PrintGC -XX:+PrintGCDetails` and run around a bit (particularly if you hit scene loads etc. which have forced GC) I cannot find common occurrences of CMS running at all.

Except inside of the Gorilla area CMS seems to run *almost all the time*, and I cannot figure out why. I've tried disabling all of the plugins and it doesn't seem to help. Sometimes if I stand there long enough it decides to switch to use the parallel GC and then it is fine again, but it is uncommon.

Other things I've tried which were unsuccessful:

1) disabling -Xincgc. This is actually already deprecated in Java 8, and it enables incremental-CMS mode, which makes the CMS GC periodically yield control of its threads in the concurrent stages to try and prevent CPU starvation on the application. Due to this, in our case I think it can cause CMS GC to take longer as we generally have many free idle cores due to the client being single threaded. It looks like it was intended for systems with very few logical cores, and has no replacement in 9+. Without i-CMS I *think* the pauses are slightly shorter (it is hard to tell since at most they are ~0.5sec) but it is hard to tell. But they are still noticeable.

2) disabling DontCompileHugeMethods. The client is full of large methods and GCing non compiled methods takes longer due to the GC having to generate oop maps on *each gc*. It doesn't seem to have any measurable affect.

3) I made two commits to decrease memory allocations (4078cfdcaaa4c1fb888d13ed67b413b96176d823 and 4078cfdcaaa4c1fb888d13ed67b413b96176d823) to try and relieve GC pressure. This helps somewhat as it makes the pauses less common, but doesn't seem to affect the length of the pause.

4) disabling regen meter/gorilla plugin doesn't help. There was some early thoughts that the arc drawing was the culprit due to the allocation overhead from enabling antialiasing on the 2d pipeline. We were profiling OpenJDK 8 (the releases we ship include Oracle Java 8) - which evidently has an entirely different 2d pipeline from Oracle Java that is much less optimized. Profiling Oracle Java 8 shows that the allocations are less than several other things, including fixes from the 2 above commits.

We could try disabling the CMS GC on the release due to that it doesn't seem to run anyway generally - so from what I can tell we aren't getting much perf gain from it anyway?

**Comment by Adam-** [comment]
Can someone having the issue try launching RL with `java -XX:+UseParallelGC -Xmx512m -Xss2m -XX:CompileThreshold=1500 -Djna.nosys=true -jar RuneLite.jar --nojvm` and report back if it makes the problem better/worse/etc?

**Comment by matcpn** [comment]
Ran with those args, seemed much better but still some stuttering. I caught these logs around the time of the stutter (sorry, dont know how to copy + paste from cmd). I'd guess that the offending line is the last one, Full GC (Ergonomics). I tried running with -XX:-UseAdaptiveSizePolicy and the game crashed when entering the cave.
![image](https://user-images.githubusercontent.com/4219663/62090797-216bb700-b23c-11e9-92dd-ce977c9dec56.png)

**Comment by Adam-** [comment]
Do the two patches I gave in the earlier post help?

**Comment by matcpn** [comment]
Sorry, I didn't test a build with the two patches but I just wanted to add that the performance is night and day with the jvm flags you posted before. I just got a task to do these and it was very stuttery. I restarted and ran with the flags and it's perfectly smooth now.

**Comment by Adam-** [comment]
@matcpn how is it in comparison to running it with https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/jdk-11.0.4%2B11/OpenJDK11U-jre_x86-32_windows_hotspot_11.0.4_11.zip using `java -Xmx512m -Xss2m -XX:CompileThreshold=1500 -Djna.nosys=true  -jar RuneLite.jar --nojvm` ?

**Comment by Hassinen** [comment]
I hope this issue can be solve finaly, its been there very long and its so annoying. Most of part its unplayable on but restarting client help sometimes. i have played without demonic plugin and tried turn off gpu/set to 25 render distance. 
So many have sayed me its memory leak problem or something.
Good luck for solving the problem.

**Comment by Livingsavior** [comment]
`java -Xmx512m -Xss2m -XX:CompileThreshold=1500 -Djna.nosys=true -jar RuneLite.jar --nojvm`
Worked like a charm, no stutter!

**Comment by Adam-** [comment]
I plan on "fixing" this by the upcoming launcher upgrade which moves to Java 11 and moves GCs. I am hesitant to change the GC on the current release because I don't understand the implications.

**Comment by Sackamanjaro** [comment]
How do I run runelite with that line?

**Comment by Livingsavior** [comment]
@Sackamanjaro 
-right click your runelite shortcut, select "open file location"
- copy the path in the explorer window that pops up.
- open CMD
- type `cd` followed by the pasting the path.
- press enter, then paste the `java -Xmx512m -Xss2m -XX:CompileThreshold=1500 -Djna.nosys=true -jar RuneLite.jar --nojvm` line.

for example mine would be `cd  C:\Users\YourName\AppData\Local\RuneLite` With "yourname" being whatever your name is on your computer.

**Comment by Livingsavior** [comment]
@Adam- 
Just had the client crash while using the line, just spent the last 10 minutes hopping worlds to finally find my items.  I can share the log for it if  you'd like.

**Comment by alfred** [comment]
Ran the client for the last 10 minutes with those args on my current gorillas task, works like a dream. I'm on OS X High Sierra if it helps.

```
[ ~ ]$ java -version
java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)
```

**Comment by Hassinen** [comment]
I got crashed too with lastest fix. So there is still something wrong.

**Comment by Sackamanjaro** [comment]
> @Sackamanjaro
> -right click your runelite shortcut, select "open file location"
> 
> * copy the path in the explorer window that pops up.
> * open CMD
> * type `cd` followed by the pasting the path.
> * press enter, then paste the `java -Xmx512m -Xss2m -XX:CompileThreshold=1500 -Djna.nosys=true -jar RuneLite.jar --nojvm` line.
> 
> for example mine would be `cd C:\Users\YourName\AppData\Local\RuneLite` With "yourname" being whatever your name is on your computer.

command prompt says Error: Unable to access jarfile RuneLite.jar, whether I run cmd as admin or not. Is there a correct way to add this to a batch or something? I've done that before to disable hardware acceleration but I'm not exactly sure how that works and haven't had luck with my fiddling.

**Comment by tallyellowgiraffe** [comment]
I ran the client using that command line for 20 mins in the cave, no stutter, no crash. Seems very nice. Could you explain what exactly the line is doing @Adam- ?

**Comment by alfred** [comment]
AS a follow up to [this,](https://github.com/runelite/runelite/issues/9329#issuecomment-519300177) ended up going back after leaving the client open for a few days and got the stutters again. Restarting it didn't fix so I just kinda dealt with it, they were less frequent but still there

**Comment by Adam-** [comment]
The newer launcher was released, update to it let me know how much it helps.

**Comment by tallyellowgiraffe** [comment]
When I did some after the Runelite update I had less lag than previously. But when it was still more lag than when running the client using that command line

**Comment by h911reiver** [comment]
I don't know how bad it was before the update but I just went there for the first time this evening and the stuttering was severe enough for me to find my way here.

**Comment by Adam-** [comment]
Are either of you actually on the newer launcher? Vague comments does not really help.

**Comment by astrimbu** [comment]
Using RuneLite version 1.5.31.1 with Launcher version 1.6.0, I was still experiencing the aforementioned stuttering / hitching at demonic gorillas.

Starting RuneLite from the command line with Adam's `java -Xmx512m -Xss2m -XX:CompileThreshold=1500 -Djna.nosys=true -jar RuneLite.jar --nojvm` (Oracle Java 8) completely eliminated all stuttering.

**Comment by tallyellowgiraffe** [comment]
My experience was the same as astrimbu above.

**Comment by Adam-** [comment]
Since noone seems to want to verify the new launcher I'm just going to call this fixed since it works for me.

**Comment by simeonlg** [comment]
Issue is closed, but just wanting to chime in that it is also working for me.

Using launcher v1.6 I was experiencing the stuttering mentioned.

To allieviate the issue, I simply ran ```java -jar Runelite.jar``` from the Runelite folder, without the previously mentioned additional options.

Then updated launcher to v2 by reinstalling and have not ran into the issue at gorillas.
