### ISSUE TITLE
Unable to right click on XP tracker or Loot tracker sidebars on Mac. Right click still works on settings sidebar. 

### ISSUE THREAD

**Issue by Gogeta1217** [runelite/runelite#9357]
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)

Currently running macOS mojave 10.14.5. As stated in the title, I can't right click in either the XP tracker or loot tracker tabs. Have tried right clicking all over the entire tab but nothing pops up. Tried with bluetooth mouse, touchpad, and even remapping a keyboard key to perform right clicks. This is a recent issue as well. I used to be able to use them perfectly in the past. 

It is as though they are not registering the right clicks at all. But I am able to right click on the settings sidebar. 

I've also noticed that when typing something into the GE search, there will be a slight lag or freeze before I am able to actually start typing. 

**To Reproduce**
No steps needed. Simply unable to right click. Have tried resetting the laptop, logging in and out of runelite, restarting the client, and re-installing the entire thing. 

**Expected behavior**
Expect to be able to right click on XP trackers and loot to reset them. 

**Screenshots**

**Environment (please complete the following information):**
 - OS: macOS mojave 10.14.5
 - RuneLite version: 1.5.28
 - Launcher version: [e.g 1.5.2] Not sure, but I just reinstalled it so whatever the newest one under the download for mac option is on runelite.net 

**Additional context**
Add any other context about the problem here, e.g. logs. Your client logs can usually be found in
`C:\Users\<your_user_name>\.runelite\logs` on Windows and `~/.runelite/logs` on Linux and macOS.

[client.log](https://github.com/runelite/runelite/files/3388220/client.log)
[launcher.log](https://github.com/runelite/runelite/files/3388221/launcher.log)
[client_2019-07-01.0.log](https://github.com/runelite/runelite/files/3388222/client_2019-07-01.0.log)
[launcher_2019-07-01.0.log](https://github.com/runelite/runelite/files/3388223/launcher_2019-07-01.0.log)

**Comment by Nightfirecat** [comment]
Does this still happen if you [disable hardware acceleration](https://github.com/runelite/runelite/wiki/Disable-Hardware-Acceleration)?

**Comment by Gogeta1217** [comment]
No change after disabling hardware acceleration

**Comment by Gogeta1217** [comment]
Just checked, didn't fix the problem

**Comment by Hydrox6** [comment]
Closing since this is incredibly stale

**Comment by sizemo** [comment]
This same thing is happening to me, but on MacOS Ventura 13.3.1(a). M2 MacBook Air.

I have uninstalled the application, deleted the /.runelite folder and emptied the trash before attempting to reinstall. I have restarted my computer. I have tried my internal trackpad, an external trackpad, and an external Logitech wireless mouse, none of which work.

I'm not sure if this is somehow related, but every time I open Runelite on this computer, it creates a new icon in the recently opened area of the dock instead of just using the version of the application that's pinned in my dock. I haven't experienced this behavior before on any other Mac I've installed it on, Intel or Apple Silicon.

Environment (please complete the following information):

OS: MacOS Ventura 13.3.1(a)
RuneLite version: Bump for 1.10.1-SNAPSHOT
Launcher version: 2.6.3 and 2.6.4
