### ISSUE TITLE
Bank tags sometimes does not remember last tag tab

### ISSUE THREAD

**Issue by winterdaze** [runelite/runelite#9401]
**Describe the bug**
The bank interface is not remembering which tag tab I was last on. It just resets to the vanilla normal tab whenever I press esc or click the close button in the corner. Restarting the client seems to temporarily fix it, but it sporadically breaks again and multiple users are having this issue after the recent update.

**To Reproduce**
1. Open Bank
2. Select bank tag tab
3. Close Bank
4. Bank tag tab is not remembered

**Expected behavior**
Closing the bank interface while viewing a tag tab should display that tab when opening the interface again

**Screenshots**

**Environment (please complete the following information):**
 - OS: Windows 10
 - RuneLite version: 1.5.29
 - Launcher version: 1.6.2

**Additional context**
Logs didn't seem to have information related but I will include them anyways
[client.log](https://github.com/runelite/runelite/files/3409174/client.log)

**Comment by raiyni** [comment]
Is there anymore information on this? I can't reproduce this.

**Comment by 000000653** [comment]
video replicating it, took like 5-10 minutes of being logged in and me teleporting to ge instead of crafting guild (not sure if that could be relevant) before it started happening, but now it doesn't stay open, toggling option in the plugin also temporarily fixes it for me, I'm not sure what's causing it to happen

https://youtu.be/IzbOB-3t4uQ

logs from today, my internet dced earlier today, but there's nothing I can see during this session that'd be an issue
[client.log](https://github.com/runelite/runelite/files/3409239/client.log)

**Comment by raiyni** [comment]
My best guess is because of tick lag. There is some hoops we have to jump through for maintaining vanilla bank search. Thus a lot of logic is placed into `onGameTick` for determining current tab.

**Comment by Adam-** [comment]
Why has this only recently become a problem?

**Comment by raiyni** [comment]
It appears there are 2 different issues that can happen.

1. #9528 If you try and open a tag tab while not on bank tab 0. 

2. #9406 If you close the bank and open it too fast. It appears the bank closes and opens on the same tick.
