### ISSUE TITLE
Ensouled heads show up twice in the tag tabs icon search

### ISSUE THREAD

**Issue by Gamer1120** [runelite/runelite#9644]
![image](https://user-images.githubusercontent.com/9074448/62855977-e9f91200-bcf3-11e9-82b9-0d13e74f880e.png)

**Comment by Gamer1120** [comment]
![image](https://user-images.githubusercontent.com/9074448/62859642-fedaa300-bcfd-11e9-9338-61ea65574f41.png)
Not sure if it is a bug then. There's not much point in showing them twice, though.

**Comment by Dava96** [comment]
> ![image](https://user-images.githubusercontent.com/9074448/62859642-fedaa300-bcfd-11e9-9338-61ea65574f41.png)
> Not sure if it is a bug then. There's not much point in showing them twice, though.

It most likely acts this way because there are two separate item ID's for the heads, so two separate items. I don't think there would be an easy way to separate them so only one version shows up either. I'm sure there are other items that act the same way due to the nature of the ItemID's but perhaps they have different sprites making it look less obvious.

**Comment by deathbeam** [comment]
We can maybe use item variations to filter stuff like this
