### ISSUE TITLE
Key Mapping

### ISSUE THREAD

**Issue by yogaba1992** [runelite/runelite#9648]
I think it would be a great idea to add the option to turn off the "Press Enter To Chat" within the key mapping section.

**Comment by deathbeam** [comment]
But then you will not be able to type or use letter/number keybindings at all, what is kind of the point of key remapping plugin

**Comment by zwilkin** [comment]
+1 to @deathbeam , this is the entire point of the Key Mapping feature to be able to use keys that would normally be inputted as text, as bindings for certain actions. If you want to talk just turn it off and use the normal F-Key binds.

**Comment by jt3232** [comment]
I'm surprised you guys are going to all this effort to defend forcing Enter To Chat feature. It should be a simple coding fix. Then just put a warning saying any mapped keys will be ignored, use at your own risk. That way those of us who would like to only remap the escape through F12 keys dont have to "enter to chat" unnecessarily.

**Comment by Adam-** [comment]
By far the most common use case of key remapping is to remap WASD or 1234, or other non-F keys, that emit characters when pressed. Press enter to chat is required to make this work, since otherwise we can't tell if the key press should be remapped, or is text trying to be typed.

**Comment by jt3232** [comment]
That's why you give an option, off by default, with a warning, like I suggested above.

**Comment by Adam-** [comment]
I don't think what you are describing makes sense. Can you elaborate?

**Comment by jt3232** [comment]
Forgive me, I am a coder, but I have never seen this code base. It may be harder than I imagine it to be.

**Option 1: Configurable Button**

Give an option that is "disable press enter to chat".

Then add a warning alongside it saying, "If you use this option, any keys mapped for other purposes will be ignored when typing for chatting."

**Option 2: Auto check for Enter To Chat**

After any option is changed, check to see if any of the remapped keys are a "texting" key. If so, then automatically enable enter to chat, else if just like F keys are enabled, disable enter to chat.


I personally like option 2 and think it should be implemented.

**Comment by Adam-** [comment]
I find your explanation very difficult to understand. I think you mean: you would still have Enter to Chat mode, but you want to make it so pressing non-keybound keys enters typing mode without having to first press enter? This seems like it would be very confusing because if you did the standard wasd mapping, you would be unable to type starting with w/a/s/d.

**Comment by jt3232** [comment]
Yes, I realized as I was typing that Option 1 would not be ideal. That's why Option 2 is probably best.

**Comment by jt3232** [comment]
If the code checks to see any of the remapped keys are "texting" keys, which includes using wasd for camera controls, then auto enable enter to chat. If none of the remapped keys are "texting" keys, then disable enter to chat.

**Comment by Adam-** [comment]
This sounds like instead you are proposing entering typing mode whenever a character-emitting key is pressed, regardless of it is remapped. This would make it so remapping character-emitting keys would be nonfunctional though. Remapping character-emitting keys is the entire purpose of the plugin, because the base game lets you already remap the fkeys.

**Comment by jt3232** [comment]
The base game does this? Oh. I understand now.

**Comment by DarkPhoenix6853** [comment]
Sorry for necro, but I don't think this answer is enough. Keyboards have plenty of keys that don't impact someone's ability to chat normally - the entire numpad (or the entire number row, if someone uses the numpad to chat), tab, ctrl, alt, f-keys, esc, ins, del, home, end, pg up/down. If I (hypothetically) want to set up keybinds so that "space" actions are instead performed by tab or numpad 0 (which isn't something I can do in the base game), you're arbitrarily restricting my ease of using chat based on "the most common use case" rather than what I actually need the plugin to do. 

If a user wants to be able to use chat normally and also set up keybinds, they should have that option. Forcing "enter to chat" probably makes more sense as a default, but not as a rule. If they choose to have both an active chat and active keybinds, give a warning and assume any bound input is for the keybind, not chat. If they set up character keys as keybinds and can't use chat properly after the warning, that's on them. 

But I'm guessing the answer is going to be "too much work for too few users"... Maybe I just need to get back into Java, learn the API and do these things myself...
