### ISSUE TITLE
API requests returning 404

### ISSUE THREAD

**Issue by follmer** [runelite/runelite#9784]
**Describe the bug**
A GET to the following endpoint returns a 404 (should it?): http://api.runelite.net/runelite-1.5.32/chat/kc?boss=corp&name=kacy

**To Reproduce**
1. Go to http://api.runelite.net/runelite-1.5.32/chat/kc?boss=corp&name=hess
2. Get a 404 returned :(

**Expected behavior**
A 200, as stated by the api: https://static.runelite.net/api/http-service/#get-15

**Screenshots**

**Environment (please complete the following information):**
Windows, chrome

**Additional context**
n/a

**Comment by Unmoon** [comment]
It only returns 200 if the player in question recently used the `!kc <boss>` command.

**Comment by Adam-** [comment]
Specifically it requires the user to submit their kc up to the service, which remembers it for only a minute or two. We don't store kcs for very long in the service because:

1) it would allow users to access everyones KCs, without their consent
2) users would mass-submit fake KC data to the service just to grief it
3) we have no way of proving account ownership, so we can't filter out bad requests to it
